export interface Technology {
  id: number;
  name: string;
  country: string;
  category: 'decentralized' | 'stp-improvement' | 'smart-monitoring' | 'sludge-treatment';
  currentGap?: string;
  technology?: string;
  novelty?: string;
  details?: string;
  fieldApplication?: string;
  limitations?: string;
  status?: string;
  references?: {
    [key: string]: string;  // key = name, value = link (URL)
  };
  images?: string[];
  institution?: string;
  authors?: string[];
}

export const categories = {
  decentralized: 'Decentralized Units & NBS',
  'stp-improvement': 'STP Improvement',
  'smart-monitoring': 'Smart Monitoring',
  'sludge-treatment': 'Sludge/Solid Waste Treatment',
};

export const technologies: Technology[] = [
  // Decentralized units & NBS
  {
    id: 1,
    name: 'Floating Wetland',
    country: 'Denmark, USA',
    category: 'decentralized',
    currentGap: 'In India, natural based treatment solutions like wetlands are underutilized and often poorly maintained.',
    technology: 'Growing plants over floating platforms helps in absorbing and degrading pollutants from water bodies.',
    novelty: 'Selected plants and biofilm have been checked for showing its effectiveness in removing the specific pollutants.',
    details: 'Remove dissolved nutrients and heavy metals from water bodies. FW size is scalable and has modular design. Plants and the plant-microbe interactions in the lower surface of the floating island absorb and remove contaminants from the water while supporting other natural processes such as denitrification and sedimentation. Heavy metals (Cd, Cr(VI), Pb, Co, Cu, Pb, Ni, Se, Zn) and Nutrients (e.g. nitrate, ammonium, phosphate) removal from water body has been removed.',
    fieldApplication: 'Has been applied successfully in Denmark.',
    limitations: 'Requires regular monitoring and maintenance. To remove carbon from water bodies, microbial culturing needs to be done.',
    status: 'Communication is under progress.',
    references: {
      "Eco Island": "https://www.ecoisland.dk/services/",
      "Floating Island International Inc.": "https://www.floatingislandinternational.com/contact.html"
    },
    images: ['/Photos/Floating Wetlands-/Picture1.jpg', '/Photos/Floating Wetlands-/Picture2.png'],
  },
  {
    id: 2,
    name: 'Photosynthesis Based Wastewater Treatment Using Gir Cow Urine',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Conventional wetland treatment requires longer treatment time with less efficiency.',
    technology: 'Wastewater passed through wetland plants mixed with Gir cow urine gives high efficiency for pollutant degradation.',
    novelty: 'Gir cow urine has been tested along with wetland plants and found to have high catalytic properties for the degradation of domestic wastewater.',
    details: 'Leverage the nutrients in urine to support microbial and algal growth, aiding in purification. Gir Cow Urine\'s nutrients-rich composition enhances microbial activity. Microalgae and purple phototrophic bacteria can play a role in purifying in wastewater by absorbing nutrients and break down organic matter. Photosynthetic microorganism utilize its nutrients to enhance purification efficiency.',
    fieldApplication: 'Lab testing has been conducted with successful results.',
    limitations: 'Takes longer treatment time compared to conventional wastewater technologies.',
    status: 'Initial presentation conducted. Second phase meeting is in progress.',
    references: {'Pinakin Technology Solutions Pvt Ltd':"https://pinakin.co.in/"},
    images: ['/Photos/Photosynthesis Based/Picture3.jpg', '/Photos/Photosynthesis Based/Picture5.png'],
  },
  {
    id: 3,
    name: 'Soil Biotechnology (SBT)',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Treating wastewater using nature based solutions with less cost than STP is a big challenge.',
    technology: 'Soil biotechnology (SBT) is a terrestrial system for wastewater treatment based on the principle of the trickling filter.',
    novelty: 'Has potential to be used in place of STP, ETP, ZLD for industries and rivers and lake rejuvenation.',
    details: 'SBT systems are constructed from RCC, stonemasonry or soil bunds. They comprise a raw-water tank, bioreactor containment, treated water tank, piping and pumps. Suitable mineral constitution, bacterial culture and bio-indicator plants are the components of the system. Water passes through the artificial wetland vertically from top to down. Removal processes involves adsorption & filtration on media and biological degradation.',
    fieldApplication: 'SBT plant has been developed in IIT Bombay and has been implemented successfully in Bengaluru and Mumbai.',
    limitations: 'SBT type wastewater treatment plants require high land area of around 2.5 m²/ m³ of wastewater treatment.',
    status: 'Communication is under progress.',
    references: {'https://www.visionearthcare.com/technology/sbt':"https://www.visionearthcare.com/technology/sbt"},
    images: ['/Photos/Soil biotechnology (SBT)/Picture6.jpg', '/Photos/Soil biotechnology (SBT)/Picture7.png', '/Photos/Soil biotechnology (SBT)/Picture8.jpg'],
  },
  {
    id: 4,
    name: 'Phytorid',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Limited capacity of centralized treatment leads to untreated sewage disposal in water bodies. Need for zero-energy, low-maintenance treatment solutions.',
    technology: 'Constructed wetland technology developed by CSIR-NEERI that uses specific wetland plants in a subsurface flow system filled with porous media for natural wastewater treatment.',
    novelty: 'Self-sustainable, zero-energy, zero O&M technology using soil-free wetland treatment. Uses both wetland and non-wetland plant species acclimatized for specific nutrient removal.',
    details: 'System consists of Primary Settling Cell, Advanced Filter Cell (gravel/stones in layers), and Phytorid Treatment Cell with plants like Elephant grass, Cattails, Reeds, Cannas, and Yellow flag iris. Plants act as nutrient sinkers directly from wastewater without requiring soil. Removal efficiency: BOD (78-84%), COD (similar), TSS (70-80%), Nitrogen (70-75%), Phosphorus (52-64%), Fecal coliform (90-97%). Wastewater flows vertically through porous media maintaining subsurface flow. Technology works through physical filtration, sedimentation, adsorption, and biological degradation by plant-root-microbe interactions.',
    fieldApplication: 'Successfully implemented at CSIR-NCL, Mumbai University, Raj Bhawan, various locations in Mumbai, Thane, Nashik, Panvel, Allahabad, and Matheran. Used for lake rejuvenation projects.',
    limitations: 'Requires approximately 35 sq.m. area for 20 m³/day treatment capacity. Treated water primarily suitable for non-potable uses like gardens, fountains, and irrigation.',
    status: 'Technology patented in India, Europe, and Australia. Widely commercialized and implemented across India.',
    references: {'NEERI Nagpur':"https://www.neeri.res.in/contents/banner_details/phytorid-wastewater-treatment-technology/5b193f6eaacd7googtrans(en%7Cen)#googtrans(en|en)"},
    images: ['/Photos/Phytorid/Picture9.png', '/Photos/Phytorid/Picture10.png'],
  },
  {
    id: 5,
    name: 'Freeze Technology',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Energy-intensive desalination and concentration processes create high operational costs in water treatment.',
    technology: 'Freeze crystallization technology that separates water from contaminants by controlled freezing, producing ice crystals of pure water.',
    novelty: 'Lower energy consumption compared to thermal evaporation. Can concentrate wastewater while producing pure water crystals.',
    details: 'Process involves cooling wastewater below freezing point, forming ice crystals of pure water while contaminants remain in concentrated liquid phase. Ice crystals are separated and melted to produce clean water. Effective for desalination, heavy metal removal, and wastewater concentration. Energy requirement is theoretically lower than evaporation as latent heat of freezing is less than vaporization.',
    fieldApplication: 'Pilot-scale implementations in industrial wastewater treatment, particularly for high-salinity streams.',
    limitations: 'Ice-liquid separation can be challenging. Scaling and fouling issues. Pre-treatment may be required for suspended solids. Capital cost can be high.',
    status: 'Emerging technology with ongoing pilot projects.',
    references: ['Various Indian research institutions'],
    images: ['/Photos/Freeze Technology/Picture11.png', '/Photos/Freeze Technology/Picture12.png'],
  },
  {
    id: 6,
    name: 'Nano Bubble',
    country: 'USA',
    category: 'decentralized',
    currentGap: 'Traditional aeration systems have low oxygen transfer rates, high energy consumption, and limited effectiveness in treating complex wastewater with surfactants and inhibitory compounds.',
    technology: 'Nanobubble generators produce ultra-fine gas bubbles (less than 1 μm diameter) with unique properties including high stability, low buoyancy, and ability to generate reactive oxygen species.',
    novelty: 'Nanobubbles remain suspended in water for extended periods (hours to months), have charged surfaces for contaminant attraction, and generate free radicals for enhanced oxidation. Oxygen transfer efficiency is significantly higher than conventional aeration.',
    details: 'Nanobubbles possess large surface area-to-volume ratio enabling efficient gas transfer and contaminant interaction. Applications include: enhanced flotation for grease/oil removal, improved aerobic biological treatment (activated sludge, MBR, constructed wetlands), protection against biological process inhibition from surfactants and quaternary ammonium compounds (QACs), oxidation of organic compounds through ROS generation. Improves TOC removal (49% vs 27-36% conventional), ammonia removal (65% vs 22-48%), and power generation in microbial fuel cells (5.5x higher). Reduces BOD, COD, and energy consumption while improving treatment stability.',
    fieldApplication: 'Successfully deployed at municipal WWTPs (City of Lodi, California plants), food & beverage facilities (Meister Cheese Co.), industrial facilities, and aquaculture operations. Used for lake/pond restoration and agricultural irrigation enhancement.',
    limitations: 'Requires specialized nanobubble generators. Initial capital investment for equipment. Performance depends on proper integration with existing systems. Not suitable for all contaminant types.',
    status: 'Commercially available and actively deployed. Major vendors include Moleaer (USA), NICO Nanobubble India Co.',
    references: ['Moleaer Inc.', 'NICO Nanobubble India Co.', 'Scientific literature in Water Research, Science of the Total Environment, ACS ES&T Engineering'],
    images: ['/Photos/Nano-Bubble Generators/Picture13.jpg', '/Photos/Nano-Bubble Generators/Picture14.jpg'],
  },
  {
    id: 7,
    name: 'Watopi',
    country: 'Denmark',
    category: 'decentralized',
    currentGap: 'Need for decentralized, nature-based water treatment solutions with minimal infrastructure in water-scarce regions.',
    technology: 'Modular wetland-based water treatment system that combines natural filtration with constructed wetland principles.',
    novelty: 'Containerized or modular design allows for flexible deployment. Integrates Danish expertise in wetland engineering.',
    details: 'System uses series of treatment cells with different wetland plants and substrates. Natural biological processes combined with physical filtration. Suitable for small communities and decentralized applications. Low energy requirement with focus on sustainability.',
    fieldApplication: 'Implemented in Denmark and exported to developing regions for community-scale treatment.',
    limitations: 'Climate-dependent performance. Requires land area. Seasonal variations in efficiency.',
    status: 'Commercial technology available from Danish providers.',
    references: ['Danish water technology companies'],
    images: ['/Photos/Watopi- BioKube, Denmark/Picture15.png', '/Photos/Watopi- BioKube, Denmark/Picture16.jpg', '/Photos/Watopi- BioKube, Denmark/Picture17.jpg'],
  },
  {
    id: 8,
    name: 'Microbial Fuel Cell',
    country: 'USA',
    category: 'decentralized',
    currentGap: 'Conventional wastewater treatment is energy-intensive, consuming significant power without energy recovery.',
    technology: 'Bioelectrochemical system where microorganisms oxidize organic matter and generate electricity through electron transfer to an electrode.',
    novelty: 'Simultaneous wastewater treatment and electricity generation. Can be integrated with other technologies like constructed wetlands and nanobubbles for enhanced performance.',
    details: 'MFCs contain anode chamber with anaerobic bacteria that oxidize organics and release electrons, cathode chamber with oxygen or other electron acceptor, and proton exchange membrane. Electrons flow through external circuit generating power. When coupled with nanobubble-aerated constructed wetlands, power generation increases 5.5x (to 29 mW/m²). Can treat domestic, industrial, and agricultural wastewater while recovering energy.',
    fieldApplication: 'Laboratory and pilot-scale demonstrations. Research installations at universities and demonstration sites. Integration with constructed wetlands shown in field trials.',
    limitations: 'Low power density compared to energy consumption of treatment. Expensive electrode materials. Membrane fouling. Scale-up challenges. Still largely in research/pilot phase for practical applications.',
    status: 'Emerging technology in transition from research to early commercial adoption.',
    references: ['Various US universities and research institutions', 'Scientific literature on bioelectrochemical systems'],
    images: ['/Photos/Microbial Fuel Cell- Aquacyl; USA/Picture18.png', '/Photos/Microbial Fuel Cell- Aquacyl; USA/Picture19.jpg'],
  },
  {
    id: 9,
    name: 'Water Mantra Technology',
    country: 'Singapore',
    category: 'decentralized',
    currentGap: 'Need for compact, efficient decentralized water treatment for urban and semi-urban areas with space constraints.',
    technology: 'Integrated water treatment system combining multiple treatment stages in compact footprint for decentralized applications.',
    novelty: 'Modular design with smart monitoring capabilities. Optimized for tropical climates and dense urban environments.',
    details: 'Multi-barrier treatment approach combining physical, chemical, and biological processes. Automated monitoring and control systems. Designed for small to medium capacity installations. Emphasis on water reuse and recovery.',
    fieldApplication: 'Deployed in Singapore and Southeast Asian markets for residential, commercial, and industrial sites.',
    limitations: 'Requires regular maintenance and monitoring. Initial cost may be higher than conventional systems.',
    status: 'Commercial technology from Singapore-based company.',
    references: ['Singapore water technology sector'],
    images: ['/Photos/Water Mantra-h2Omantra; Singapore/Picture20.png', '/Photos/Water Mantra-h2Omantra; Singapore/Picture21.png', '/Photos/Water Mantra-h2Omantra; Singapore/Picture22.png'],
  },
  {
    id: 10,
    name: 'Electro-oxidation',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Difficulty in treating recalcitrant organic pollutants, dyes, and toxic compounds that resist biological treatment.',
    technology: 'Advanced oxidation process using electrochemical reactions at electrode surfaces to oxidize and mineralize organic pollutants.',
    novelty: 'Generates powerful hydroxyl radicals and other oxidants in-situ without chemical addition. Effective for destroying refractory organics.',
    details: 'Uses dimensionally stable anodes (DSA) or boron-doped diamond (BDD) electrodes. When current is applied, water is oxidized at the anode surface generating hydroxyl radicals (·OH) and other reactive oxygen species. These oxidize organic pollutants into CO2, H2O, and simple inorganic compounds. Effective for COD reduction, color removal, and destruction of pharmaceuticals, pesticides, and industrial chemicals. Can be combined with biological treatment for complete mineralization.',
    fieldApplication: 'Used in pharmaceutical, textile, tannery, and chemical industries in India. Particularly effective as polishing step after biological treatment.',
    limitations: 'High energy consumption. Electrode cost and lifespan. Formation of chlorinated byproducts if chlorides present. Regular electrode maintenance required.',
    status: 'Commercial technology with established Indian suppliers.',
    references: ['Indian electrochemical technology providers', 'IIT research groups'],
    images: ['/Photos/Electro Oxidation Technology; Pinakin/Picture23.jpg', '/Photos/Electro Oxidation Technology; Pinakin/Picture24.png', '/Photos/Electro Oxidation Technology; Pinakin/Picture25.png'],
  },
  {
    id: 11,
    name: 'Onsite Oxidation',
    country: 'Denmark',
    category: 'decentralized',
    currentGap: 'Need for effective on-site treatment of micropollutants and emerging contaminants at source.',
    technology: 'Advanced oxidation technology for on-site treatment using ozone, UV, or combined oxidation processes.',
    novelty: 'Point-of-generation treatment prevents pollutant entry into water systems. Compact systems for decentralized application.',
    details: 'Employs oxidation processes such as UV/H2O2, ozonation, or Fenton oxidation for destroying micropollutants, pharmaceuticals, and persistent organics. Can be installed at hospitals, laboratories, and industrial sites to treat wastewater at source. Reduces burden on central treatment plants.',
    fieldApplication: 'Installed at Danish hospitals and pharmaceutical facilities for treating medicinal wastewater.',
    limitations: 'Operating costs for oxidant chemicals or UV power. Byproduct formation possible. Requires skilled operation.',
    status: 'Commercial solutions available from Danish water technology companies.',
    references: ['Danish Environmental Protection Agency', 'Nordic water technology providers'],
    images: ['/Photos/Onsite Oxidation- hpnow; Denmark/Picture26.jpg', '/Photos/Onsite Oxidation- hpnow; Denmark/Picture27.jpg'],
  },
  {
    id: 12,
    name: 'Pulse Plasma',
    country: 'Germany',
    category: 'decentralized',
    currentGap: 'Conventional treatment methods struggle with persistent organic pollutants, pathogens, and pharmaceutical residues.',
    technology: 'Non-thermal plasma technology using pulsed electrical discharges in water to generate reactive species for pollutant degradation and disinfection.',
    novelty: 'Generates UV radiation, shockwaves, and multiple reactive species (OH·, O3, H2O2) simultaneously without chemical addition.',
    details: 'High voltage pulses create plasma streamers in water, producing physical and chemical effects: UV photolysis, acoustic cavitation, pyrolysis, and generation of reactive oxygen and nitrogen species. Simultaneously degrades organics and inactivates microorganisms. Effective against pharmaceuticals, PFAS, dyes, and pathogens. Can treat small volumes efficiently.',
    fieldApplication: 'Pilot installations in Germany for pharmaceutical wastewater and hospital effluent treatment. Research applications in water disinfection.',
    limitations: 'High energy requirement per volume treated. Electrode erosion. Suitable mainly for small flow rates. Capital cost can be significant.',
    status: 'Advanced development stage with pilot implementations.',
    references: ['German research institutions', 'Fraunhofer Institute', 'Technical universities'],
    images: ['/Photos/Pulse Plasma- Fidtech; Germany/Picture28.png', '/Photos/Pulse Plasma- Fidtech; Germany/Picture29.png', '/Photos/Pulse Plasma- Fidtech; Germany/Picture30.jpg'],
  },
  {
    id: 13,
    name: 'MVR Technology',
    country: 'Denmark',
    category: 'decentralized',
    currentGap: 'Energy-intensive evaporation processes in zero liquid discharge (ZLD) and brine concentration applications.',
    technology: 'Mechanical Vapor Recompression uses a compressor to recycle and reuse heat energy from evaporation, significantly reducing energy consumption.',
    novelty: 'Energy recovery through vapor recompression reduces thermal energy requirement by 90% compared to conventional evaporation.',
    details: 'Wastewater is heated and evaporated. The generated vapor is compressed, which increases its temperature and pressure. This hot compressed vapor is used to heat incoming wastewater in a heat exchanger, creating a self-sustaining cycle. Produces distilled water and concentrated brine/solids. Typical energy consumption 20-25 kWh/m³ of distillate compared to 60-80 kWh/m³ for conventional evaporation. Particularly effective for ZLD applications, desalination concentrate treatment, and industrial wastewater with high TDS.',
    fieldApplication: 'Widely used in Europe for industrial ZLD, dairy industry, pharmaceutical, and chemical industries. Proven technology with thousands of installations globally.',
    limitations: 'High capital investment. Requires skilled maintenance. Scaling/fouling issues with high hardness water. Not economical for very low TDS water.',
    status: 'Mature commercial technology with established vendors.',
    references: ['Danish industry', 'GEA Process Engineering', 'European ZLD providers'],
    images: ['/Photos/MVR Technology- Envotherm; Denmark/Picture31.png', '/Photos/MVR Technology- Envotherm; Denmark/Picture32.png'],
  },
  {
    id: 14,
    name: 'Geotubes - Solmax',
    country: 'India & Australia',
    category: 'decentralized',
    currentGap: 'Sludge dewatering is costly, energy-intensive, and requires significant infrastructure. Traditional methods have high operating costs.',
    technology: 'Large geotextile tubes that dewater sludge through natural filtration and gravity drainage. Polymers flocculate solids which are retained in the tube while water drains through the permeable fabric.',
    novelty: 'Passive dewatering requiring no mechanical equipment or external energy. Can handle large volumes in short time with minimal labor.',
    details: 'High-strength woven geotextile tubes (up to 100m long) are filled with conditioned sludge. Polymer is added for flocculation. Solids are retained inside while water filters through the fabric. Solar drying and consolidation occur over weeks to months, achieving 15-30% solids content. Can be used for dredged materials, industrial sludge, wastewater biosolids. Tubes can be stacked or reused.',
    fieldApplication: 'Used extensively in India and Australia for sewage sludge, mining tailings, dredging projects, and industrial waste. Hundreds of projects completed.',
    limitations: 'Requires large land area. Dewatering time is long (weeks to months). Performance affected by weather/climate. Not suitable where rapid turnaround needed. Final disposal of dewatered cake still required.',
    status: 'Established commercial technology. Solmax and other vendors provide turnkey solutions.',
    references: ['Solmax International', 'TenCate Geosynthetics', 'Indian and Australian environmental engineering firms'],
    images: ['/Photos/Geotubes/Picture33.jpg', '/Photos/Geotubes/Picture34.png'],
  },
  {
    id: 15,
    name: 'Poseidon Pellets – Phosphorous Removal',
    country: 'USA',
    category: 'decentralized',
    currentGap: 'Phosphorus removal in wastewater treatment often requires chemical dosing or expensive biological processes. Nutrient recovery is not practiced.',
    technology: 'Iron-based reactive media in pellet form that adsorbs phosphorus from wastewater through surface reactions, enabling passive nutrient removal.',
    novelty: 'Simultaneous phosphorus removal and recovery. Media can be regenerated or used as fertilizer. Passive treatment without chemical addition.',
    details: 'Poseidon pellets are iron oxide-coated media with high affinity for phosphate. As water flows through pellet bed, phosphate is adsorbed onto iron surface through ligand exchange and precipitation reactions. Achieves low effluent phosphorus levels (<0.1 mg/L). Spent media can be regenerated with alkali solution recovering phosphate for fertilizer use, or used directly as slow-release fertilizer. Can be used in filters, columns, or reactive barriers.',
    fieldApplication: 'Implemented at municipal WWTPs in USA for tertiary phosphorus removal. Used in stormwater treatment and agricultural runoff management.',
    limitations: 'Media requires periodic replacement or regeneration. Pre-filtration needed to prevent clogging. Limited capacity requires sizing based on phosphorus load. Not effective for nitrogen removal.',
    status: 'Commercial technology with proven installations.',
    references: ['Advanced Water Management Inc.', 'US EPA nutrient removal case studies'],
    images: ['/Photos/Poseidon Pellets/Picture35.jpg', '/Photos/Poseidon Pellets/Picture36.jpg', '/Photos/Poseidon Pellets/Picture37.jpg'],
  },
  {
    id: 16,
    name: 'Coagulation-Flocculation',
    country: 'China',
    category: 'decentralized',
    currentGap: 'Removal of suspended solids, colloids, and turbidity requires effective solid-liquid separation. Emerging pollutants need advanced treatment.',
    technology: 'Chemical treatment process using coagulants (aluminum/iron salts or polymers) to destabilize particles, followed by flocculants to form large settleable flocs.',
    novelty: 'Advanced high-efficiency coagulants and flocculants developed in China. Magnetic coagulation and electrocoagulation variants offer enhanced performance.',
    details: 'Coagulant chemicals neutralize particle surface charges causing destabilization. Flocculants bridge particles forming large flocs that settle rapidly. Process parameters: rapid mixing for coagulant dispersion (1-3 min), slow mixing for floc formation (15-30 min), sedimentation for separation. Removes suspended solids, turbidity, color, phosphorus, heavy metals, and some organic matter. New developments include polyaluminum chloride (PAC), polyferric sulfate (PFS), and composite coagulants. Can be combined with membrane filtration or dissolved air flotation.',
    fieldApplication: 'Universally applied in Chinese drinking water plants and industrial WWTPs. Used in paper, textile, mining, and municipal applications. Millions of installations.',
    limitations: 'Generates chemical sludge requiring disposal. pH dependent. Chemical costs. Not effective alone for dissolved organics or nutrients. Overdosing can worsen water quality.',
    status: 'Mature technology continuously being improved with novel coagulants.',
    references: ['Chinese water treatment industry', 'Major coagulant manufacturers in China', 'Research from Tsinghua, Tongji universities'],
    images: ['/Photos/Coagulation/Picture38.png', '/Photos/Coagulation/Picture39.png'],
  },
  // STP Improvement
  {
    id: 17,
    name: 'MBR',
    country: 'France & USA',
    category: 'stp-improvement',
    currentGap: 'Conventional activated sludge with clarifiers requires large footprint, produces variable effluent quality, and has limited ability to treat micropollutants.',
    technology: 'Membrane Bioreactor combines activated sludge biological treatment with membrane filtration (microfiltration or ultrafiltration) for solid-liquid separation.',
    novelty: 'Eliminates need for secondary clarifiers. Produces high-quality effluent suitable for reuse. Can operate at higher MLSS concentrations (8,000-12,000 mg/L).',
    details: 'Microorganisms degrade organic matter and nutrients in bioreactor. Membrane module (submerged or external) filters treated water, completely retaining biomass and suspended solids. Produces effluent with near-zero TSS and turbidity, very low BOD (<5 mg/L) and COD, reduced pathogens. Average removal: BOD 88%, COD 84%, TN 65%, TP 60%. Enables longer SRT for nitrification and growth of slow-growing microorganisms. Compact footprint (1/3 to 1/2 of conventional). Effluent suitable for non-potable reuse, irrigation, industrial processes.',
    fieldApplication: 'Thousands of installations globally including large municipal plants (>100,000 PE). Major installations in France, USA, Asia. Used in water-scarce regions for water reuse. Industrial applications in food/beverage, pharmaceutical, semiconductor industries.',
    limitations: 'Membrane fouling requiring regular cleaning. Higher energy consumption for aeration and membrane operation. Membrane replacement costs. Requires skilled operation. Capital cost 20-40% higher than conventional treatment.',
    status: 'Mature commercial technology. Leading vendors: Suez (France), Evoqua (USA), Toray, Mitsubishi.',
    references: ['Suez Water Technologies', 'Evoqua', 'Membrane Bioreactor Industry Consortium', 'IWA MBR specialist group'],
    images: ['/Photos/Membrane Bioreactor/Picture40.png', '/Photos/Membrane Bioreactor/Picture41.jpg'],
  },
  {
    id: 18,
    name: 'MBBR',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Activated sludge requires large tank volumes, complex sludge recirculation, and sensitive operation. Limited capacity to handle organic shock loads.',
    technology: 'Moving Bed Biofilm Reactor uses free-floating plastic carriers that provide surface for biofilm growth while moving continuously in the aeration tank.',
    novelty: 'Combines benefits of suspended growth (activated sludge) and attached growth (biofilm) systems. No sludge recirculation needed. Compact design with high volumetric loading.',
    details: 'Developed in late 1980s by Prof. Hallvard Ødegaard (Norway). Carriers (filling 40-70% of reactor volume) have density close to water and move freely via aeration or mechanical mixing. Large protected surface area (>5,500 m²/m³ for advanced media) supports high biomass concentration (4,000-8,000 mg/L MLSS equivalent). Biofilm protected from toxic shocks. Processes: BOD/COD removal, nitrification, denitrification (in anoxic zones). Average removal: BOD 87%, COD 80%, TN 56%, TP 54%. Can retrofit existing tanks to increase capacity. Applications include municipal WWTPs, industrial wastewater (pulp & paper, food processing, petrochemical), and aquaculture.',
    fieldApplication: 'Over 1000 installations worldwide. Widely used in Scandinavia, North America, Asia. Successful retrofits increasing plant capacity 2-3x. Works in extreme climates from Arctic to tropical.',
    limitations: 'Higher energy consumption than activated sludge to keep carriers suspended. Requires secondary clarifier for suspended solids separation (unless combined with membrane). Media replacement every 10-15 years. Not as effective as MBR for complete solid removal.',
    status: 'Mature proven technology. Major vendors: Veolia/AnoxKaldnes (Denmark), SSI Aeration, Ecologix.',
    references: ['AnoxKaldnes (Veolia)', 'SSI Aeration', 'Norwegian University of Science and Technology', 'Wikipedia MBBR article'],
    images: ['/Photos/Membrane Bioreactor/Picture40.png', '/Photos/Membrane Bioreactor/Picture41.jpg'],
  },
  {
    id: 19,
    name: 'IFAS Technology',
    country: 'Canada',
    category: 'stp-improvement',
    currentGap: 'Existing activated sludge plants reaching capacity limits. Need to upgrade without expanding tank volume.',
    technology: 'Integrated Fixed-Film Activated Sludge combines suspended growth activated sludge with attached growth biofilm media in the same tank.',
    novelty: 'Hybrid system providing benefits of both technologies. Media can be added to existing tanks for capacity increase without construction.',
    details: 'Fixed media (plastic carriers or rope/fabric media) are added to activated sludge aeration tanks. Both suspended and attached biomass treat wastewater simultaneously. Biofilm on media provides additional treatment capacity and protects nitrifying bacteria. Suspended biomass handles bulk organic removal and provides denitrification. System maintains conventional sludge recirculation. Particularly effective for enhanced nitrogen removal through simultaneous nitrification-denitrification. Can increase treatment capacity 50-100% in existing tankage. Lower footprint than conventional activated sludge upgrades.',
    fieldApplication: 'Numerous installations across North America for municipal WWTP upgrades. Successfully implemented in Canada, USA for plants requiring nutrient removal compliance. Typical size range 5,000 to 500,000 PE.',
    limitations: 'More complex than pure MBBR or activated sludge. Requires careful balance between suspended and attached biomass. Mixing and aeration requirements higher than conventional AS. Media fouling possible with certain wastewaters.',
    status: 'Proven commercial technology for capacity upgrades.',
    references: ['InfraCor (Canada)', 'Evoqua Technologies', 'Various Canadian municipalities', 'WEF publications'],
    images: ['/Photos/Integrated Fixed-film Activated Sludge/Picture46.png', '/Photos/Integrated Fixed-film Activated Sludge/Picture47.emf'],
  },
  {
    id: 20,
    name: 'Membranes',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Need for advanced solid-liquid separation, pathogen removal, and water reuse quality. Conventional clarification insufficient for stringent standards.',
    technology: 'Pressure-driven membrane filtration technologies including Microfiltration (MF), Ultrafiltration (UF), Nanofiltration (NF), and Reverse Osmosis (RO) for water treatment.',
    novelty: 'Absolute barriers for particles, microorganisms, and dissolved contaminants depending on membrane type. Modular and scalable design.',
    details: 'MF/UF (0.01-0.1 μm pore size): Remove suspended solids, bacteria, protozoa, viruses. Used in MBR and tertiary filtration. NF (0.001 μm): Remove hardness, divalent ions, organic molecules, partial desalination. RO (<0.001 μm): Remove dissolved salts, metals, organics; produces ultrapure water. Applications: drinking water production, wastewater reuse, desalination, industrial water purification. Can achieve >99.9% removal of pathogens. Danish companies lead in ceramic membrane development (higher fouling resistance than polymeric).',
    fieldApplication: 'Global market with millions of installations. Municipal drinking water, wastewater reuse plants, seawater desalination, industrial processes, pharmaceutical production. Increasing adoption in water-scarce regions.',
    limitations: 'Membrane fouling and scaling requiring cleaning. Energy intensive especially for RO. Concentrate/brine disposal. Membrane replacement costs. Pre-treatment required for many applications.',
    status: 'Mature commercial technology with continuous innovation in materials and configurations.',
    references: ['Danish water technology sector', 'Major membrane manufacturers: Toray, Dow, Hydranautics, Pentair'],
    images: ['/Photos/Membranes; Aquaporin/Picture48.png', '/Photos/Membranes; Aquaporin/Picture49.png', '/Photos/Membranes; Aquaporin/Picture50.png'],
  },
  {
    id: 21,
    name: 'Ceramic Membrane Filtration',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Polymeric membranes degrade with harsh chemicals, high temperatures, and aggressive cleaning. Limited lifespan in difficult applications.',
    technology: 'Membranes made from inorganic materials (alumina, titania, zirconia) offering superior chemical and thermal resistance compared to polymer membranes.',
    novelty: 'Withstands pH 0-14, temperatures up to 150°C, aggressive oxidizing cleaners. Longer lifespan (>10 years vs 3-7 for polymers). Higher fouling resistance.',
    details: 'Ceramic membranes have rigid porous structure with precise pore size control. Available in MF and UF range. Can be cleaned with strong acids, bases, oxidizers without degradation, enabling recovery from severe fouling. Applications: dairy processing, oil-water separation, municipal drinking water, harsh industrial wastewaters. Denmark is global leader in ceramic membrane technology. Higher flux rates and cleaning efficiency reduce overall operating costs despite higher capital cost.',
    fieldApplication: 'Growing adoption in drinking water plants in Denmark, Netherlands, France. Industrial applications in food/beverage, petrochemical, pharmaceutical industries. Several large municipal installations.',
    limitations: 'Higher capital cost (2-3x polymeric membranes). Brittleness requires careful handling. Limited suppliers compared to polymeric. Not available in all configurations (no spiral wound).',
    status: 'Established technology with expanding market. Expected to grow as costs decrease.',
    references: ['LiqTech (Denmark)', 'TAMI Industries', 'Metawater', 'Danish Technological Institute'],
    images: ['/Photos/Ceramic Membrane Filtration/Picture51.png'],
  },
  {
    id: 22,
    name: 'Revolving Algal Biofilm System',
    country: 'USA',
    category: 'stp-improvement',
    currentGap: 'Algae-based treatment requires large ponds, long HRT, and difficult biomass harvesting. Conventional algae systems have low productivity.',
    technology: 'Rotating biofilm reactor where algae grow on slowly revolving vertical surfaces alternately exposed to wastewater and air/sunlight.',
    novelty: 'Higher algae productivity than ponds through optimized light exposure. Easy harvesting by scraping biofilm. Simultaneous nutrient removal and biomass production.',
    details: 'System consists of rotating cylinders or belts with textured surface submerged in wastewater. Algal biofilm grows on surface. As cylinders rotate, biofilm is alternately exposed to nutrient-rich water and to air/light for photosynthesis. Mature biofilm is scraped off for harvest. Algae uptake nitrogen and phosphorus while producing oxygen that supports aerobic bacteria. Integrated algae-bacteria system treats wastewater. Harvested algae biomass can be used for biofuel, animal feed, or fertilizer. Treats municipal and agricultural wastewater with high nutrient content. Removal: >90% ammonia, >80% phosphorus.',
    fieldApplication: 'Pilot and demonstration projects in USA. Installations at universities and research facilities. Several commercial installations for agricultural runoff treatment.',
    limitations: 'Requires sunlight - limited in cloudy regions or winter. Seasonal performance variation. Mechanical complexity of rotating system. Capital and maintenance costs. Algae biomass utilization pathways still developing.',
    status: 'Emerging commercial technology transitioning from research.',
    references: ['US DOE funded projects', 'Utah State University research', 'Gross-Wen Technologies'],
    images: ['/Photos/Revolving Algal Biofilm System/Picture52.png', '/Photos/Revolving Algal Biofilm System/Picture53.png', '/Photos/Revolving Algal Biofilm System/Picture54.png'],
  },
  {
    id: 23,
    name: 'Nicotinamide Adenine Dinucleotide (NADH) Probes',
    country: 'U.S.A',
    category: 'stp-improvement',
    currentGap: 'Traditional wastewater monitoring relies on grab samples and lab analysis with delayed results. Real-time process control is limited.',
    technology: 'Optical sensors that measure NADH fluorescence as indicator of microbial activity and process performance in biological wastewater treatment.',
    novelty: 'Real-time measurement of biological activity. NADH is key coenzyme in microbial metabolism - its concentration reflects treatment effectiveness.',
    details: 'NADH molecules fluoresce when excited by UV light. Fluorescence intensity correlates with active biomass concentration and metabolic activity. Probes inserted into bioreactors provide continuous monitoring. Helps optimize: aeration rates, substrate loading, nutrient dosing, early warning of process upsets. Enables automated process control for stable treatment performance and energy savings. Can reduce aeration energy 10-30% through optimized control.',
    fieldApplication: 'Implemented in advanced WWTPs in USA and Europe. Used in industrial biological treatment for breweries, food processing, pharmaceutical plants. Hundreds of installations globally.',
    limitations: 'Probe fouling requiring cleaning. Interference from other fluorescent compounds. Requires calibration and correlation with conventional parameters. Cost of sensors and control systems.',
    status: 'Commercial technology with proven applications.',
    references: ['Real Tech Inc.', 'Hach Company', 'Endress+Hauser', 'Scientific literature on biological process monitoring'],
    images: ['/Photos/Nicotinamide Adenine Dinucleotide/Picture55.png', '/Photos/Nicotinamide Adenine Dinucleotide/Picture56.png'],
  },
  {
    id: 24,
    name: 'Supercritical Water Oxidation',
    country: 'USA',
    category: 'stp-improvement',
    currentGap: 'Hazardous and recalcitrant organic wastes cannot be treated by biological methods. Incineration creates air emissions.',
    technology: 'Advanced oxidation using water above critical point (374°C, 221 bar) where organic compounds rapidly oxidize to CO2 and water.',
    novelty: 'Complete destruction of organics (>99.99%) in minutes. No air emissions. Salts precipitate and can be recovered.',
    details: 'Waste is pressurized and heated above supercritical point. Oxygen is injected. In supercritical water, organic compounds are completely miscible and oxidize rapidly to CO2, H2O, and minerals. Reaction time: seconds to minutes. Destroys: hazardous wastes, pharmaceuticals, sewage sludge, chemical weapons, PCBs, dioxins. Energy intensive but can be partially recovered. Produces clean water and recoverable salts. No toxic byproducts.',
    fieldApplication: 'Commercial plants in USA for destruction of chemical warfare agents and hazardous wastes. Pilot plants for sewage sludge treatment. Used by US military and specialty waste treatment companies.',
    limitations: 'Very high capital and operating costs. Extreme operating conditions require special materials. High energy requirement. Corrosion issues with salts. Economic mainly for high-value hazardous waste destruction, not bulk wastewater.',
    status: 'Mature but niche technology for specific applications.',
    references: ['General Atomics', 'US Department of Defense programs', 'Scientific literature on SCWO'],
    images: ['/Photos/Supercritical Water Oxidation/Picture57.png', '/Photos/Supercritical Water Oxidation/Picture58.jpg', '/Photos/Supercritical Water Oxidation/Picture59.png', '/Photos/Supercritical Water Oxidation/Picture60.png'],
  },
  {
    id: 25,
    name: 'Energy-Positive Wastewater Treatment',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Wastewater treatment is energy-intensive, consuming 1-3% of total electricity in developed countries. Need for energy-neutral or positive operations.',
    technology: 'Integrated treatment approach maximizing energy recovery from wastewater organics through anaerobic digestion, combined with energy efficiency measures.',
    novelty: 'Produces more energy than consumed. Transforms WWTP from energy consumer to energy producer and resource recovery facility.',
    details: 'Key elements: maximize carbon capture to anaerobic digestion (chemically enhanced primary treatment, sidestream treatment, A-stage in AB process), optimize anaerobic digestion (thermal hydrolysis pretreatment, co-digestion with other organics), maximize biogas yield and utilize efficiently (CHP, biogas upgrading to vehicle fuel), minimize aeration energy (efficient diffusers, process control, use of MBR or IFAS), energy recovery from effluent (heat exchangers). Danish WWTPs like Avedøre, Marselisborg, and Ejby Mølle achieve >100% energy self-sufficiency, producing surplus renewable energy. Combines with nutrient recovery for circular economy.',
    fieldApplication: 'Multiple full-scale energy-positive WWTPs operating in Denmark. Examples: Marselisborg WWTP (Aarhus) produces 150% of energy consumed. Ejby Mølle WWTP energy neutral. Technology exported worldwide.',
    limitations: 'Requires holistic redesign of WWTP. High initial investment. Some technologies (thermal hydrolysis) add complexity. Not all sites suitable - depends on wastewater characteristics and plant size.',
    status: 'Proven concept with operating examples. Becoming best practice in progressive jurisdictions.',
    references: ['Danish water utilities (BIOFOS, Aarhus Vand)', 'Water Environment Research Foundation', 'IWA energy-positive WWTP case studies'],
    images: ['/Photos/Energy-Positive Wastewater Treatment/Picture61.jpg'],
  },
  {
    id: 26,
    name: 'UV Systems',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Chlorine disinfection creates harmful disinfection byproducts (DBPs). Need for chemical-free disinfection especially for water reuse.',
    technology: 'Ultraviolet light disinfection using UV lamps (typically 254 nm wavelength) to inactivate microorganisms by damaging their DNA/RNA.',
    novelty: 'No chemical addition or residual. No DBPs formation. Effective against chlorine-resistant pathogens like Cryptosporidium. Compact footprint.',
    details: 'UV-C radiation penetrates microbial cells and damages genetic material, preventing reproduction. Achieves 3-4 log inactivation of bacteria, 2-4 log viruses, 2-3 log protozoa. UV dose typically 30-100 mJ/cm² depending on target organism and water quality. Modern systems use efficient LED or amalgam lamps with automated cleaning, intensity monitoring, and dose control. No contact time required - treatment is instantaneous. Can be combined with H2O2 for UV/AOP destroying micropollutants.',
    fieldApplication: 'Standard disinfection technology at thousands of WWTPs globally. Mandatory for water reuse applications in many jurisdictions. Used in drinking water, wastewater, aquaculture, food processing. Denmark has extensive UV installations.',
    limitations: 'Requires clear water - suspended solids and turbidity reduce effectiveness. No residual disinfection in distribution system. Fouling of quartz sleeves requires cleaning. Energy consumption. Does not remove dissolved contaminants (only disinfects).',
    status: 'Mature proven technology. Industry standard for tertiary disinfection.',
    references: ['Xylem/Wedeco', 'Trojan Technologies', 'Danish UV equipment manufacturers', 'US EPA UV Disinfection Guidance'],
    images: ['/Photos/UV System/Picture62.png', '/Photos/UV System/Picture63.jpg'],
  },
  {
    id: 27,
    name: 'Rotary Drum Filter',
    country: 'France',
    category: 'stp-improvement',
    currentGap: 'Primary treatment screens miss fine solids. Need for better solid-liquid separation before biological treatment or membrane systems.',
    technology: 'Rotating cylindrical screen with fine mesh (10-100 microns) for continuous removal of fine suspended solids from wastewater.',
    novelty: 'Continuous self-cleaning operation. Compact design with high hydraulic capacity. Low pressure drop.',
    details: 'Drum rotates partially submerged in wastewater flow. Water flows from inside to outside through screen cloth. Solids accumulate on inside surface. As drum rotates, captured solids are lifted above water level, dewatered by gravity, and backwashed off by spray nozzles into collection trough. Removes TSS, fibers, particles before biological treatment or membranes. Reduces organic load to secondary treatment, improves clarifier performance, protects membranes from fouling. Applications: primary treatment enhancement, membrane pre-filtration, industrial process water.',
    fieldApplication: 'Widely used in European WWTPs. Standard equipment in aquaculture industry. Applied in paper mills, food processing, textile industries. Thousands of installations globally.',
    limitations: 'Screen blinding with oily or sticky solids. Regular maintenance of spray nozzles and bearings. Pre-screening of large objects required. Not effective for dissolved contaminants.',
    status: 'Mature commercial technology.',
    references: ['BOKELA (Germany)', 'Hydrotech (Veolia)', 'ANDRITZ', 'French water treatment equipment manufacturers'],
    images: ['/Photos/Rotary drum/Picture65.jpg', '/Photos/Rotary drum/Picture64.png'],
  },
  // Smart Monitoring
  {
    id: 28,
    name: 'Remote Sensing & Earth Observation',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Limited spatial coverage of ground-based water quality monitoring. Difficult to monitor large or inaccessible water bodies.',
    technology: 'Satellite and aerial imagery analysis using multispectral and hyperspectral sensors to monitor water quality parameters over large areas.',
    novelty: 'Synoptic view of entire water bodies. Historical data analysis for trend detection. Can monitor parameters like turbidity, chlorophyll, algae blooms, temperature.',
    details: 'Satellites (Sentinel-2, Landsat, Planet) capture images in visible and infrared bands. Water-leaving radiance correlates with water quality parameters. Algorithms derive: suspended sediment concentration, chlorophyll-a (algae indicator), turbidity, colored dissolved organic matter (CDOM), water temperature, surface features (oil spills, algae blooms). Temporal resolution: daily to weekly depending on satellite. Spatial resolution: 10-30m for medium satellites, <5m for commercial high-res. Can integrate with hydrological models for predictive analysis. Particularly useful for: lake monitoring, coastal water quality, river basin management, compliance monitoring.',
    fieldApplication: 'Operational in Denmark and EU for water framework directive monitoring. Used globally for lake/reservoir management, HAB early warning, coastal monitoring. Applications in India for Ganga monitoring and reservoir surveillance.',
    limitations: 'Cloud cover limits optical observation. Algorithms need calibration with in-situ data. Limited penetration depth in turbid water. Cannot measure all parameters (no nutrients, pathogens). Temporal resolution lower than in-situ sensors.',
    status: 'Operational technology with growing adoption as satellite data becomes freely available.',
    references: ['DHI GRAS (Denmark)', 'European Space Agency', 'Copernicus program', 'NASA', 'Planet Labs'],
    images: ['/Photos/Rotary drum/Picture64.png', '/Photos/Rotary drum/Picture65.jpg'],
  },
  {
    id: 29,
    name: 'Multi Parameter Water Quality Monitoring',
    country: 'England',
    category: 'smart-monitoring',
    currentGap: 'Traditional monitoring requires multiple sensors and complex installation. Lab analysis has delayed results. Need for real-time comprehensive data.',
    technology: 'Integrated multi-sensor probes measuring multiple water quality parameters simultaneously with single instrument.',
    novelty: 'One sonde measures 10+ parameters. Real-time data with telemetry. Reduced deployment and maintenance compared to multiple sensors.',
    details: 'Multi-parameter sondes include sensors for: physical parameters (temperature, pressure, depth, conductivity, turbidity, TSS), chemical parameters (pH, ORP, DO, specific ions with ISE), biological indicators (chlorophyll-a, phycocyanin, CDOM, FDOM), nutrient proxies. Data logging and telemetry transmit to cloud platforms. Used for continuous monitoring at fixed stations or profiling. Applications: drinking water reservoirs, wastewater effluent monitoring, river/stream monitoring, stormwater outfalls, industrial discharge compliance.',
    fieldApplication: 'Deployed globally at water utilities, environmental agencies, research stations. Thousands of units in operation. Leading UK manufacturers supply worldwide.',
    limitations: 'Sensor drift requires regular calibration. Biofouling in natural waters. Cost increases with number of parameters. Some parameters (like BOD, COD) cannot be measured directly - only proxies. Maintenance requirements in harsh environments.',
    status: 'Mature commercial technology. Industry standard for water quality monitoring networks.',
    references: ['YSI/Xylem (USA/UK)', 'Hach (UK)', 'Aquatic Informatics', 'In-Situ Inc.'],
    images: ['/Photos/Multi parameter Water Quality/Picture68.jpg', '/Photos/Multi parameter Water Quality/Picture69.jpg'],
  },
  {
    id: 30,
    name: 'AI-Driven Cloud Optimization for WWTPs',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'WWTP operations rely on operator experience and simple rule-based control. Not optimized for energy efficiency or treatment performance.',
    technology: 'Cloud-based artificial intelligence and machine learning platforms that optimize WWTP operations in real-time using plant data.',
    novelty: 'Learns from historical data to predict and optimize. Adapts to site-specific conditions. Reduces energy consumption 10-30% while improving effluent quality.',
    details: 'SCADA data uploaded to cloud platform. AI models trained on plant historical data learn relationships between influent conditions, operational parameters, and effluent quality. System predicts incoming load and optimizes: aeration intensity, chemical dosing, flow distribution, equipment scheduling. Predictive maintenance alerts for equipment failure. Enables proactive rather than reactive control. Danish systems integrate weather forecasts, rainfall data for feed-forward control. Provides operator decision support and autonomous optimization.',
    fieldApplication: 'Deployed at progressive WWTPs in Denmark, Netherlands, UK, USA. Growing adoption globally. Successful implementations show 15-25% energy savings with improved compliance.',
    limitations: 'Requires extensive historical data for training. Data quality critical - garbage in, garbage out. Some operators hesitant to trust AI control. Cybersecurity concerns with cloud connectivity. Subscription costs for cloud services.',
    status: 'Rapidly growing technology. Transition from pilot to mainstream adoption.',
    references: ['DHI (Denmark)', 'Envirosuite', 'SUEZ AQUADVANCED', 'Xylem Applied Water Systems', 'Nereda (Royal HaskoningDHV)'],
    images: ['/Photos/AI-Driven Cloud/Picture70.jpg', '/Photos/AI-Driven Cloud/Picture71.jpg'],
  },
  {
    id: 31,
    name: 'Energy-Efficient Smart Control Systems',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Aeration consumes 50-70% of WWTP energy. Fixed speed equipment and manual control waste energy.',
    technology: 'Advanced process control using real-time sensors, variable frequency drives (VFDs), and control algorithms to minimize energy consumption.',
    novelty: 'Dynamic control based on actual process needs rather than fixed settings. Integrates DO control, ammonia sensors, ORP, flowmeters for precise aeration.',
    details: 'System components: online sensors (DO, NH4, NOx, ORP), PLCs with advanced control algorithms (PID, fuzzy logic, model predictive control), VFDs for blowers and pumps, SCADA for monitoring. Controls optimize: dissolved oxygen setpoints (reduce to minimum safe level), aeration intensity matching load, pump speeds to required flows, equipment staging for efficiency. Ammonia-based aeration control (ABAC) adjusts DO based on actual nitrification needs. ORP-based control for denitrification. Predictive algorithms anticipate diurnal loading patterns. Results: 15-40% energy reduction, more stable effluent quality, reduced equipment wear.',
    fieldApplication: 'Standard practice at modern WWTPs in Denmark and progressive utilities worldwide. Retrofits common at existing plants. Thousands of installations.',
    limitations: 'Requires reliable sensors and maintenance. Control algorithm tuning needs expertise. Initial investment in VFDs and sensors. Not all plants suitable if equipment incompatible.',
    status: 'Proven technology. Best practice for energy efficiency.',
    references: ['Danish water sector', 'Grundfos (Denmark)', 'Siemens', 'Rockwell Automation', 'WEF energy management guidelines'],
    images: ['/Photos/Energy-Efficient Smart/Picture72.png'],
  },
  {
    id: 32,
    name: 'IoT Monitoring for Real-Time Water Network',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Water distribution networks lack visibility. Leaks and water quality issues go undetected. Manual meter reading is costly.',
    technology: 'Internet of Things (IoT) network of connected sensors, smart meters, and devices throughout water infrastructure providing real-time monitoring.',
    novelty: 'Continuous monitoring at numerous points. Early detection of leaks, contamination, pressure issues. Enables predictive maintenance and smart operations.',
    details: 'IoT sensors deployed at: water sources, treatment plants, pump stations, distribution mains, customer meters. Measurements include: flow, pressure, water quality, energy consumption, equipment status. Wireless communication (LoRaWAN, NB-IoT, cellular) transmits data to cloud platform. Analytics provide: leak detection through flow/pressure analysis, water quality event detection, asset health monitoring, customer usage patterns. Enables: automated billing, demand forecasting, pressure management, network optimization. Digital twin integration for predictive modeling.',
    fieldApplication: 'Extensive deployment in Denmark achieving 5-10% leakage rates (among world\'s best). Growing implementation in smart cities worldwide. Pilot projects in many countries.',
    limitations: 'High number of sensors needed for coverage. Battery life and replacement for wireless sensors. Communication network costs and reliability. Data management and cybersecurity challenges. High initial investment.',
    status: 'Active area of innovation and deployment. Accelerating adoption.',
    references: ['Grundfos (Denmark)', 'Kamstrup (Denmark)', 'Siemens', 'Sensus/Xylem', 'Danish smart water grids'],
    images: ['/Photos/IoT Monitoring for Real-Time Water Network-/Picture73.jpg'],
  },
  {
    id: 33,
    name: 'N₂O Sensors',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Nitrous oxide (N2O) is potent greenhouse gas (300x CO2) emitted from WWTPs but typically not measured. Largest source of WWTP carbon footprint.',
    technology: 'Real-time sensors measuring dissolved and gaseous N2O concentrations in biological treatment processes.',
    novelty: 'Enables measurement and mitigation of major GHG from WWTPs. Provides feedback for process optimization to reduce N2O emissions.',
    details: 'N2O produced during incomplete nitrification/denitrification. Measurement technologies: laser-based sensors (TDLAS), electrochemical sensors, mass spectrometry. Deployed in aeration tanks and off-gas. Real-time data reveals N2O hotspots and production conditions. Process optimization to reduce N2O: control DO levels (avoid <0.5 and >2 mg/L oscillations), optimize nitrite buildup, improve denitrification, carbon source management. Can reduce N2O emissions 30-70% through informed operation. Important for carbon footprint reduction and climate goals.',
    fieldApplication: 'Research and demonstration at Danish WWTPs and universities. Growing deployment at progressive utilities in Europe and North America. Becoming standard in GHG inventory programs.',
    limitations: 'Sensor cost relatively high. Calibration and maintenance requirements. Limited commercial suppliers. Not yet regulatory requirement in most places. Interpretation requires process expertise.',
    status: 'Emerging operational technology transitioning from research.',
    references: ['DTU Environment (Denmark)', 'Unisense (Denmark)', 'Scientific literature on N2O from WWTPs', 'GWRC research'],
    images: ['/Photos/N2O Sensors- Unisense; Denmark/Picture74.png'],
  },
  {
    id: 34,
    name: 'SulfiLogger H₂S Sensor',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Hydrogen sulfide causes odors, corrosion, and health hazards in sewers but difficult to monitor continuously. Creates liability and infrastructure damage.',
    technology: 'Real-time electrochemical sensor for measuring dissolved sulfide (H2S) in wastewater and sewer systems.',
    novelty: 'Online continuous H2S monitoring in harsh sewer conditions. Early warning for odor events and corrosion risk. Enables optimized chemical dosing.',
    details: 'Electrochemical sensor measures dissolved sulfide concentrations (0.01-10 mg/L typical range). Deployed in sewers, pump stations, wet wells. Data logged and transmitted via telemetry. Applications: odor complaint investigation, chemical dosing optimization (oxygen, nitrate, iron salts), corrosion risk assessment, industrial discharge monitoring. Helps utilities: prevent odor complaints, extend asset life (reduce concrete corrosion), optimize chemical costs, meet discharge regulations. Can integrate with automated dosing systems for feedback control.',
    fieldApplication: 'Deployed by progressive utilities in Denmark and globally. Particularly important in warm climates where sulfide generation high. Used for pumping stations and force mains.',
    limitations: 'Sensor fouling in sewers requires regular cleaning. H2S variability makes grab sampling inadequate - continuous monitoring essential. Initial cost and ongoing calibration. Telemetry and power requirements.',
    status: 'Established commercial technology with expanding adoption.',
    references: ['Unisense (Denmark)', 'OdaLog', 'Scientific literature on sewer sulfide control'],
    images: ['/Photos/H2S Sensor- SulfiLogger; Denmark/Picture76.jpg', '/Photos/H2S Sensor- SulfiLogger; Denmark/Picture75.png'],
  },
  {
    id: 35,
    name: 'Ultrasonic Sludge Level Sensor',
    country: 'China',
    category: 'smart-monitoring',
    currentGap: 'Sludge levels in clarifiers and thickeners not reliably monitored. Overflows occur due to lack of visibility. Manual inspection inefficient.',
    technology: 'Non-contact ultrasonic sensors mounted above tanks to measure sludge blanket level by detecting ultrasound reflection from sludge interface.',
    novelty: 'Continuous automated monitoring without contact with process. Prevents clarifier overflows and optimizes sludge withdrawal.',
    details: 'Sensor emits ultrasonic pulse downward. Pulse reflects from water surface and sludge blanket interface. Time-of-flight calculation determines levels. Modern sensors can detect multiple interfaces (water surface, sludge blanket, blanket depth). Applications: secondary clarifiers, primary sedimentation, thickeners, DAF units. Benefits: optimize sludge withdrawal timing and rate, prevent solids carryover to effluent, alarm for abnormal conditions, reduce operator rounds. Can integrate with SCADA for automated control.',
    fieldApplication: 'Standard equipment at modern WWTPs globally. Particularly common in Chinese manufactured treatment plants. Thousands of installations.',
    limitations: 'Foam or heavy rain can interfere with measurement. Limited range (typically <15m). Requires mounting structure and power. Calibration needed for sludge types. Some dense sludges may not reflect well.',
    status: 'Mature commercial technology.',
    references: ['Chinese sensor manufacturers', 'Endress+Hauser', 'Siemens', 'ABB'],
    images: ['/Photos/Ultrasonic Sludge Level/Picture78.jpg', '/Photos/Ultrasonic Sludge Level/Picture77.png'],
  },
  {
    id: 36,
    name: 'Sludge Concentration Sensor',
    country: 'China',
    category: 'smart-monitoring',
    currentGap: 'MLSS and sludge concentration typically measured by lab analysis with delayed results. Continuous monitoring needed for process control.',
    technology: 'Online sensors measuring suspended solids concentration in activated sludge and sludge streams using optical or acoustic principles.',
    novelty: 'Real-time MLSS measurement for improved process control. Optimizes RAS flow, WAS withdrawal, aeration.',
    details: 'Technologies: optical turbidity/nephelometry (measures light scattering), ultrasonic attenuation (sound absorption by particles), capacitance (dielectric properties). Measurement range typically 0-20 g/L for activated sludge. Installation locations: aeration tanks (MLSS), RAS line, WAS line, thickener overflow. Applications: maintain optimal MLSS concentration, control RAS/WAS pumping, balance sludge age, improve clarifier operation. Can reduce lab sampling by 80% and enable automated control.',
    fieldApplication: 'Widely deployed at municipal and industrial WWTPs. Chinese manufacturers produce affordable sensors increasing adoption. Common in Asia, growing in other regions.',
    limitations: 'Calibration with grab samples required. Fouling of optical sensors needs cleaning. Sensor drift over time. Air bubbles and fiber content can interfere. Not all sludge types have linear correlation.',
    status: 'Established technology with improving reliability and affordability.',
    references: ['Hach (Solitax)', 'Endress+Hauser (Turbimax)', 'Chinese manufacturers', 'Yokogawa'],
    images: ['/Photos/Sludge Concentration Sensor- Tengine; China/Picture79.jpg', '/Photos/Sludge Concentration Sensor- Tengine; China/Picture80.png'],
  },
  // Sludge/Solid Waste Treatment
  {
    id: 37,
    name: 'Reed Beds',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Mechanical sludge dewatering requires high energy and polymer consumption. Need for low-cost, low-energy sludge management for small plants.',
    technology: 'Sludge drying beds planted with reeds (Phragmites) that dewater and mineralize sludge through natural drainage and evapotranspiration.',
    novelty: 'Passive sludge dewatering and stabilization with minimal energy or chemicals. Reed roots create drainage channels improving performance.',
    details: 'Sludge applied to surface of reed bed (sand/gravel substrate). Water drains through bed and is collected. Reeds transpire water accelerating drying. Over time (1-5 years), sludge accumulates and mineralizes. Reed roots penetrate sludge creating macropores for improved drainage. Achieves 20-40% solids content. Final material resembles soil and can be used as soil amendment. Very low operating cost. Suitable for small plants (<5,000 PE). Land area required: 0.5-2 m²/PE depending on climate. Developed in Denmark and widely used in Scandinavia.',
    fieldApplication: 'Thousands of installations across Denmark and Northern Europe. Used in small municipalities and rural areas. Proven 30+ year operational history.',
    limitations: 'Large land area required. Long retention time (1-5 years). Performance affected by climate (reduced in cold/wet). Not suitable for large plants. Periodic harvesting required. May attract pests.',
    status: 'Mature technology for niche applications.',
    references: ['Danish EPA', 'Sludge Treatment Reed Beds Association', 'Scientific literature from Aarhus University'],
    images: ['/Photos/Reed Beds- Aarhusvand; Denmark/Picture82.jpg', '/Photos/Reed Beds- Aarhusvand; Denmark/Picture81.png'],
  },
  {
    id: 38,
    name: 'High Temperature and Pressure with Catalyst Technology',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Conventional sludge treatment takes long time and produces difficult-to-dewater material. Need for rapid organic destruction.',
    technology: 'Thermal hydrolysis or catalytic wet oxidation treating sludge at high temperature (150-260°C) and pressure with catalyst to break down complex organics.',
    novelty: 'Rapid organic breakdown improving digestibility and dewaterability. Increases biogas production 15-50% in downstream anaerobic digestion.',
    details: 'Sludge heated to high temperature under pressure in presence of catalyst (or just temperature/pressure for thermal hydrolysis). Breaks down cell walls, proteins, polysaccharides. Processes: Thermal Hydrolysis (Cambi - 165°C, 6 bar), Catalytic Wet Oxidation (Zimpro - 200-260°C with air/oxygen). Results: sterilized sludge (pathogens destroyed), improved dewaterability, increased biogas in AD, reduced viscosity. Enables higher solids digestion. Valuable for large plants producing significant biogas. Can reduce final sludge volume 50%.',
    fieldApplication: 'Cambi thermal hydrolysis has 80+ installations globally including large plants in Denmark, UK, USA, China. Used for enhanced biogas production and improved sludge quality.',
    limitations: 'High capital and operational costs. Energy intensive (though offset by increased biogas). Complex operation requiring skilled staff. Economical mainly for large plants (>100,000 PE). Odor management needed.',
    status: 'Proven commercial technology for large-scale applications.',
    references: ['Cambi (Norway)', 'Veolia (former US Filter/Zimpro)', 'Scientific literature on THP'],
    images: ['/Photos/High Temperature & Pressure with catalyst technology-Suez; Denmark/Picture83.jpg', '/Photos/High Temperature & Pressure with catalyst technology-Suez; Denmark/Picture84.png'],
  },
  {
    id: 39,
    name: 'Steam-Drying and Pyrolysis Technology',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Disposal of dewatered sludge is costly. Land application regulations tightening. Need for volume reduction and energy recovery.',
    technology: 'Two-stage thermal process: steam drying converts wet sludge to dry granules (90% solids), followed by pyrolysis at 400-600°C converting to biochar, oil, and gas.',
    novelty: 'Complete sludge destruction with energy and material recovery. Biochar product has value as soil amendment or fuel. Self-sustaining process.',
    details: 'Steam dryer uses indirect heating (no air contact) to dry sludge to 90%+ solids as pellets/granules. Pyrolysis in oxygen-free environment thermally decomposes organics. Products: biochar (carbon-rich solid for soil, adsorption, fuel), pyrolysis oil (liquid fuel), syngas (combusted for process heat). Technology often energy self-sufficient as pyrolysis products fuel the dryer. Achieves 90% mass reduction. Destroys pathogens, pharmaceuticals, microplastics. Biochar sequesters carbon. Heavy metals concentrated in biochar for controlled management.',
    fieldApplication: 'Several commercial installations in Denmark for municipal sludge. Growing adoption in Europe and Asia. Particularly attractive where landfill expensive and regulations strict.',
    limitations: 'Very high capital cost. Complex operation. Requires minimum scale (typically >20,000 PE). Off-gas treatment needed. Biochar market development still evolving. Not economic for small plants.',
    status: 'Commercial technology for progressive large plants. Growing sector.',
    references: ['TCCR (Denmark)', 'Pyreg (Germany)', 'EnergyTech (Denmark)', 'Scientific literature on sludge pyrolysis'],
    images: ['/Photos/Steam-drying and pyrolysis technology/Picture85.png'],
  },
  {
    id: 40,
    name: 'Cyclones Sludge Settler',
    country: 'France',
    category: 'sludge-treatment',
    currentGap: 'Primary clarifiers have large footprint. Need for compact high-rate settling for pretreatment or primary treatment.',
    technology: 'Hydrocyclones using centrifugal force to rapidly separate settleable solids from wastewater in compact units.',
    novelty: 'High-rate settling in small footprint. No moving parts. Can achieve clarification in seconds vs hours for conventional settling.',
    details: 'Wastewater enters tangentially into cylindrical-conical vessel. Rotation creates vortex with centrifugal acceleration 50-200x gravity. Solids migrate to wall and exit from bottom as underflow (concentrated sludge). Clarified water exits from top center as overflow. Residence time: 5-30 seconds. Can remove >50% TSS. Used for primary treatment, side-stream thickening, or pretreatment. Compact size attractive for space-constrained sites. Can be modular for capacity increase.',
    fieldApplication: 'Applied in European industrial WWTPs. Used in pulp & paper, food processing, mining. Some municipal applications. Several hundred installations.',
    limitations: 'Does not remove dissolved or colloidal matter. Requires pressure head or pumping. Wear from abrasive solids. May not meet primary treatment regulations alone. Energy consumption higher than gravity settling per m³.',
    status: 'Established niche technology for specific applications.',
    references: ['Krebs (France)', 'Weir Minerals', 'Scientific literature on hydrocyclones'],
    images: ['/Photos/Cyclones Sludge Settler- Suez; Denmark/Picture86.png', '/Photos/Cyclones Sludge Settler- Suez; Denmark/Picture87.png'],
  },
  {
    id: 41,
    name: 'Smart Waste Management Solution',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Inefficient solid waste collection with fixed schedules. Overflowing bins or unnecessary collections. Lack of data on waste streams.',
    technology: 'IoT-enabled smart bins with fill-level sensors, optimized collection routing software, and data analytics for waste management optimization.',
    novelty: 'Dynamic waste collection based on actual fill levels. Optimizes routes reducing fuel consumption 20-40%. Provides waste generation analytics.',
    details: 'Smart bins equipped with ultrasonic or optical fill-level sensors and wireless connectivity (LoRaWAN, NB-IoT, cellular). Data transmitted to cloud platform. System provides: real-time fill level monitoring, alerts for collection needs, optimized collection routes, waste generation analytics, contamination detection. Benefits: reduce collection costs, prevent overflows, reduce emissions from collection vehicles, improve service levels. Can integrate with underground vacuum waste systems. Provides data for circular economy initiatives.',
    fieldApplication: 'Deployed in many Danish cities and municipalities. Growing adoption in smart cities worldwide. Thousands of bins in operation. Applied to residential, commercial, and public waste bins.',
    limitations: 'Initial investment in sensors and bins. Battery replacement/maintenance for sensors. Connectivity challenges in some areas. Cultural adoption challenges in some communities. ROI depends on collection costs.',
    status: 'Growing commercial market. Maturing technology.',
    references: ['Danish waste management companies', 'Enevo', 'Bigbelly', 'Nordsense', 'Sensoneo'],
    images: ['/Photos/Smart Waste Management Solution- Nordsense; Denmark/Picture89.jpg', '/Photos/Smart Waste Management Solution- Nordsense; Denmark/Picture88.png'],
  },
  {
    id: 42,
    name: 'Ecogi System',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Need for decentralized composting of organic waste. Food waste in landfills creates methane emissions.',
    technology: 'Automated composting systems for institutional and community-scale organic waste treatment using controlled aerobic decomposition.',
    novelty: 'Accelerated composting (2-4 weeks) through optimized temperature, moisture, and aeration control. Minimal odor with proper operation.',
    details: 'Insulated vessel with automated mixing, aeration, and temperature control. Organic waste (food, garden, paper) loaded regularly. System maintains optimal composting conditions: 50-65°C temperature, 50-60% moisture, regular turning for aeration. Microbes decompose organics rapidly. Volume reduction 70-80%. Output is stabilized compost for soil amendment. Capacity ranges from 50 kg/day (institutional) to several tons/day (community). Some systems integrated with educational centers. Modular scalable design.',
    fieldApplication: 'Deployed at schools, hospitals, apartment complexes, communities in Denmark and internationally. Hundreds of installations. Popular in institutions with sustainability goals.',
    limitations: 'Requires proper feedstock balance (carbon/nitrogen ratio). Some maintenance and monitoring needed. Odor management critical. Not suitable for all waste types (meat, dairy limited). Capital cost may be barrier for small installations.',
    status: 'Commercial technology with established market.',
    references: ['Danish organic waste management sector', 'Various Scandinavian manufacturers'],
    images: ['/Photos/Ecogi System- Ecogi; Denmark/Picture90.png', '/Photos/Ecogi System- Ecogi; Denmark/Picture91.png'],
  },
  {
    id: 43,
    name: 'Solid Waste Recycling',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Low recycling rates and poor sorting quality. Contamination reduces material recovery value.',
    technology: 'Advanced material recovery facilities with automated sorting using optical sensors, AI, and robotics to maximize recycling and material quality.',
    novelty: 'High-speed automated sorting achieving >95% recovery of recyclables. AI-powered recognition systems adapt to new materials and contamination patterns.',
    details: 'Modern MRFs employ: optical sorters (NIR, visual, x-ray) identifying material types, AI-powered robotic sorters picking specific items, eddy current separators for metals, air classifiers for light materials, ballistic separators for dimensional sorting. Process flow: pre-sorting, size classification, material separation by type (paper, cardboard, plastics by polymer, metals, glass by color). Produces clean material streams meeting recycler specifications. Denmark achieves >50% recycling rate. System can process 20-50 tons/hour. Integration with source separation programs.',
    fieldApplication: 'State-of-art facilities in Denmark and progressive European municipalities. Growing adoption globally as regulations mandate recycling. Facility investments $20-100M depending on capacity.',
    limitations: 'High capital investment. Requires source separation cooperation from residents. Some materials difficult to recycle economically. Market fluctuations affect material values. Residual waste still requires disposal.',
    status: 'Mature and continuously improving technology. Best practice.',
    references: ['Danish waste sector', 'TOMRA Sorting', 'European Environment Agency', 'Waste management industry publications'],
    images: ['/Photos/Solid waste Recycling/Picture92.jpg', '/Photos/Solid waste Recycling/Picture93.jpg'],
  },
  {
    id: 44,
    name: 'Azortum Solid Waste Sorting',
    country: 'Estonia; Finland',
    category: 'sludge-treatment',
    currentGap: 'Manual sorting is labor-intensive, slow, and has poor recovery rates. Need for automated high-throughput sorting.',
    technology: 'Advanced automated waste sorting system using AI-powered computer vision and robotics for high-speed, accurate material separation.',
    novelty: 'Deep learning algorithms continuously learn and improve recognition. Can identify thousands of object types. Sorting accuracy >95% at high speed.',
    details: 'Conveyor system moves waste stream past vision stations. High-resolution cameras capture images from multiple angles. AI algorithms (trained neural networks) identify material type, contamination, value. Robotic arms or air jets separate materials. System learns from corrections and adapts to local waste composition. Can sort: various plastic types, paper/cardboard grades, metals, textiles, specific valuable items. Processing speed 60-80 picks/minute per robot. Modular design allows capacity scaling. Integrates with existing MRF infrastructure.',
    fieldApplication: 'Installations in Baltic countries and Scandinavia. Growing installations across Europe. Used in municipal MRFs and commercial recycling facilities. Pilots in other regions.',
    limitations: 'High initial investment in vision systems and robotics. Requires conveyor system modification. Performance affected by highly contaminated or wet waste. Maintenance of robots and cameras. ROI depends on material values and labor costs.',
    status: 'Commercial technology with expanding market.',
    references: ['ZenRobotics (Finland)', 'Bollegraaf (Netherlands)', 'Machinex (Canada)', 'AMP Robotics (USA)'],
    images: ['/Photos/Azortum solid waste sorting/Picture1.png', '/Photos/Azortum solid waste sorting/Picture2.png'],
  },
  {
    id: 45,
    name: 'WAGABOX® Technology - Upgrade Landfill Gas into RNG',
    country: 'U.S.A',
    category: 'sludge-treatment',
    currentGap: 'Landfill gas (LFG) is often flared or used for low-value electricity generation. Opportunity for higher-value renewable natural gas.',
    technology: 'Membrane separation system specifically designed to upgrade landfill gas to pipeline-quality renewable natural gas (RNG/biomethane) for injection to grid or vehicle fuel.',
    novelty: 'Compact membrane technology optimized for landfill gas composition. Lower capital and operating cost than cryogenic or amine upgrading. Mobile/containerized units available.',
    details: 'Landfill gas (typically 50-55% methane, 40-45% CO2, traces of H2S, siloxanes, VOCs) is collected from landfill. Pre-treatment removes moisture, particulates, siloxanes, H2S. WAGABOX membrane system separates CO2 and other impurants from methane. Multi-stage membrane process achieves >97% methane purity meeting pipeline specifications. Output is RNG suitable for natural gas grid injection or compressed natural gas (CNG) vehicle fuel. Modular units 50-500 scfm capacity. Can process gas from old closed landfills. Monetizes waste methane as renewable fuel.',
    fieldApplication: 'Multiple installations at US landfills producing pipeline-quality RNG. Growing market driven by renewable fuel standards and carbon credits. Technology deployed internationally.',
    limitations: 'Requires minimum landfill gas production (typically >300 scfm). Gas composition variability affects performance. RNG markets not developed everywhere. Pipeline injection requires utility agreements. Siloxane removal critical for equipment protection.',
    status: 'Proven commercial technology. Market growing rapidly with renewable energy incentives.',
    references: ['Waga Energy (France/USA)', 'Greenlane Renewables', 'Guild Associates', 'US EPA LMOP program'],
    images: ['/Photos/WAGABOX® technology/Picture3.jpg', '/Photos/WAGABOX® technology/Picture4.png'],
  },
];