export interface Technology {
  id: number;
  name: string;
  country: string;
  category: 'decentralized' | 'stp-improvement' | 'smart-monitoring' | 'sludge-treatment';
  currentGap?: string;
  technology?: string;
  novelty?: string;
  details?: string;
  fieldApplication?: string;
  limitations?: string;
  status?: string;
  references?: [{
    [key: string]: string;
  }];
  images?: string[];
  institution?: string;
  authors?: string[];
}

export const categories = {
  decentralized: 'Decentralized Units & NBS',
  'stp-improvement': 'STP Improvement',
  'smart-monitoring': 'Smart Monitoring',
  'sludge-treatment': 'Sludge/Solid Waste Treatment',
};

export const technologies: Technology[] = [
  {
    id: 1,
    name: 'Floating Wetland',
    country: 'Denmark, USA',
    category: 'decentralized',
    currentGap: 'In India, natural based treatment solutions like wetlands are underutilized and often poorly maintained.',
    technology: 'Growing plants over floating platforms helps in absorbing and degrading pollutants from water bodies.',
    novelty: 'Selected plants and biofilm have been checked for showing its effectiveness in removing the specific pollutants.',
    details: 'Remove dissolved nutrients and heavy metals from water bodies. FW size is scalable and has modular design. Plants and the plant-microbe interactions in the lower surface of the floating island absorb and remove contaminants from the water while supporting other natural processes such as denitrification and sedimentation. Heavy metals (Cd, Cr(VI), Pb, Co, Cu, Pb, Ni, Se, Zn) and Nutrients (e.g. nitrate, ammonium, phosphate) removal from water body has been removed.',
    fieldApplication: 'Has been applied successfully in Denmark.',
    limitations: 'Requires regular monitoring and maintenance. To remove carbon from water bodies, microbial culturing needs to be done.',
    status: 'Communication is under progress.',
    references: [{ "Eco Island": "https://www.ecoisland.dk/services/", "Floating Island International Inc": "https://www.floatingislandinternational.com/contact.html" }],
    images: ['/Photos/Floating Wetlands-/Picture1.jpg', '/Photos/Floating Wetlands-/Picture2.png'],
  },
  {
    id: 2,
    name: 'Photosynthesis Based Wastewater Treatment Using Gir Cow Urine,',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Conventional wetland treatment requires longer treatment time with less efficiency.',
    technology: 'Wastewater passed through wetland plants mixed with Gir cow urine gives high efficiency for pollutant degradation.',
    novelty: 'Gir cow urine has been tested along with wetland plants and found to have high catalytic properties for the degradation of domestic wastewater.',
    details: 'Leverage the nutrients in urine to support microbial and algal growth, aiding in purification. Gir Cow Urine’s nutrients-rich composition enhances microbial activity. Microalgae and purple phototrophic bacteria can play a role in purifying wastewater by absorbing nutrients and break down organic matter. Photosynthetic microorganism utilize its nutrients to enhance purification efficiency.',
    fieldApplication: 'Lab testing has been conducted with successful results.',
    limitations: 'Takes longer treatment time compared to conventional wastewater technologies.',
    status: 'Initial presentation conducted. Second phase meeting is in progress.',
    references: [{ "Pinakin Technology Solutions Pvt Ltd": "https://pinakin.co.in/" }],
    images: ['/Photos/Photosynthesis Based/Picture3.jpg', '/Photos/Photosynthesis Based/Picture5.png'],
  },
  {
    id: 3,
    name: 'Soil Biotechnology (SBT)',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Treating wastewater using nature based solutions with less cost than STP is a big challenge.',
    technology: 'Soil biotechnology (SBT) is a terrestrial system for wastewater treatment based on the principle of the trickling filter.',
    novelty: 'Has potential to be used in place of STP, ETP, ZLD for industries and rivers and lake rejuvenation.',
    details: 'SBT systems are constructed from RCC, stonemasonry or soil bunds. They comprise a raw-water tank, bioreactor containment, treated water tank, piping and pumps. Suitable mineral constitution, bacterial culture and bio-indicator plants are the components of the system. Water passes through the artificial wetland vertically from top to down. Removal processes involves adsorption & filtration on media and biological degradation.',
    fieldApplication: 'SBT plant has been developed in IIT Bombay and has been implemented successfully in Bengaluru and Mumbai.',
    limitations: 'SBT type wastewater treatment plants require high land area of around 2.5 m²/m³ of wastewater treatment.',
    status: 'Communication is under progress.',
    references: [{ 'visionearthcare': "https://www.visionearthcare.com/technology/sbt" }],
    images: ['/Photos/Soil biotechnology (SBT)/Picture6.jpg', '/Photos/Soil biotechnology (SBT)/Picture7.png', '/Photos/Soil biotechnology (SBT)/Picture8.jpg'],
  },
  {
    id: 4,
    name: 'Phytorid',
    country: 'India',
    category: 'decentralized',
    currentGap: 'In India, natural wetland treatment systems occupy a lot of area.',
    technology: 'Treats the water using natural wetland technology.',
    novelty: 'Produces better output in less area requirement compared with conventional wetland systems.',
    details: 'Constructed wetland capable of treatment of municipal, urban, agricultural and industrial wastewater. The system consists of the 3 zones - Inlet zone of crushed bricks and different sizes of stones; Treatment zone consisting of the same media as in inlet zone with plant species; outlet zone. The total area required for the system is approximately 35 m² for 20 m³/day of wastewater.',
    fieldApplication: 'Has been successfully implemented in various places such as in Mumbai and Buldhana.',
    limitations: 'Initial cost and time taken for complete cleaning of water body is high.',
    status: 'Communication is in progress.',
    references: [{ 'NEERI Nagpur': "https://www.neeri.res.in/contents/banner_details/phytorid-wastewater-treatment-technology/5b193f6eaacd7googtrans(en%7Cen)" }],
    images: ['/Photos/Phytorid/Picture9.png', '/Photos/Phytorid/Picture10.png'],
  },
  {
    id: 5,
    name: 'Freeze Technology',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Conventional technologies for industrial wastewater like evaporators require high energy, crystallizers are costly, and RO has high reject.',
    technology: 'Freezing the wastewater at the water freezing temperature causes easy separation of pollutant and pure ice.',
    novelty: 'Suitable for high strength wastewater and economical compared to conventional RO and evaporation method.',
    details: 'Recovery of salts from wastewater like NaCl, Na2SO4, CaCl2, CaCO3 with efficiency up to 90-95% can be achieved. Suitable for recovery of clean water from various high strength industrial effluents like Dyes, Textile, Agrochemical, Insecticides & Pharmaceutical units. Recovery of expensive minerals from waste discharge of Mining Industry is possible. Desalination (making sea water drinkable).',
    fieldApplication: 'Successfully implemented and got results for mining industry in India.',
    limitations: 'Less efficient for domestic sewage having less organics (BOD < 500 mg/L).',
    status: 'Initial presentation conducted by company. Second phase meeting is in progress.',
    references: [{ "Pinakin Technologies Company": "https://pinakin.co.in/" }],
    images: ['/Photos/Freeze Technology/Picture11.png', '/Photos/Freeze Technology/Picture12.png'],
  },
  {
    id: 6,
    name: 'Nano-Bubble Generators',
    country: 'USA',
    category: 'decentralized',
    currentGap: 'Conventional aerators produce very less oxygen and have low oxygen dissolution capability.',
    technology: 'The generators produce very fine air bubbles in nanometer size.',
    novelty: 'Nanobubble generators deliver >85% oxygen transfer efficiency in the water body.',
    details: 'It is scalable, retrofittable, and can be easily used for any kind of water body. The system works with gases like oxygen, ozone, and CO₂, and supports a wide range of system capacities. No chemical usage and the oxygen helps in degrading organics which improves water quality.',
    fieldApplication: 'Used in agriculture to boost plant growth, aquaculture to improve fish health, and wastewater to enhance water quality.',
    limitations: 'High initial investment needed.',
    status: 'Initial response received. Presentation was scheduled; no response.',
    references: [{ "http://www.moleaer.com/": "http://www.moleaer.com/" }],
    images: ['/Photos/Nano-Bubble Generators/Picture13.jpg', '/Photos/Nano-Bubble Generators/Picture14.jpg'],
  },
  {
    id: 7,
    name: 'Watopi',
    country: 'Denmark',
    category: 'decentralized',
    currentGap: 'Many rural and peri-urban areas in India lack scalable, affordable, and easily manageable decentralized wastewater treatment infrastructure.',
    technology: 'Modular, prefabricated plug-and-play decentralized wastewater treatment units (e.g., MBRs, SBRs), incorporated with smart monitoring systems.',
    novelty: 'Scalable, low operation & management, minimal land and energy needs, solar-enabled and ideal for small communities where centralized systems are not feasible.',
    details: 'Can treat sewage generated from 5 to 1000 persons. Suitable for schools, apartments, townships and promotes local water reuse.',
    fieldApplication: 'Similar decentralized solutions deployed across 50+ countries including India by various providers.',
    limitations: 'Requires regular service visits for consistent long-term functionality.',
    status: 'Communication is under process.',
    references: [{ "http://www.biokube.dk/": "http://www.biokube.dk/" }],
    images: ['/Photos/Watopi- BioKube, Denmark/Picture15.png', '/Photos/Watopi- BioKube, Denmark/Picture16.jpg', '/Photos/Watopi- BioKube, Denmark/Picture17.jpg'],
  },
  {
    id: 8,
    name: 'Microbial Fuel Cell',
    country: 'USA',
    category: 'decentralized',
    currentGap: 'High strength aerobic wastewater degradation requires a lot of energy consumption.',
    technology: 'Produces electricity by degrading pollutants.',
    novelty: 'Patented technology (BETT®, USA) - Can produce electricity while degrading pollutants.',
    details: 'Can treat very highly polluted wastewater. The process requires only added oxygen from outside and converts organic pollutants into electricity and water.',
    fieldApplication: 'Pilot-based study on USA swine wastewater showed maximum 93% COD removal.',
    limitations: 'Not very effective for less polluted wastewater such as domestic sewage (BOD < 500 mg/L).',
    status: 'Initial response received. Presentation was scheduled; no response.',
    references: [{ "Aquacycl company, USA": "https://aquacycl.com/services/carbon-removal/", "Hsu et al., 2017": "https://aquacycl.com/wp-content/uploads/2024/07/2017_ECS-Trans.-2017-Hsu-19-29.pdf", "https://www.youtube.com/watch?v=IxsG8G0YTEE": "https://www.youtube.com/watch?v=IxsG8G0YTEE" }],
    images: ['/Photos/Microbial Fuel Cell- Aquacyl; USA/Picture18.png', '/Photos/Microbial Fuel Cell- Aquacyl; USA/Picture19.jpg'],
  },
  {
    id: 9,
    name: 'Water Mantra',
    country: 'Singapore',
    category: 'decentralized',
    currentGap: 'RO technology produces a high amount of reject water while giving clean water.',
    technology: 'The water to be treated has to be fed through the pipe and the hand pump pressure produces clean water through the membranes.',
    novelty: 'Membrane has been modified. Better alternative to RO as the ultrafiltration membrane produces very less reject. No electricity requirement, simple in operation, and can be used anywhere.',
    details: 'Ultrafiltration membranes and nanofiltration are used. Water wasting is very low compared to RO. In RO, rejected water is almost 70%, but for WaterMantra water purifier pump, reject is only 2–3%. TDS is maintained at healthier levels compared to RO (which reduces TDS to 20–30 ppm). Ideal for drinking water systems where mineral retention is essential.',
    fieldApplication: 'On-field application performed at Hindon Canal, Ghaziabad, Uttar Pradesh.',
    limitations: 'Maximum treatment capacity is 150 L/Hr.',
    status: 'Response of SLCR email is awaited.',
    references: [{ "http://h2omantra.com/": "http://h2omantra.com/", "https://www.youtube.com/watch?v=fAXTCBhkWGc": "https://www.youtube.com/watch?v=fAXTCBhkWGc", "https://youtu.be/RTfi1cFEzT8?si=LZjQMbP2_6L10v_6": "https://youtu.be/RTfi1cFEzT8?si=LZjQMbP2_6L10v_6" }],
    images: ['/Photos/Water Mantra-h2Omantra; Singapore/Picture20.png', '/Photos/Water Mantra-h2Omantra; Singapore/Picture21.png', '/Photos/Water Mantra-h2Omantra; Singapore/Picture22.png'],
  },
  {
    id: 9.1,
    name: 'Water Mantra',
    country: 'Singapore',
    category: 'decentralized',
    currentGap: 'RO technology produces a high amount of reject water while giving clean water.',
    technology: 'The membranes convert contaminated water into clean water through the membranes with very less space requirement.',
    novelty: 'Can easily convert contaminated water into purified water without need of electricity.',
    details: ' Ideal for commercial establishments, rural community where availability of electricity is limited. Can be used at emergency & disaste rrelief, military troops, schools, hospitals.',
    fieldApplication: ' Onfield application performed at Ramnagar, Bhopal, MadhyaPradesh.',
    limitations: 'Maximum treatment capacity is 50L/Hr.',
    status: 'Mail has been sent. At present waiting for their reply.',
    references: [{ "http://h2omantra.com/": "http://h2omantra.com/", "https://www.youtube.com/watch?v=W5cNmFTn5Rw": "https://www.youtube.com/watch?v=W5cNmFTn5Rw" }],
    images: ['/Photos/Water Mantra-h2Omantra; Singapore/Picture20.png', '/Photos/Water Mantra-h2Omantra; Singapore/Picture21.png', '/Photos/Water Mantra-h2Omantra; Singapore/Picture22.png'],
  },
  {
    id: 10,
    name: 'Electro Oxidation Technology',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Conventional electrodes have corrosion problems and lower efficiency.',
    technology: 'Applying external current through electrodes causes oxidants formation in water, leading to pollutant degradation.',
    novelty: 'Novel electrode gives higher operational life (15–20 years) compared to conventional electrodes (0.5–3 years).',
    details: 'Wastewater is treated by applying electric current through electrodes in a reactor. Applicable for removal of organic pollutants (high strength and low strength) from wastewater. Does not need auxiliary chemicals, high pressure, or temperature. Titanium-coated electrodes provide higher life compared to conventional electrodes. Domestic sewage operation cost is very low.',
    fieldApplication: 'Applied at some places in India.',
    limitations: 'Initial installation cost is very high.',
    status: 'Initial presentation conducted by Pinkain Technology, India. Second phase meeting is in progress.',
    references: [{ "Pinakin Technology Solutions Pvt Ltd": "https://pinakin.co.in/", "Technology- HPNow": "https://hpnow.com/technology/" }],
    images: ['/Photos/Electro Oxidation Technology; Pinakin/Picture23.jpg', '/Photos/Electro Oxidation Technology; Pinakin/Picture24.png', '/Photos/Electro Oxidation Technology; Pinakin/Picture25.png'],
  },
  {
    id: 11,
    name: 'Onsite Oxidation',
    country: 'Denmark',
    category: 'decentralized',
    currentGap: 'Persistent compounds do not undergo oxidation by conventional processes.',
    technology: 'Generation of radicals using external power supply and electrodes causing pollutant degradation.',
    novelty: 'Onsite generation of Hydrogen Peroxide (H₂O₂) using water, air, and electricity causing in situ water treatment.',
    details: 'Produces ultra-pure H₂O₂ and other radicals which cause oxidation of contaminants and disinfection. Environmentally friendly, with no chemical waste or byproduct buildup. Highly scalable design with cells arranged in stacks and systems supporting multiple stacks.',
    fieldApplication: 'Demonstrated at Evonik, Germany – integration with Xylem’s UV reactor for real-time contaminant removal.',
    limitations: 'Initial investment cost may be high for small facilities. The process is electricity-dependent and not ideal for areas with unreliable power.',
    status: 'No initial response received.',
    references: [{ "https://hpnow.com/technology/": "https://hpnow.com/technology/", "https://hpnow.com/introducing-hpgen-i-series/": "https://hpnow.com/introducing-hpgen-i-series/", "https://smartwatermagazine.com/news/hpnow/green-peroxide-generation-enables-safe-and-chemical-free-aop": "https://smartwatermagazine.com/news/hpnow/green-peroxide-generation-enables-safe-and-chemical-free-aop" }],
    images: ['/Photos/Onsite Oxidation- hpnow; Denmark/Picture26.jpg', '/Photos/Onsite Oxidation- hpnow; Denmark/Picture27.jpg'],
  },
  {
    id: 12,
    name: 'Pulse Plasma',
    country: 'Germany',
    category: 'decentralized',
    currentGap: 'Conventional advanced oxidation processes take longer treatment time with lesser efficiency.',
    technology: 'Plasma, the fourth state of matter, rapidly generates radicals inside water which causes pollutant degradation.',
    novelty: 'High-voltage nanosecond and picosecond pulse generators produce precise, high-speed pulses suitable for advanced plasma applications.',
    details: 'The pulse generators are designed for versatility, accommodating various applications requiring rapid, high-voltage pulses. They are customizable to meet specific client requirements, ensuring optimal integration into existing systems.',
    fieldApplication: 'Has been implemented successfully in various pilot plant studies with good removal efficiency such as IIT Madras sewage treatment plant.',
    limitations: 'High-voltage operations require high safety protocols, trained personnel, and treatment cost. The process generates nitrate release into water after treatment.',
    status: 'No initial response received.',
    references: [{ "https://fidtech.com/high-voltage-pulse-generators/": "https://fidtech.com/high-voltage-pulse-generators/" }],
    images: ['/Photos/Pulse Plasma- Fidtech; Germany/Picture28.png', '/Photos/Pulse Plasma- Fidtech; Germany/Picture29.png', '/Photos/Pulse Plasma- Fidtech; Germany/Picture30.jpg'],
  },
  {
    id: 13,
    name: 'Mechanical Vapor Recompression (MVR) Technology',
    country: 'Denmark',
    category: 'decentralized',
    currentGap: 'Indian industries face challenges in treating complex wastewater and achieving Zero Liquid Discharge (ZLD) or Minimal Liquid Discharge (MLD).',
    technology: 'Patented Mechanical Vapor Recompression (MVR) technology for industrial wastewater treatment.',
    novelty: 'Efficiently separates wastewater into high-purity distillate (95–99% reuse) with minimum concentrate, with low energy consumption and automated operation.',
    details: 'Treats harsh industrial effluents (e.g., from automotive, food & beverage) to enable significant water reuse and minimize hazardous waste.',
    fieldApplication: 'Successfully implemented across various industrial sectors globally.',
    limitations: 'Primarily for industrial wastewater; requires careful pre-treatment for heavily polluted wastewater.',
    status: 'Communication is under progress.',
    references: [{ "Envotherm": "http://www.envotherm.dk/" }],
    images: ['/Photos/MVR Technology- Envotherm; Denmark/Picture31.png', '/Photos/MVR Technology- Envotherm; Denmark/Picture32.png'],
  },
  {
    id: 14,
    name: 'Geotubes',
    country: 'India , Australia',
    category: 'decentralized',
    currentGap: 'In India, natural filtration is not much explored.',
    technology: 'Treats the water using a natural filtration system with improved filtration tubes.',
    novelty: 'Sludge dewatering separates the solid and liquid components of the sludge/slurry, causing effective elimination of liquids before disposal.',
    details: 'Sludge or wastewater is pumped into the geotube container. Environmentally safe polymers are added to the sludge, which makes the solids bind together and separate water from it. Clear effluent water simply drains from the geotube container. Over 99% of solids are captured, and clear filtrate can be collected and recirculated through the system. Solids remain in the container and the content can be deposited at landfill or land-applied.',
    fieldApplication: 'Has been successfully implemented in various places in India such as during Kumbh, Prayagraj.',
    limitations: 'Utilization of chemical polymer for binding the solids is a concern for discharging. The filter pores are not suitable for long run.',
    status: 'Communication is in progress.',
    references: [{ "Ocean Global": "https://oceangeosynthetics.com/geotubes-the-effective-solution-for-dewatering-sludge/", "Solamax": "https://www.solmax.com/me/en/blog/how-to-achieve-sustainable-dewatering-with-geotube", "https://www.geofabrics.co/sites/default/files/2024-07/GEOTUBE_Dewatering_Technology_APAC_0923_Web.pdf": "https://www.geofabrics.co/sites/default/files/2024-07/GEOTUBE_Dewatering_Technology_APAC_0923_Web.pdf" }],
    images: ['/Photos/Geotubes/Picture33.jpg', '/Photos/Geotubes/Picture34.png'],
  },
  {
    id: 15,
    name: 'Poseidon Pellets – Phosphorous removal',
    country: 'USA',
    category: 'decentralized',
    currentGap: 'Removal of nutrients by adsorption from ponds and lakes is difficult.',
    technology: 'Can remove phosphorus by using pellets.',
    novelty: 'The pellets can be reused again and also as fertilizer.',
    details: 'Can bind phosphorus in water as well as in sediment. Helps in controlling algal blooms in water bodies. Pellets can be reused as a soil amendment. In wastewater treatment, they can be used as pre or post treatment. Does not pose any risk to freshwater biota or human health.',
    fieldApplication: 'Laguna Niguel Lake, USA had total initial phosphorus of ~270 µg/L which achieved >80% removal. Serpentine Lake, UK had initial phosphorus of ~0.3 mg/L which was reduced to 0.05 mg/L.',
    limitations: 'Treatment cost is comparatively higher than conventional biological processes. Only applicable for phosphorus and not for other nutrients or pollutants.',
    status: 'No initial response received.',
    references: [{ "https://www.waterwarriorsinc.com/": "https://www.waterwarriorsinc.com/", "https://petwatersolutions.com/products/water-treatment-phoslock/": "https://petwatersolutions.com/products/water-treatment-phoslock/", "https://www.youtube.com/watch?v=8XlDY84WIP8": "https://www.youtube.com/watch?v=8XlDY84WIP8" }],
    images: ['/Photos/Poseidon Pellets/Picture35.jpg', '/Photos/Poseidon Pellets/Picture36.jpg', '/Photos/Poseidon Pellets/Picture37.jpg'],
  },
  {
    id: 16,
    name: 'Coagulation - Flocculation',
    country: 'China',
    category: 'decentralized',
    currentGap: 'Conventional coagulants produce lesser dense flocs with longer treatment time.',
    technology: 'Coagulants addition produces flocs with wastewater pollutants followed by their removal.',
    novelty: ' Very high floc formation & pollutant removal for any type of wastewater.',
    details: 'Excellent coagulants which forms flocs with any type of wastewater. Flocs formed are dense and has high settling properties. Requires very less treatment time compared with conventional coagulants like alum.',
    fieldApplication: 'Used extensively for municipal WWTP and Industrial wastewater.',
    limitations: 'Coagulants once used can’t be reused again. Coagulants may pose issue after the test',
    status: 'Negative response received.',
    references: [{ "Henan SECCO Company, China": "https://www.hnsecco.com/", "https://www.youtube.com/watch?v=H2-G9dMw4Lw": "https://www.youtube.com/watch?v=H2-G9dMw4Lw" }],
    images: ['/Photos/Coagulation/Picture38.png', '/Photos/Coagulation/Picture39.png'],
  },
  // STP Improvement
  {
    id: 17,
    name: 'Membrane Bioreactor (MBR)',
    country: 'France & USA',
    category: 'stp-improvement',
    currentGap: 'Conventional technologies such as ASP and SBR require high land, tanks requirement and less solids separation (% ).',
    technology: 'Utilizes membranes inbiological tank causing less area requirement and moreefficient solids removal.',
    novelty: ' Provides advanced solids-liquid separation and eliminates the need for secondary clarifiers and can meet the stringent STP norms.  Can also be used as a modular standalone system. Causes less land area requirement (~40% less) and more efficient solids removal (less than 2 mg/l). It is sustainable; lasting for around 15-20 years and economical in long run',
    details: 'Membrane Bioreactor (MBR) combines biological treatment with membrane filtration. Suitable for municipal sewage, industrial effluents and recycled water systems. Operates at higher MLSS, causing reduced footprint and enhancing treatment capacity.',
    fieldApplication: 'Used by leading companies like Xylem and Veolia for high-quality wastewater treatment. Xylem’s Sanitaire MBR and Veolia’s Biosep™ are established globally.',
    limitations: 'High initial capital costs due to membrane purchase and installation.',
    status: ' Veolia company made their presentation & Xylem company didn’t respond.',
    references: [{ "https://www.veoliawatertech.com/en/products/biosep-neosep": "https://www.veoliawatertech.com/en/products/biosep-neosep", "https://www.xylem.com/en-us/brands/sanitaire/about-sanitaire/": "https://www.xylem.com/en-us/brands/sanitaire/about-sanitaire/" }],
    images: ['/Photos/Membrane Bioreactor/Picture40.png', '/Photos/Membrane Bioreactor/Picture41.jpg'],
  },
  {
    id: 18,
    name: 'MBBR – Moving Bed Biofilm Reactor',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Conventional ASP or SBR has suspended technology which gives comparatively lesser  efficiency.High-strength wastewater treatment requires large footprint and complex sludge management systems',
    technology: 'Combined suspended and attached growth technology. Utilizes media on which microbes grow and degrades pollutants.',
    novelty: 'Advanced biological treatment using biofilm carriers in an aeration tank. High surface-area novel plastic media enhances biofilm growth efficiency.Handles variable loading conditions. Can provide phosphate removal of order of 95 %.',
    details: 'Treats highly contaminated wastewater effectively using free-floating plastic carriers with high surface area which promotes biofilm growth.• Requires minimal space and is compatible with existing treatment systems.• Meteor™ by SUEZ – a patented MBBR system used globally for complex industrial wastewater.',
    fieldApplication: 'World’s largest Produced Water treatment plant using MBBR in Fredericia, Denmark. Successfully demonstrated in Banning, CA, USA pilot with aerobic-aerobic-anoxic- aerobic configuration.',
    limitations: 'Some insects, like sewage flies, mosquitoes and red worms, will be attracted to the biofilm and causing decrease in effectiveness of the system. • Manual monitoring is required to ensure the bacteria on the carriers is still alive.',
    status: 'Initial response is awaited.',
    references: [{ "https://www.suez.com/en/denmark/references/danish-oil-pipe": "https://www.suez.com/en/denmark/references/danish-oil-pipe", "https://bio-blok.com/applications/wastewater-treatment-municipality": "https://bio-blok.com/applications/wastewater-treatment-municipality" }],
    images: ['/Photos/Membrane Bioreactor/Picture40.png', '/Photos/Membrane Bioreactor/Picture41.jpg'],
  },
  {
    id: 19,
    name: 'IFAS Technology',
    country: 'Canada',
    category: 'stp-improvement',
    currentGap: 'The existing STP biological treatment units (mostly ASP’s and SBR) have low efficiency.',
    technology: 'Membranes or modules are installed inside the existing STP’s biological units. Microbes get themselves attach on these modules and degrade the organics in wastewater.',
    novelty: 'Hybrid system combining suspended and attached growth for enhanced treatment',
    details: 'Biofilm carriers support attached microbial growth which increases the treatment efficiency. Improves nutrient removal and increases treatment capacity.Useful for Indian plants needing capacity upgrades without large footprint expansion. Improves nitrogen and phosphorus removal efficiency',
    fieldApplication: 'Applied successfully in Copenhagen, Denmark and other EU plants — 5-15 MLD scale.',
    limitations: 'Requires monitoring of biofilm thickness and carrier integrity. Operational complexity higher than conventional activated sludge.',
    status: 'Meeting held; follow up is being done by sending water quality data',
    references: [{ "https://www.ovivowater.com/en/product/clearfas/": "https://www.ovivowater.com/en/product/clearfas/" }],
    images: ['/Photos/Integrated Fixed-film Activated Sludge/Picture46.png', '/Photos/Integrated Fixed-film Activated Sludge/Picture47.emf'],
  },
  {
    id: 20,
    name: 'Membranes',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'General membranes causes high power requirement.',
    technology: 'Aquaporin is a protein which is selective in nature and causes efficient water pass through it under less applied pressure.',
    novelty: 'Aquaporin® membranes add natural aquaporin proteins, causing cellular water channels for selective and efficient water filtration. • This biomimetic approach offers enhanced water permeability and selectivity compared to conventional membranes under less feed pressure. Thus, it helps in power saving (~20 %)',
    details: 'Available in flat sheet and hollow fiber configurations, suitable for forward osmosis (FO) and reverse osmosis (RO) applications. Operates effectively at ambient temperatures, reducing energy requirements and treatment cost. Membranes offer high contaminant rejection and upto 40% higher permeability, enhancing residential water purification systems.',
    fieldApplication: 'Applied in wastewater treatment, food and beverage concentration, and pharmaceutical industries for efficient water separation.',
    limitations: 'Membrane performance can be affected by fouling; requires proper pre-treatment and maintenance.',
    status: 'Meeting held on on 6th June and further follow -up is under way..',
    references: [{ "https://aquaporin.com/products/": "https://aquaporin.com/products/" }],
    images: ['/Photos/Membranes; Aquaporin/Picture48.png', '/Photos/Membranes; Aquaporin/Picture49.png', '/Photos/Membranes; Aquaporin/Picture50.png'],
  },
  {
    id: 21,
    name: 'Ceramic Membrane Filtration',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Indian industries and municipal plants need robust, durable filtration solutions for challenging wastewater streams and to achieve high water reuse.',
    technology: 'Unique, patented Silicon Carbide (SiC) ceramic membrane technology for liquid filtration.',
    novelty: 'Extremely durable (chemically/thermally inert), high flux, low power usage, and long lifespan compared to polymeric membranes, enabling reliable treatment of difficult waters.',
    details: 'Filters can tolerate harsh wastewater from industries and municipal effluent. Suitable for zero or minimum liquid discharge (ZLD/MLD) applications. Achieves high-purity water for reuse.',
    fieldApplication: 'Widely used in various industrial liquid filtration processes and municipal wastewater applications globally.',
    limitations: 'Higher initial capital cost than some conventional filtration methods.',
    status: 'Communication is under process',
    references: [{ "Liq Tech International": "http://www.liqtech.com/" }],

    images: ['/Photos/Ceramic Membrane Filtration/Picture51.png'],
  },
  {
    id: 22,
    name: 'Revolving Algal Biofilm System',
    country: 'USA',
    category: 'stp-improvement',
    currentGap: 'Conventional ASP having suspended process has lesser efficiency.',
    technology: 'Rotating biofilm reactor where algae grow on slowly revolving vertical surfaces alternately exposed to wastewater and air/sunlight.',
    novelty: 'Patented technology (RAB™, USA)- Algae is grown on moving belts surface.',
    details: 'Algae or Bacteria grows on the revolving belt inside wastewater.• Algae consumes nitrogen and phosphorous from the wastewater.Nutrient- rich algae produced which can be made into pellets & used for other purpose. Nutrient- rich algae can be used as fertilizer use or in replacing plastics to some extent. Bacteria can also be cultured on belts for the removal of organics (BOD).  Reduces carbon footprints. Can be used as a tertiary treatment',
    fieldApplication: 'Applied successfully in Canadian municipality with obtained effluent (P< 0.05, NH3< 1 and BOD5< 10 mg/L) reaching standard.',
    limitations: 'The moving belt requires extra energy consumption & maintenance.',
    status: 'Initial response is awaited.',
    references: [{ "Technology | Gross-Wen Technologies": "https://algae.com/technology", "https://algae.com/wp-content/uploads/2024/04/5-Municiapal-Pilot_Case-Study.pdf": "https://algae.com/wp-content/uploads/2024/04/5-Municiapal-Pilot_Case-Study.pdf" }],
    images: ['/Photos/Revolving Algal Biofilm System/Picture52.png', '/Photos/Revolving Algal Biofilm System/Picture53.png', '/Photos/Revolving Algal Biofilm System/Picture54.png'],
  },
  {
    id: 23,
    name: 'Nicotinamide Adenine Dinucleotide (NADH) Probes',
    country: 'U.S.A',
    category: 'stp-improvement',
    currentGap: 'Nitrogen and carbon removal in single STP tank is not happening. It requires making different tanks for Carbon and nitrogen removal.',
    technology: 'NADH process probes can be used to check appropriate aeration to maintain simultaneous nitrification and denitrification conditions.',
    novelty: 'Under controlled aeration conditions, simultaneous carbon and nitrogen removal is possible.',
    details: 'Nicotinamide adenine dinucleotide (NAD) is an intermediate compound in biological reactions that functions to transport electrons from a reduced substrate (i.e., chemical oxygen demand) to the biosynthetic pathways. • In its reduced form, it exists as NADH or NADPH. When light at 340 nm strikes NADH, it fluoresces and emits light at 460 nm. • NADH probes measure the concentration of NADH by emitting 340 nm and detecting 460 nm light. It can then help in carbon removal in aerobic zone and nitrogen in anoxic zone.',
    fieldApplication: 'More than 40 municipal applications are in the United States.',
    limitations: 'Requires very skilled manpower and continuous monitoring to operate.',
    status: 'Communication is under progress.',
    references: [{ "Sci-Hub": "https://sci-hub.st/10.2175/193864700784545036", "https://www.epa.gov/sites/default/files/2019-02/documents/emerging-tech-wastewater-treatment-management.pdf": "https://www.epa.gov/sites/default/files/2019-02/documents/emerging-tech-wastewater-treatment-management.pdf" }],
    images: ['/Photos/Nicotinamide Adenine Dinucleotide/Picture55.png', '/Photos/Nicotinamide Adenine Dinucleotide/Picture56.png'],
  },
  {
    id: 24,
    name: 'Supercritical Water Oxidation',
    country: 'USA',
    category: 'stp-improvement',
    currentGap: 'Persistent/complex compounds are not removed from STP’s secondary biological treatment.',
    technology: 'Treating wastewater under temperature and pressure at water critical condition completely destroy toxic organics into CO₂ and water.',
    novelty: 'Utilises critical water condition to degrade pollutants causing pollutant complete destruction, including challenging substances like PFAS, without generating secondary waste streams.',
    details: 'When wastewater is heated above 374 oC temperature and 221 bar pressurize, then it reaches supercritical condition. • Heat and pressure during the process produces oxidants which is used to treat waste water constituents. • Can degrade even persistent pollutants such as PFAS. • Requires small installation area.',
    fieldApplication: 'Worked in collaboration with “OC San wastewater treatment company” and other US company for the treatment of emerging contaminants',
    limitations: 'Requires lot of energy, specialized equipment and safety measures during its operation.',
    status: 'No initial response came through mail.',
    references: [{ "https://aquarden.com/superox-scwo/": "https://aquarden.com/superox-scwo/", "https://374water.com/technology/": "https://374water.com/technology/", "Supercritical Water Oxidation Project": "https://www.ocsan.gov/construction-project/supercritical-water-oxidation-project/" }],
    images: ['/Photos/Supercritical Water Oxidation/Picture57.png', '/Photos/Supercritical Water Oxidation/Picture58.jpg', '/Photos/Supercritical Water Oxidation/Picture59.png', '/Photos/Supercritical Water Oxidation/Picture60.png'],
  },
  {
    id: 25,
    name: 'Energy-Positive Wastewater Treatment',
    country: '',
    category: 'stp-improvement',
    currentGap: 'Indian municipal utilities need to upgrade wastewater treatment to meet stricter discharge norms and also achieve energy neutrality and recover resources.',
    technology: 'Operates as a showcase for advanced wastewater treatment, energy optimization (self-sufficient/positive), and resource recovery (e.g., sludge to energy).',
    novelty: 'Demonstrates how large WWTPs can become energy-positive bio-refineries through smart operation, asset management, and low NRW practices.',
    details: 'Focuses on optimizing water distribution, reducing Non-Revenue Water, and achieving high-quality effluent; applicable for large urban utilities.',
    fieldApplication: 'Ejby Mølle is a fully operational, highly optimized plant in Denmark, serving as a benchmark for water management.',
    limitations: 'Represents a state-of-the-art facility; full replication requires significant investment and skilled operation.',
    status: 'Received initial response. Requested for presentation; response is awaited.',
    references: [{ "VCSDenmark": "http://www.vcs.dk/", "Aarhus Vand": "http://www.aarhusvand.com/" }],
    images: ['/Photos/Energy-Positive Wastewater Treatment/Picture61.jpg'],
  },
  {
    id: 26,
    name: 'UV Systems',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Conventional UV lamps have less light penetration & gets affected by turbid solutions.',
    technology: 'UV Lamps having different configuration for waster treatment.',
    novelty: 'Has more energy compared to conventional UV lamps.',
    details: 'Produces UV light at 185 nm wavelength having more energy and penetration than conventional 254 nm lights. Has more water penetrating power than conventional ones. Able to remove total organic carbon also from water system. • Efficiency can be further increased by adding ozone or hydrogen peroxide.',
    fieldApplication: 'Has been applied in various countries like Canada, UK, USA.',
    limitations: 'Not suitable for highly turbid water.',
    status: 'Received initial response. Requested for presentation; response is awaited.',
    references: [{ "Ultra Aqua": "https://ultraaqua.com/product/ultratox-series/?_gl=1*110abdh*_up*MQ..*_ga*NjQyOTc0MjQuMTc0ODUxNDQ5Mw..*_ga_FM5MZLCMJ4*czE3NDg1MTQ0OTMkbzEkZzEkdDE3NDg1MTQ1MTckajM2JGwwJGgw" }],
    images: ['/Photos/UV System/Picture62.png', '/Photos/UV System/Picture63.jpg'],
  },
  {
    id: 27,
    name: 'Rotary Drum Filter',
    country: 'France',
    category: 'stp-improvement',
    currentGap: 'The solids content coming out of conventional treatment process is not completely removed.',
    technology: '10 or 20 mm filters the suspended solids to make the effluent solids less than 10 mg/L.',
    novelty: 'A mechanical filtration system that separates solids from water using a rotating drum and screen filter to almost completely removes suspended solids.',
    details: 'Continuously removes suspended solids from wastewater with minimal energy consumption. Ideal for tertiary treatment, aquaculture and pre-filtration before biological systems.',
    fieldApplication: 'Used in JC France’s projects for sewage filtration, food processing, and textile industry effluent treatment.',
    limitations: 'Not effective for dissolved pollutants – only removes particulate matter. Requires regular maintenance to prevent clogging and ensuring effective filtration.',
    status: 'Response is awaited',
    references: [{ "https://www.jcfranceindustrie.fr/en/rotary-drum-filter/": "https://www.jcfranceindustrie.fr/en/rotary-drum-filter/" }],
    images: ['/Photos/Rotary drum/Picture65.jpg', '/Photos/Rotary drum/Picture64.png'],
  },
  // Smart Monitoring
  {
    id: 28,
    name: 'Remote Sensing & Earth Observation',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'India needs the cost-effective, wide-area monitoring of water quality ,land use changes affecting water bodies, and environmental impact assessments.',
    technology: 'Processes satellite image and Earth Observation data using machine learning to provide actionable insights for environmental and water management.',
    novelty: 'Converts vast satellite data into practical information for water quality mapping, flood risk assessment, urban planning, and environmental monitoring.',
    details: 'Provides large-scale environmental intelligence for hydrologic modeling, water quality assessment (e.g., algae blooms), and infrastructure planning.',
    fieldApplication: 'Used in national and international projects globally, including collaborations with the European Space Agency.',
    limitations: 'Requires expertise in data interpretation; dependent on satellite data availability and resolution. • Usually measures chlorophyll and turbidity of water bodies. Difficult to analyze other major parameters like BOD, COD, etc.',
    status: 'Operational technology with growing adoption as satellite data becomes freely available.',
    references: [{ "DHI GRAS": "http://www.dhigras.com/" }],
    images: ['/Photos/Rotary drum/Picture64.png', '/Photos/Rotary drum/Picture65.jpg'],
  },
  {
    id: 29,
    name: 'Multi Parameter Water Quality Monitoring',
    country: 'England',
    category: 'smart-monitoring',
    currentGap: 'Analysis various water quality parameters in lab is a tedious job.',
    technology: 'Utilizes various probes at a time for measuring various water parameters with ease.',
    novelty: 'Can measure multiple water quality parameters.',
    details: 'Real-time water quality monitoring solutions.• Innovative sensor technology enables continuous, accurate measurement of key parameters (30 parameters) such as BOD, COD, TOC, and coliform bacteria, sodium, nitrate, calcium, chloride, bromide, ammonium, Turbidity, dissolved oxygen, pH, temperature, TDS, fluorescence, tryptophan, blue- green algae, coliforms, fluorescein dye, chlorophyll. • Requires minimal maintenance and no reagent is required.',
    fieldApplication: 'Has been installed in UK with over 250 outstations monitoring water quality,level and weather.• Has been installed in Denmark and Philippines coastal area.',
    limitations: '+5% error in the determined parameters values and initial cost is high.',
    status: 'Initial response received. In the process of scheduling presentation.',
    references: [{ "https://proteus-instruments.com/": "https://proteus-instruments.com/", "How the UK's largest real-time catchment monitoring network is leading the way": "https://proteus-instruments.com/2024/01/24/how-the-uks-largest-real-time-catchment-monitoring-network-is-leading-the-way/" }],
    images: ['/Photos/Multi parameter Water Quality/Picture68.jpg', '/Photos/Multi parameter Water Quality/Picture69.jpg'],
  },

  {
    id: 30,
    name: 'AI-Driven Cloud Optimization for WWTPs',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Indian wastewater treatment plants face challenges in optimizing energy consumption, reducing greenhouse gas emissions, and adapting to fluctuating influent loads due to reliance on manual control and static operating strategies.',
    technology: 'Cloud-based artificial intelligence and machine learning platform that connects with SCADA systems to monitor, predict, and optimize wastewater treatment plant operations in real time.',
    novelty: 'Leverages advanced AI algorithms and predictive analytics to dynamically adjust aeration, nutrient removal, and process control, reducing energy and GHG emissions by 15–30%. Integrates with existing systems for adaptive, data-driven optimization.',
    details: 'The platform collects operational and sensor data from SCADA and uploads it to a secure cloud environment. Machine learning models are trained on historical data to understand relationships between influent load, process conditions, and effluent quality. The system predicts incoming loads and optimizes process parameters such as aeration intensity, chemical dosing, and flow distribution. It supports predictive maintenance and integrates weather and rainfall data for feed-forward control. Applicable to large-scale municipal WWTPs, the system helps improve compliance, stability, and energy efficiency while reducing manual intervention.',
    fieldApplication: 'Successfully implemented at advanced WWTPs in Denmark, Italy, the Netherlands, the UK, and the USA. Demonstrated 15–25% energy and 10–20% GHG reduction with improved effluent stability. Applicable for Indian utilities seeking digital transformation in WWTP operations.',
    limitations: 'Requires reliable and comprehensive SCADA data integration. Data quality directly affects model accuracy. Initial setup, calibration, and operator training are required. Ongoing subscription costs and cybersecurity considerations apply.',
    status: 'Initial response received. Presentation requested; awaiting further communication.',
    references: [{ "DHI": "http://www.dhi.com/", "BIOFOS": "https://en.biofos.dk/" }],
    images: ['/Photos/AI-Driven Cloud/Picture70.jpg', '/Photos/AI-Driven Cloud/Picture71.jpg']
  },


  {
    id: 31,
    name: 'Energy-Efficient Smart Control Systems',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'High energy consumption constitutes a major operational cost for wastewater treatment and water supply systems in India. Conventional fixed-speed pumps, blowers, and manual operation cause inefficiency.',
    technology: 'Energy-efficient Variable Frequency Drives (VFDs) integrated with smart control algorithms and real-time sensor feedback to optimize pump, blower, and mixer operations across water and wastewater infrastructure, including ZLD/MLD systems.',
    novelty: 'Dynamic control based on actual process requirements instead of fixed-speed operation. Enables 25–50% energy savings through real-time optimization of aeration, pumping, and flow control. Supports predictive and adaptive process regulation for ZLD/MLD and WWTP applications.',
    details: 'The system combines online sensors (DO, NH4, NOx, ORP), PLCs with advanced algorithms (PID, fuzzy logic, model predictive control), and VFDs for variable-speed operation. SCADA systems enable centralized monitoring. Control logic optimizes dissolved oxygen setpoints, pump/blower speeds, and process staging for energy efficiency. Ammonia-based aeration control (ABAC) adjusts DO in response to nitrification demand, while ORP-based control supports denitrification. Suitable for municipal WWTPs, water pumping stations, and industrial water systems. Demonstrated 15–40% energy savings, improved effluent stability, and extended equipment life.',
    fieldApplication: 'Extensively implemented in Denmark and other advanced water utilities worldwide. Applicable across municipal and industrial sectors in India, including ZLD/MLD facilities. Proven energy-saving performance in thousands of installations.',
    limitations: 'Requires proper sensor maintenance, system tuning, and compatibility with existing motor or pump setups. Initial investment in VFDs and control infrastructure.',
    status: 'Proven and mature technology. Communication with solution providers underway for deployment.',
    references: [{ "Danfoss": "http://www.danfoss.com/en-in" }],
    images: ['/Photos/Energy-Efficient Smart/Picture72.png']
  },

  {
    id: 32,
    name: 'IoT Monitoring for Real-Time Water Network',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Remote or inaccessible areas in water distribution networks often lack real-time monitoring of critical parameters such as flow, pressure, and quality, especially in regions with limited power or connectivity. Manual inspection and delayed detection lead to water loss and inefficiency.',
    technology: 'Internet of Things (IoT) network of smart, self-powered sensors and connected devices across water infrastructure that monitor and transmit real-time data on flow, pressure, and water quality.',
    novelty: 'Integrates energy-harvesting micro-hydro systems to power IoT sensors, enabling continuous, battery-free operation. Provides predictive insights and early leak or contamination detection for proactive water network management.',
    details: 'IoT sensors are installed at water sources, treatment plants, pump stations, and distribution mains. They monitor parameters such as flow, pressure, turbidity, conductivity, temperature, and residual chlorine. Data is transmitted via LoRaWAN, NB-IoT, or cellular networks to a cloud-based platform. Analytics enable leak detection, quality anomaly detection, and asset condition monitoring. The energy-harvesting design allows deployment in remote areas by converting water flow into electricity to power sensors. Supports digital twins and integration with SCADA for predictive maintenance and smart water management.',
    fieldApplication: 'Piloted with utilities in Denmark and Europe for continuous water network monitoring. Achieved world-class leakage reduction rates (5–10%) and improved operational efficiency. Suitable for decentralized and rural networks.',
    limitations: 'Requires steady water flow for energy generation. Coverage depends on communication network availability. Initial setup and calibration can be resource-intensive.',
    status: 'Contact initiated with developers; technology under active piloting and demonstration.',
    references: [{ "Aqua Robur Technologies": "http://www.aquarobur.com/" }],
    images: ['/Photos/IoT Monitoring for Real-Time Water Network-/Picture73.jpg']
  },
  {
    id: 33,
    name: 'N₂O Sensors',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Nitrous oxide (N₂O), a potent greenhouse gas nearly 300 times stronger than CO₂, is emitted from wastewater treatment plants but typically goes unmeasured. Conventional nitrate analysis in laboratories is time-consuming and lacks real-time process feedback.',
    technology: 'Real-time sensor system measuring dissolved and gaseous N₂O concentrations in biological treatment processes, providing insights into nitrogen removal efficiency and greenhouse gas emissions.',
    novelty: 'Provides continuous, real-time measurement of nitrous oxide emissions, enabling both nitrogen process optimization and climate impact reduction. Links nitrogen transformation dynamics directly with operational parameters.',
    details: 'N₂O sensors measure emissions from nitrification and denitrification stages, offering insight into process inefficiencies and nitrate removal rates. Technologies include tunable diode laser absorption spectroscopy (TDLAS), electrochemical sensors, and gas-phase analyzers. The emission of 1 kg of N₂O equals approximately 300 kg of CO₂ in climate impact. Real-time data enables process optimization — adjusting dissolved oxygen (DO), nitrite accumulation, and carbon dosing to minimize emissions. Applicable for municipal and industrial wastewater treatment plants, research facilities, and greenhouse gas inventory monitoring.',
    fieldApplication: 'Successfully applied in Danish wastewater treatment plants and research projects by Unisense Environment and DTU Environment. Growing adoption across progressive utilities in Europe and North America.',
    limitations: 'Limited to nitrogen-based emission monitoring. High sensor cost and maintenance requirements. Data interpretation requires process expertise. Not yet a regulatory requirement in most regions.',
    status: 'Emerging operational technology transitioning from research to field-scale deployment.',
    references: [{ "https://youtu.be/zE3z5IGUP88?si=avdWB4JD6qUy8fg9": "https://youtu.be/zE3z5IGUP88?si=avdWB4JD6qUy8fg9", "Mission - Unisense Environment": "https://unisense-environment.com/mission/" }],
    images: ['/Photos/N2O Sensors- Unisense; Denmark/Picture74.png']
  },


  {
    id: 34,
    name: 'SulfiLogger H₂S Sensor',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Hydrogen sulfide (H₂S) in wastewater systems causes severe odor pollution, infrastructure corrosion, and health hazards for workers. Conventional grab sampling and gas detectors do not provide continuous or real-time data.',
    technology: 'Robust, continuous electrochemical sensor system for real-time H₂S monitoring directly in wastewater, air, or process gases. Data is transmitted to SCADA or cloud-based IoT platforms for proactive control.',
    novelty: 'Provides online, real-time dissolved or gaseous H₂S data even in harsh sewer and treatment environments. Enables predictive odor and corrosion management and optimizes chemical dosing through IoT connectivity.',
    details: 'Electrochemical H₂S sensor measures dissolved or gaseous hydrogen sulfide in concentrations typically from 0.01–10 mg/L (in liquid) or ppm levels (in gas). Designed for installation in sewers, pumping stations, wet wells, and treatment process lines. Data is logged and transmitted via telemetry to SCADA or cloud dashboards for continuous monitoring. Applications include odor and corrosion control, optimization of dosing (oxygen, nitrate, iron salts), safety management in confined spaces, and corrosion risk mapping. Used in wastewater, biogas, and oil & gas sectors. Helps utilities prevent odor complaints, extend asset lifespan, and reduce chemical costs.',
    fieldApplication: 'Widely deployed in Denmark and internationally in wastewater utilities, biogas plants, and industrial sites. Proven under harsh field conditions for long-term monitoring.',
    limitations: 'Sensor requires periodic cleaning and calibration due to fouling in sewers. Needs stable power and telemetry connections. Direct contact with sludge or debris may affect accuracy.',
    status: 'Commercial and widely adopted with proven global installations.',
    references: [{ "SulfiLogger": "http://www.sulfilogger.com/" }],
    images: ['/Photos/H2S Sensor- SulfiLogger; Denmark/Picture76.jpg', '/Photos/H2S Sensor- SulfiLogger; Denmark/Picture75.png']
  },


  {
    id: 35,
    name: 'Ultrasonic Sludge Level Sensor',
    country: 'China',
    category: 'smart-monitoring',
    currentGap: 'Determining the sludge depth or amount of water to be filtered from sedimentation tanks is difficult using manual inspection or conventional methods.',
    technology: 'Ultrasonic echo detection system that determines sludge depth and thickness based on reflection of ultrasonic waves from different density layers.',
    novelty: 'Capable of distinguishing multiple sludge layers and measuring their thickness with high accuracy. Enables real-time monitoring of sludge blanket and discharge levels.',
    details: 'The instrument emits ultrasonic waves toward the bottom of the tank and receives reflected signals of varying intensities from sludge layers of different densities. Using these reflections, it calculates sludge depth, layer thickness, and blanket interface position. It supports self-cleaning, automatic energy adjustment for various media, and wide measurement ranges up to 10 meters. Applications include sewage treatment plants (STP), water treatment plants (WTP), mining washing plants, and power plants. Data can support sludge discharge optimization and chemical dosing control. Designed for low maintenance and stable long-term operation.',
    fieldApplication: 'No specific field applications reported yet. Currently in early-stage evaluation and demonstration.',
    limitations: 'Measurement range limited to approximately 10 meters. Foam and turbulence can interfere with signal accuracy.',
    status: 'Initial response received; presentation scheduling in progress.',
    references: [{ "Tengine, China": "https://en.tengine.com.cn/products_details/63.html" }],
    images: ['/Photos/Ultrasonic Sludge Level/Picture78.jpg', '/Photos/Ultrasonic Sludge Level/Picture77.png']
  },


  {
    id: 36,
    name: 'Sludge Concentration Sensor',
    country: 'China',
    category: 'smart-monitoring',
    currentGap: 'Difficult to continuously determine sludge solids concentration and densification requirements using conventional lab-based tests with delayed results.',
    technology: 'Online digital sensor for real-time measurement of sludge and suspended solids concentration using multi-beam infrared light transmission and optical filtering technology.',
    novelty: 'Simplifies sludge concentration measurement compared to conventional lab methods. Provides continuous and accurate monitoring with automatic air cleaning for stable performance.',
    details: 'The sensor operates on the principle of multi-beam infrared light transmission combined with optical bandpass filtering and modulated excitation to eliminate ambient light interference. It includes an automatic air-cleaning system for reducing fouling and ensuring reliable long-term operation. Offers strong anti-interference capability and stability. Measurement range typically up to 25 g/L. Applications include wastewater treatment plants (WWTPs), paper mills, coal washing plants, and power industries. Enables real-time monitoring for improved process control and reduced manual sampling.',
    fieldApplication: 'No specific field application reports available yet. Currently under evaluation and demonstration.',
    limitations: 'Not suitable for higher concentrations of activated sludge (>25 g/L). Requires calibration for accuracy and periodic maintenance of optical components.',
    status: 'Initial response received; presentation scheduling in progress.',
    references: [{ "Tengine, China": "https://en.tengine.com.cn/products_details/87.html#c_relevant_052-1710324098964" }],
    images: ['/Photos/Sludge Concentration Sensor- Tengine; China/Picture79.jpg', '/Photos/Sludge Concentration Sensor- Tengine; China/Picture80.png']
  },

  // Sludge/Solid Waste Treatment
  {
    id: 37,
    name: 'Reed Beds',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Sludge treatment through natural processes requires large land area and may cause gas emission problems.',
    technology: 'Engineered wetlands planted with reeds (Phragmites australis) that dewater, stabilize, and mineralize sludge through natural drainage and microbial activity in the root zone.',
    novelty: 'Natural, low-energy method for sludge treatment using reed roots to enhance drainage and microbial degradation.',
    details: 'Sludge from primary or secondary treatment is applied in layers to reed beds built over sand or gravel substrate. Water percolates down and drains through a collection system, while organic matter decomposes over time via aerobic and anaerobic microbial processes in the root zone. After several years, the mineralized sludge is removed and used as a soil conditioner or disposed of safely. Typically achieves 20–40% solids content. Requires 0.5–2 m²/PE of land depending on climate. Low operational cost and minimal maintenance. Suitable for small wastewater treatment plants (<5,000 PE).',
    fieldApplication: 'Widely implemented across Denmark and Northern Europe in small municipalities and rural areas. Proven operation in Danish plants such as Aarhus Vand with more than 30 years of successful experience.',
    limitations: 'Longer treatment time compared to thermal or pyrolysis methods. Requires large land area and favorable climate. Potential groundwater contamination risk due to leaching. Periodic harvesting required. Not suitable for large plants.',
    status: 'Communication under progress.',
    references: [{ "Reed Beds": "https://vbn.aau.dk/ws/portalfiles/portal/424057861/Reed_bed_vegetation_structure_and_plant_species_diversity_depend_on_management_type_and_the_time_period_since_last_management.pdf" }],
    images: ['/Photos/Reed Beds- Aarhusvand; Denmark/Picture82.jpg', '/Photos/Reed Beds- Aarhusvand; Denmark/Picture81.png']
  },


  {
    id: 38,
    name: 'High Temperature and Pressure with Catalyst Technology',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Conventional sludge dryers densify the sludge only to a limited extent, causing disposal challenges.',
    technology: 'Sludge is dried under high temperature and pressure in the presence of a catalyst.',
    novelty: 'Dehydris™ Ultra (patented technology) is capable of drying sludge more effectively compared to conventional processes.',
    details: 'Utilizes HydroThermal Carbonization in a closed reactor. Produces ultra-dewatered sludge with up to 70% dry solids. Increases biogas production by 30–40% compared to standard thermal drying. The process operates with no odor, consumes 2–3 times less energy than conventional drying, and allows further use of the dried material as biosolids (fertilizer).',
    fieldApplication: 'Applied successfully in a municipal wastewater treatment plant in Handan, China.',
    limitations: 'Produces only partial removal of micropollutants.',
    status: 'No initial response received.',
    references: [{ "Suez": "https://www.suez.com/en/denmark/wastewater/sludge-treatment-via-sludge-carbonization", "https://www.suez.com/-/media/suez-global/files/dk/brochures/brochure_dehydris_ultra.pdf?open=true": "https://www.suez.com/-/media/suez-global/files/dk/brochures/brochure_dehydris_ultra.pdf?open=true" }],
    images: ['/Photos/High Temperature & Pressure with catalyst technology-Suez; Denmark/Picture83.jpg', '/Photos/High Temperature & Pressure with catalyst technology-Suez; Denmark/Picture84.png'],
  },

  {
    id: 39,
    name: 'Steam-Drying and Pyrolysis Technology',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Conventional sludge dryers densify the sludge only to a limited extent, causing disposal challenges.',
    technology: 'Biomass is dewatered, then dried under steam followed by pyrolysis (heating in the absence of air).',
    novelty: 'HECLA® 1,000 transforms waste biomass into a useful resource with minimal manpower for operation and can be monitored remotely.',
    details: 'Transforms sewage sludge into renewable thermal energy, soil-improving biochar, and activated carbon. The steam dryer dries dewatered biomass in an oxygen-free atmosphere with superheated steam at 200°C. In the pyrolysis oven, dried biomass is heated to 650°C in an oxygen-free environment. The resulting biochar can be used for soil improvement, fertilization, or upgraded into activated carbon.',
    fieldApplication: 'Full-scale implementation at several Danish wastewater treatment plants has demonstrated up to 90% reduction in sludge volume and significant carbon capture.',
    limitations: 'Requires consistent sludge input and involves high initial capital investment. Potential release of harmful gases such as dioxins and furans if toxic solids are used.',
    status: 'Not positive response obtained.',
    references: [{ "Aquagreen company, Denmark.": "https://aquagreen.dk/", "https://www.youtube.com/watch?v=RxOmnZtBwnc&t=2s": "https://www.youtube.com/watch?v=RxOmnZtBwnc&t=2s", "https://www.sn.dk/art716024/odsherred-kommune/nyhed/epokegoerende-forsoeg-pyrolyse-fjerner-pfas-i-slam/": "https://www.sn.dk/art716024/odsherred-kommune/nyhed/epokegoerende-forsoeg-pyrolyse-fjerner-pfas-i-slam/" }],
    images: ['/Photos/Steam-drying and pyrolysis technology/Picture85.png'],
  },

  {
    id: 40,
    name: 'Cyclones Sludge Settler',
    country: 'France; Denmark',
    category: 'sludge-treatment',
    currentGap: 'The sludge generated from conventional ASP is highly dilute (~1-5% concentration) and requires heavy treatment for discharge and return feed.',
    technology: 'Cyclonic feed of sludge through the instrument causes densification of sludge by centrifugation of solids.',
    novelty: 'The patented InDense™ technology improves sludge concentration and overall efficiency of the activated sludge process.',
    details: 'Employs high centrifugal forces within hydrocyclones to concentrate sludge. Cyclone devices separate the sludge into two fractions: the concentrated “good” sludge is returned to the plant, while the “bad” fraction is removed as excess sludge. This process increases STP efficiency, especially in winter months, by recycling sludge with higher solid concentrations. It reduces secondary clarifier area requirements, enhances treatment capacity, and allows sludge to settle 4–5 times faster than in conventional settling tanks.',
    fieldApplication: 'Increased the hydraulic capacity of Søholt wastewater treatment plant in Europe by 30%.',
    limitations: 'Only applicable for retrofitting in conventional activated sludge processes.',
    status: 'Initial response not received.',
    references: [{ "SUEZ in Denmark": "https://www.suez.com/en/denmark", "Suez": "https://www.suez.com/en/news/press-releases/suez-increases-30-percent-hydraulic-capacity-soholt-wastewater-treatment-plant-thanks-biomass-densification-technology-first-its-kind-scandinavia" }],
    images: ['/Photos/Cyclones Sludge Settler- Suez; Denmark/Picture86.png', '/Photos/Cyclones Sludge Settler- Suez; Denmark/Picture87.png'],
  },
  {
    id: 41,
    name: 'Smart Waste Management Solution',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Indian cities suffer from overflowing bins, inefficient waste collection routes, high operational costs, and poor urban hygiene.',
    technology: 'IoT sensors (3D optical laser) in waste containers provide real-time fill level data to a cloud platform, enabling intelligent routing and optimized collection.',
    novelty: 'Automated real-time monitoring and AI-driven route optimization significantly reduce collection costs, environmental impact, and improve city cleanliness.',
    details: 'Applicable for municipal and commercial waste collection; optimizes routes, reduces trips, and improves resource allocation.',
    fieldApplication: 'Deployed for customers worldwide, showcasing improved efficiency and cost savings in urban waste collection.',
    limitations: 'Requires sensor installation in bins and an initial investment in the platform.',
    status: 'Communication is under progress.',
    references: [{ "Nordsense": "http://www.nordsense.com/" }],
    images: ['/Photos/Smart Waste Management Solution- Nordsense; Denmark/Picture89.jpg', '/Photos/Smart Waste Management Solution- Nordsense; Denmark/Picture88.png'],
  },

  {
    id: 42,
    name: 'Ecogi System',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'India faces challenges in efficiently segregating and pre-treating organic waste for biogas production, limiting its energy and fertilizer potential.',
    technology: 'Mechanical pre-treatment system for source-separated organic waste, creating a pure biopulp suitable for anaerobic digestion.',
    novelty: 'Handles diverse packaging and efficiently removes impurities, maximizing biogas yield and producing a clean, ready-to-use fertilizer (biopulp).',
    details: 'Processes municipal organic waste to feed biogas plants, improving efficiency and output. Enhances circular economy for food waste.',
    fieldApplication: 'Utilized by public authorities and private companies in waste management, with pulp use as fertilizer.',
    limitations: 'Requires organized collection of organic waste for optimal performance.',
    status: 'Communication is under progress.',
    references: [{ "Ecogi": "https://ecogi.dk/en/" }],
    images: ['/Photos/Ecogi System- Ecogi; Denmark/Picture90.png', '/Photos/Ecogi System- Ecogi; Denmark/Picture91.png'],
  },
  {
    id: 43,
    name: 'Solid Waste Recycling',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'India needs efficient, specialized machinery to process diverse and challenging waste streams (e.g., tires, e-waste, plastics) for higher recycling rates.',
    technology: 'Develops and manufactures machinery for recycling various waste types, including tires, cables, aluminum, e-waste, and MSW.',
    novelty: 'Provides robust, specialized equipment and complete recycling solutions for specific, hard-to-process waste streams to maximize material recovery.',
    details: 'Offers shredders, granulators, and sorting systems for large-scale recycling facilities, converting waste into valuable secondary raw materials.',
    fieldApplication: 'Global presence with installations in numerous countries for tire recycling, e-waste processing, and other specialized waste streams.',
    limitations: 'High capital investment for full-scale recycling plants.',
    status: 'Communication is under progress.',
    references: [{ " ELDAN Recycling": "http://www.eldan-recycling.com/" }],
    images: ['/Photos/Solid waste Recycling/Picture92.jpg', '/Photos/Solid waste Recycling/Picture93.jpg'],
  },
  {
    id: 44,
    name: 'Azortum Solid Waste Sorting',
    country: 'Estonia; Finland',
    category: 'sludge-treatment',
    currentGap: "India's mixed waste streams often have low recycling rates due to inefficient and labor-intensive sorting processes.",
    technology: 'Advanced sorting and recovery technology for plastics, papers, tyres, and construction waste using sensor-based identification.',
    novelty: 'Offers modular and scalable solutions to improve recycling performance, allowing higher purity and recovery from complex waste streams.',
    details: 'Designed for large-scale Material Recovery Facilities and suitable for modernizing existing plants or building new efficient sorting lines. Construction and demolition waste is reused as filling material for roads and underlayers. Tyres are converted into oils through pyrolysis. Wood chips and paper are reused as external fuel. Plastic packaging materials are sent to companies to be used for making new products.',
    fieldApplication: 'The company has installed successful plants in several countries like Latvia and Estonia.',
    limitations: 'Requires investment in specialized sorting equipment.',
    status: 'Communication is under progress.',
    references: [{ "Azortum": "http://www.azortum.com/" }],
    images: ['/Photos/Azortum solid waste sorting/Picture1.png', '/Photos/Azortum solid waste sorting/Picture2.png'],
  },
  {
    id: 45,
    name: 'WAGABOX® Technology – Upgrading Landfill Gas into Renewable Natural Gas (RNG)',
    country: 'France, USA, Canada, Spain',
    category: 'sludge-treatment',
    currentGap: 'India needs sustainable methods to manage organic waste and landfill gas, converting them into renewable energy sources.',
    technology: 'Collects, stores & converts landfill gas into biomethane using advanced membrane filtration.',
    novelty: 'Transforms a major source of greenhouse gas emissions (landfill gas) into a high-value, vehicle-fuel biomethane.',
    details: 'Waste is stored in airtight geotextile membrane. The methane gas released from organic breakdown is collected & stored filtered to make it pure (~98% purity). Methane produced is used in homes & other purposes throughout the city. Reduction in emissions and generating revenue.',
    fieldApplication: 'Multiple operational sites in France, US, Canada, and Spain converting landfill gas into biomethane. 30 landfill gas have been upgraded units in operation worldwide.',
    limitations: 'Requires sufficient methane production from landfill gas and is capital intensive.',
    status: 'Communication is under progress.',
    references: [{ "WAGA Energy": "http://www.waga-energy.com/" }],
    images: [
      '/Photos/WAGABOX® technology/Picture3.jpg',
      '/Photos/WAGABOX® technology/Picture4.png'
    ]
  },
];