export interface Technology {
  id: number;
  name: string;
  country: string;
  category: 'decentralized' | 'stp-improvement' | 'smart-monitoring' | 'sludge-treatment';
  currentGap?: string;
  technology?: string;
  novelty?: string;
  details?: string;
  fieldApplication?: string;
  limitations?: string;
  status?: string;
  references?: {
    [key: string]: string;  // key = name, value = link (URL)
  };
  images?: string[];
  institution?: string;
  authors?: string[];
}

export const categories = {
  decentralized: 'Decentralized Units & NBS',
  'stp-improvement': 'STP Improvement',
  'smart-monitoring': 'Smart Monitoring',
  'sludge-treatment': 'Sludge/Solid Waste Treatment',
};

export const technologies: Technology[] = [
  // Decentralized units & NBS
  {
    id: 1,
    name: 'Floating Wetland',
    country: 'Denmark, USA',
    category: 'decentralized',
    currentGap: 'In India, natural based treatment solutions like wetlands are underutilized and often poorly maintained.',
    technology: 'Growing plants over floating platforms helps in absorbing and degrading pollutants from water bodies.',
    novelty: 'Selected plants and biofilm have been checked for showing its effectiveness in removing the specific pollutants.',
    details: 'Remove dissolved nutrients and heavy metals from water bodies. FW size is scalable and has modular design. Plants and the plant-microbe interactions in the lower surface of the floating island absorb and remove contaminants from the water while supporting other natural processes such as denitrification and sedimentation. Heavy metals (Cd, Cr(VI), Pb, Co, Cu, Pb, Ni, Se, Zn) and Nutrients (e.g. nitrate, ammonium, phosphate) removal from water body has been removed.',
    fieldApplication: 'Has been applied successfully in Denmark.',
    limitations: 'Requires regular monitoring and maintenance. To remove carbon from water bodies, microbial culturing needs to be done.',
    status: 'Communication is under progress.',
    references: {
      'Eco Island': 'https://www.ecoisland.dk/services/',
      'Floating Island International Inc.': 'https://www.floatingislandinternational.com/contact.html'
    },
    images: ['/Photos/Floating Wetlands-/Picture1.jpg', '/Photos/Floating Wetlands-/Picture2.png'],
  },
  {
    id: 2,
    name: 'Photosynthesis Based Wastewater Treatment Using Gir Cow Urine',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Conventional wetland treatment requires longer treatment time with less efficiency.',
    technology: 'Wastewater passed through wetland plants mixed with Gir cow urine gives high efficiency for pollutant degradation.',
    novelty: 'Gir cow urine has been tested along with wetland plants and found to have high catalytic properties for the degradation of domestic wastewater.',
    details: 'Leverage the nutrients in urine to support microbial and algal growth, aiding in purification. Gir Cow Urine\'s nutrients-rich composition enhances microbial activity. Microalgae and purple phototrophic bacteria can play a role in purifying in wastewater by absorbing nutrients and break down organic matter. Photosynthetic microorganism utilize its nutrients to enhance purification efficiency.',
    fieldApplication: 'Lab testing has been conducted with successful results.',
    limitations: 'Takes longer treatment time compared to conventional wastewater technologies.',
    status: 'Initial presentation conducted. Second phase meeting is in progress.',
    references: { 'Pinakin Technology Solutions Pvt Ltd': 'https://pinakin.co.in/' },
    images: ['/Photos/Photosynthesis Based/Picture3.jpg', '/Photos/Photosynthesis Based/Picture5.png'],
  },
  {
    id: 3,
    name: 'Soil Biotechnology (SBT)',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Treating wastewater using nature based solutions with less cost than STP is a big challenge.',
    technology: 'Soil biotechnology (SBT) is a terrestrial system for wastewater treatment based on the principle of the trickling filter.',
    novelty: 'Has potential to be used in place of STP, ETP, ZLD for industries and rivers and lake rejuvenation.',
    details: 'SBT systems are constructed from RCC, stonemasonry or soil bunds. They comprise a raw-water tank, bioreactor containment, treated water tank, piping and pumps. Suitable mineral constitution, bacterial culture and bio-indicator plants are the components of the system. Water passes through the artificial wetland vertically from top to down. Removal processes involves adsorption & filtration on media and biological degradation.',
    fieldApplication: 'SBT plant has been developed in IIT Bombay and has been implemented successfully in Bengaluru and Mumbai.',
    limitations: 'SBT type wastewater treatment plants require high land area of around 2.5 m²/ m³ of wastewater treatment.',
    status: 'Communication is under progress.',
    references: { 'https://www.visionearthcare.com/technology/sbt': 'https://www.visionearthcare.com/technology/sbt' },
    images: ['/Photos/Soil biotechnology (SBT)/Picture6.jpg', '/Photos/Soil biotechnology (SBT)/Picture7.png', '/Photos/Soil biotechnology (SBT)/Picture8.jpg'],
  },
  {
    id: 4,
    name: 'Phytorid',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Limited capacity of centralized treatment leads to untreated sewage disposal in water bodies. Need for zero-energy, low-maintenance treatment solutions.',
    technology: 'Constructed wetland technology developed by CSIR-NEERI that uses specific wetland plants in a subsurface flow system filled with porous media for natural wastewater treatment.',
    novelty: 'Self-sustainable, zero-energy, zero O&M technology using soil-free wetland treatment. Uses both wetland and non-wetland plant species acclimatized for specific nutrient removal.',
    details: 'System consists of Primary Settling Cell, Advanced Filter Cell (gravel/stones in layers), and Phytorid Treatment Cell with plants like Elephant grass, Cattails, Reeds, Cannas, and Yellow flag iris. Plants act as nutrient sinkers directly from wastewater without requiring soil. Removal efficiency: BOD (78-84%), COD (similar), TSS (70-80%), Nitrogen (70-75%), Phosphorus (52-64%), Fecal coliform (90-97%). Wastewater flows vertically through porous media maintaining subsurface flow. Technology works through physical filtration, sedimentation, adsorption, and biological degradation by plant-root-microbe interactions.',
    fieldApplication: 'Successfully implemented at CSIR-NCL, Mumbai University, Raj Bhawan, various locations in Mumbai, Thane, Nashik, Panvel, Allahabad, and Matheran. Used for lake rejuvenation projects.',
    limitations: 'Requires approximately 35 sq.m. area for 20 m³/day treatment capacity. Treated water primarily suitable for non-potable uses like gardens, fountains, and irrigation.',
    status: 'Technology patented in India, Europe, and Australia. Widely commercialized and implemented across India.',
    references: { 'NEERI Nagpur': 'https://www.neeri.res.in/contents/banner_details/phytorid-wastewater-treatment-technology/5b193f6eaacd7googtrans(en%7Cen)#googtrans(en|en)' },
    images: ['/Photos/Phytorid/Picture9.png', '/Photos/Phytorid/Picture10.png'],
  },
  {
    id: 5,
    name: 'Freeze Technology',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Energy-intensive desalination and concentration processes create high operational costs in water treatment.',
    technology: 'Freeze crystallization technology that separates water from contaminants by controlled freezing, producing ice crystals of pure water.',
    novelty: 'Lower energy consumption compared to thermal evaporation. Can concentrate wastewater while producing pure water crystals.',
    details: 'Process involves cooling wastewater below freezing point, forming ice crystals of pure water while contaminants remain in concentrated liquid phase. Ice crystals are separated and melted to produce clean water. Effective for desalination, heavy metal removal, and wastewater concentration. Energy requirement is theoretically lower than evaporation as latent heat of freezing is less than vaporization.',
    fieldApplication: 'Pilot-scale implementations in industrial wastewater treatment, particularly for high-salinity streams.',
    limitations: 'Ice-liquid separation can be challenging. Scaling and fouling issues. Pre-treatment may be required for suspended solids. Capital cost can be high.',
    status: 'Emerging technology with ongoing pilot projects.',
    references: ['Various Indian research institutions'],
    images: ['/Photos/Freeze Technology/Picture11.png', '/Photos/Freeze Technology/Picture12.png'],
  },
  {
    id: 6,
    name: 'Nano Bubble',
    country: 'USA',
    category: 'decentralized',
    currentGap: 'Traditional aeration systems have low oxygen transfer rates, high energy consumption, and limited effectiveness in treating complex wastewater with surfactants and inhibitory compounds.',
    technology: 'Nanobubble generators produce ultra-fine gas bubbles (less than 1 μm diameter) with unique properties including high stability, low buoyancy, and ability to generate reactive oxygen species.',
    novelty: 'Nanobubbles remain suspended in water for extended periods (hours to months), have charged surfaces for contaminant attraction, and generate free radicals for enhanced oxidation. Oxygen transfer efficiency is significantly higher than conventional aeration.',
    details: 'Nanobubbles possess large surface area-to-volume ratio enabling efficient gas transfer and contaminant interaction. Applications include: enhanced flotation for grease/oil removal, improved aerobic biological treatment (activated sludge, MBR, constructed wetlands), protection against biological process inhibition from surfactants and quaternary ammonium compounds (QACs), oxidation of organic compounds through ROS generation. Improves TOC removal (49% vs 27-36% conventional), ammonia removal (65% vs 22-48%), and power generation in microbial fuel cells (5.5x higher). Reduces BOD, COD, and energy consumption while improving treatment stability.',
    fieldApplication: 'Successfully deployed at municipal WWTPs (City of Lodi, California plants), food & beverage facilities (Meister Cheese Co.), industrial facilities, and aquaculture operations. Used for lake/pond restoration and agricultural irrigation enhancement.',
    limitations: 'Requires specialized nanobubble generators. Initial capital investment for equipment. Performance depends on proper integration with existing systems. Not suitable for all contaminant types.',
    status: 'Commercially available and actively deployed. Major vendors include Moleaer (USA), NICO Nanobubble India Co.',
    references: ['Moleaer Inc.', 'NICO Nanobubble India Co.', 'Scientific literature in Water Research, Science of the Total Environment, ACS ES&T Engineering'],
    images: ['/Photos/Nano-Bubble Generators/Picture13.jpg', '/Photos/Nano-Bubble Generators/Picture14.jpg'],
  },
  {
    id: 7,
    name: 'Watopi',
    country: 'Denmark',
    category: 'decentralized',
    currentGap: 'Need for decentralized, nature-based water treatment solutions with minimal infrastructure in water-scarce regions.',
    technology: 'Modular wetland-based water treatment system that combines natural filtration with constructed wetland principles.',
    novelty: 'Containerized or modular design allows for flexible deployment. Integrates Danish expertise in wetland engineering.',
    details: 'System uses series of treatment cells with different wetland plants and substrates. Natural biological processes combined with physical filtration. Suitable for small communities and decentralized applications. Low energy requirement with focus on sustainability.',
    fieldApplication: 'Implemented in Denmark and exported to developing regions for community-scale treatment.',
    limitations: 'Climate-dependent performance. Requires land area. Seasonal variations in efficiency.',
    status: 'Commercial technology available from Danish providers.',
    references: ['Danish water technology companies'],
    images: ['/Photos/Watopi- BioKube, Denmark/Picture15.png', '/Photos/Watopi- BioKube, Denmark/Picture16.jpg', '/Photos/Watopi- BioKube, Denmark/Picture17.jpg'],
  },
  {
    id: 8,
    name: 'Microbial Fuel Cell',
    country: 'USA',
    category: 'decentralized',
    currentGap: 'Conventional wastewater treatment is energy-intensive, consuming significant power without energy recovery.',
    technology: 'Bioelectrochemical system where microorganisms oxidize organic matter and generate electricity through electron transfer to an electrode.',
    novelty: 'Simultaneous wastewater treatment and electricity generation. Can be integrated with other technologies like constructed wetlands and nanobubbles for enhanced performance.',
    details: 'MFCs contain anode chamber with anaerobic bacteria that oxidize organics and release electrons, cathode chamber with oxygen or other electron acceptor, and proton exchange membrane. Electrons flow through external circuit generating power. When coupled with nanobubble-aerated constructed wetlands, power generation increases 5.5x (to 29 mW/m²). Can treat domestic, industrial, and agricultural wastewater while recovering energy.',
    fieldApplication: 'Laboratory and pilot-scale demonstrations. Research installations at universities and demonstration sites. Integration with constructed wetlands shown in field trials.',
    limitations: 'Low power density compared to energy consumption of treatment. Expensive electrode materials. Membrane fouling. Scale-up challenges. Still largely in research/pilot phase for practical applications.',
    status: 'Emerging technology in transition from research to early commercial adoption.',
    references: ['Various US universities and research institutions', 'Scientific literature on bioelectrochemical systems'],
    images: ['/Photos/Microbial Fuel Cell- Aquacyl; USA/Picture18.png', '/Photos/Microbial Fuel Cell- Aquacyl; USA/Picture19.jpg'],
  },
  {
    id: 9,
    name: 'Water Mantra Technology',
    country: 'Singapore',
    category: 'decentralized',
    currentGap: 'Need for compact, efficient decentralized water treatment for urban and semi-urban areas with space constraints.',
    technology: 'Integrated water treatment system combining multiple treatment stages in compact footprint for decentralized applications.',
    novelty: 'Modular design with smart monitoring capabilities. Optimized for tropical climates and dense urban environments.',
    details: 'Multi-barrier treatment approach combining physical, chemical, and biological processes. Automated monitoring and control systems. Designed for small to medium capacity installations. Emphasis on water reuse and recovery.',
    fieldApplication: 'Deployed in Singapore and Southeast Asian markets for residential, commercial, and industrial sites.',
    limitations: 'Requires regular maintenance and monitoring. Initial cost may be higher than conventional systems.',
    status: 'Commercial technology from Singapore-based company.',
    references: ['Singapore water technology sector'],
    images: ['/Photos/Water Mantra-h2Omantra; Singapore/Picture20.png', '/Photos/Water Mantra-h2Omantra; Singapore/Picture21.png', '/Photos/Water Mantra-h2Omantra; Singapore/Picture22.png'],
  },
  {
    id: 10,
    name: 'Electro-oxidation',
    country: 'India',
    category: 'decentralized',
    currentGap: 'Difficulty in treating recalcitrant organic pollutants, dyes, and toxic compounds that resist biological treatment.',
    technology: 'Advanced oxidation process using electrochemical reactions at electrode surfaces to oxidize and mineralize organic pollutants.',
    novelty: 'Generates powerful hydroxyl radicals and other oxidants in-situ without chemical addition. Effective for destroying refractory organics.',
    details: 'Uses dimensionally stable anodes (DSA) or boron-doped diamond (BDD) electrodes. When current is applied, water is oxidized at the anode surface generating hydroxyl radicals (·OH) and other reactive oxygen species. These oxidize organic pollutants into CO2, H2O, and simple inorganic compounds. Effective for COD reduction, color removal, and destruction of pharmaceuticals, pesticides, and industrial chemicals. Can be combined with biological treatment for complete mineralization.',
    fieldApplication: 'Used in pharmaceutical, textile, tannery, and chemical industries in India. Particularly effective as polishing step after biological treatment.',
    limitations: 'High energy consumption. Electrode cost and lifespan. Formation of chlorinated byproducts if chlorides present. Regular electrode maintenance required.',
    status: 'Commercial technology with established Indian suppliers.',
    references: ['Indian electrochemical technology providers', 'IIT research groups'],
    images: ['/Photos/Electro Oxidation Technology; Pinakin/Picture23.jpg', '/Photos/Electro Oxidation Technology; Pinakin/Picture24.png', '/Photos/Electro Oxidation Technology; Pinakin/Picture25.png'],
  },
  {
    id: 11,
    name: 'Onsite Oxidation',
    country: 'Denmark',
    category: 'decentralized',
    currentGap: 'Need for effective on-site treatment of micropollutants and emerging contaminants at source.',
    technology: 'Advanced oxidation technology for on-site treatment using ozone, UV, or combined oxidation processes.',
    novelty: 'Point-of-generation treatment prevents pollutant entry into water systems. Compact systems for decentralized application.',
    details: 'Employs oxidation processes such as UV/H2O2, ozonation, or Fenton oxidation for destroying micropollutants, pharmaceuticals, and persistent organics. Can be installed at hospitals, laboratories, and industrial sites to treat wastewater at source. Reduces burden on central treatment plants.',
    fieldApplication: 'Installed at Danish hospitals and pharmaceutical facilities for treating medicinal wastewater.',
    limitations: 'Operating costs for oxidant chemicals or UV power. Byproduct formation possible. Requires skilled operation.',
    status: 'Commercial solutions available from Danish water technology companies.',
    references: ['Danish Environmental Protection Agency', 'Nordic water technology providers'],
    images: ['/Photos/Onsite Oxidation- hpnow; Denmark/Picture26.jpg', '/Photos/Onsite Oxidation- hpnow; Denmark/Picture27.jpg'],
  },
  {
    id: 12,
    name: 'Pulse Plasma',
    country: 'Germany',
    category: 'decentralized',
    currentGap: 'Conventional treatment methods struggle with persistent organic pollutants, pathogens, and pharmaceutical residues.',
    technology: 'Non-thermal plasma technology using pulsed electrical discharges in water to generate reactive species for pollutant degradation and disinfection.',
    novelty: 'Generates UV radiation, shockwaves, and multiple reactive species (OH·, O3, H2O2) simultaneously without chemical addition.',
    details: 'High voltage pulses create plasma streamers in water, producing physical and chemical effects: UV photolysis, acoustic cavitation, pyrolysis, and generation of reactive oxygen and nitrogen species. Simultaneously degrades organics and inactivates microorganisms. Effective against pharmaceuticals, PFAS, dyes, and pathogens. Can treat small volumes efficiently.',
    fieldApplication: 'Pilot installations in Germany for pharmaceutical wastewater and hospital effluent treatment. Research applications in water disinfection.',
    limitations: 'High energy requirement per volume treated. Electrode erosion. Suitable mainly for small flow rates. Capital cost can be significant.',
    status: 'Advanced development stage with pilot implementations.',
    references: ['German research institutions', 'Fraunhofer Institute', 'Technical universities'],
    images: ['/Photos/Pulse Plasma- Fidtech; Germany/Picture28.png', '/Photos/Pulse Plasma- Fidtech; Germany/Picture29.png', '/Photos/Pulse Plasma- Fidtech; Germany/Picture30.jpg'],
  },
  {
    id: 13,
    name: 'MVR Technology',
    country: 'Denmark',
    category: 'decentralized',
    currentGap: 'Energy-intensive evaporation processes in zero liquid discharge (ZLD) and brine concentration applications.',
    technology: 'Mechanical Vapor Recompression uses a compressor to recycle and reuse heat energy from evaporation, significantly reducing energy consumption.',
    novelty: 'Energy recovery through vapor recompression reduces thermal energy requirement by 90% compared to conventional evaporation.',
    details: 'Wastewater is heated and evaporated. The generated vapor is compressed, which increases its temperature and pressure. This hot compressed vapor is used to heat incoming wastewater in a heat exchanger, creating a self-sustaining cycle. Produces distilled water and concentrated brine/solids. Typical energy consumption 20-25 kWh/m³ of distillate compared to 60-80 kWh/m³ for conventional evaporation. Particularly effective for ZLD applications, desalination concentrate treatment, and industrial wastewater with high TDS.',
    fieldApplication: 'Widely used in Europe for industrial ZLD, dairy industry, pharmaceutical, and chemical industries. Proven technology with thousands of installations globally.',
    limitations: 'High capital investment. Requires skilled maintenance. Scaling/fouling issues with high hardness water. Not economical for very low TDS water.',
    status: 'Mature commercial technology with established vendors.',
    references: ['Danish industry', 'GEA Process Engineering', 'European ZLD providers'],
    images: ['/Photos/MVR Technology- Envotherm; Denmark/Picture31.png', '/Photos/MVR Technology- Envotherm; Denmark/Picture32.png'],
  },
  {
    id: 14,
    name: 'Geotubes - Solmax',
    country: 'India & Australia',
    category: 'decentralized',
    currentGap: 'Sludge dewatering is costly, energy-intensive, and requires significant infrastructure. Traditional methods have high operating costs.',
    technology: 'Large geotextile tubes that dewater sludge through natural filtration and gravity drainage. Polymers flocculate solids which are retained in the tube while water drains through the permeable fabric.',
    novelty: 'Passive dewatering requiring no mechanical equipment or external energy. Can handle large volumes in short time with minimal labor.',
    details: 'High-strength woven geotextile tubes (up to 100m long) are filled with conditioned sludge. Polymer is added for flocculation. Solids are retained inside while water filters through the fabric. Solar drying and consolidation occur over weeks to months, achieving 15-30% solids content. Can be used for dredged materials, industrial sludge, wastewater biosolids. Tubes can be stacked or reused.',
    fieldApplication: 'Used extensively in India and Australia for sewage sludge, mining tailings, dredging projects, and industrial waste. Hundreds of projects completed.',
    limitations: 'Requires large land area. Dewatering time is long (weeks to months). Performance affected by weather/climate. Not suitable where rapid turnaround needed. Final disposal of dewatered cake still required.',
    status: 'Established commercial technology. Solmax and other vendors provide turnkey solutions.',
    references: ['Solmax International', 'TenCate Geosynthetics', 'Indian and Australian environmental engineering firms'],
    images: ['/Photos/Geotubes/Picture33.jpg', '/Photos/Geotubes/Picture34.png'],
  },
  {
    id: 15,
    name: 'Poseidon Pellets – Phosphorous Removal',
    country: 'USA',
    category: 'decentralized',
    currentGap: 'Phosphorus removal in wastewater treatment often requires chemical dosing or expensive biological processes. Nutrient recovery is not practiced.',
    technology: 'Iron-based reactive media in pellet form that adsorbs phosphorus from wastewater through surface reactions, enabling passive nutrient removal.',
    novelty: 'Simultaneous phosphorus removal and recovery. Media can be regenerated or used as fertilizer. Passive treatment without chemical addition.',
    details: 'Poseidon pellets are iron oxide-coated media with high affinity for phosphate. As water flows through pellet bed, phosphate is adsorbed onto iron surface through ligand exchange and precipitation reactions. Achieves low effluent phosphorus levels (<0.1 mg/L). Spent media can be regenerated with alkali solution recovering phosphate for fertilizer use, or used directly as slow-release fertilizer. Can be used in filters, columns, or reactive barriers.',
    fieldApplication: 'Implemented at municipal WWTPs in USA for tertiary phosphorus removal. Used in stormwater treatment and agricultural runoff management.',
    limitations: 'Media requires periodic replacement or regeneration. Pre-filtration needed to prevent clogging. Limited capacity requires sizing based on phosphorus load. Not effective for nitrogen removal.',
    status: 'Commercial technology with proven installations.',
    references: ['Advanced Water Management Inc.', 'US EPA nutrient removal case studies'],
    images: ['/Photos/Poseidon Pellets/Picture35.jpg', '/Photos/Poseidon Pellets/Picture36.jpg', '/Photos/Poseidon Pellets/Picture37.jpg'],
  },
  {
    id: 16,
    name: 'Coagulation-Flocculation',
    country: 'China',
    category: 'decentralized',
    currentGap: 'Removal of suspended solids, colloids, and turbidity requires effective solid-liquid separation. Emerging pollutants need advanced treatment.',
    technology: 'Chemical treatment process using coagulants (aluminum/iron salts or polymers) to destabilize particles, followed by flocculants to form large settleable flocs.',
    novelty: 'Advanced high-efficiency coagulants and flocculants developed in China. Magnetic coagulation and electrocoagulation variants offer enhanced performance.',
    details: 'Coagulant chemicals neutralize particle surface charges causing destabilization. Flocculants bridge particles forming large flocs that settle rapidly. Process parameters: rapid mixing for coagulant dispersion (1-3 min), slow mixing for floc formation (15-30 min), sedimentation for separation. Removes suspended solids, turbidity, color, phosphorus, heavy metals, and some organic matter. New developments include polyaluminum chloride (PAC), polyferric sulfate (PFS), and composite coagulants. Can be combined with membrane filtration or dissolved air flotation.',
    fieldApplication: 'Universally applied in Chinese drinking water plants and industrial WWTPs. Used in paper, textile, mining, and municipal applications. Millions of installations.',
    limitations: 'Generates chemical sludge requiring disposal. pH dependent. Chemical costs. Not effective alone for dissolved organics or nutrients. Overdosing can worsen water quality.',
    status: 'Mature technology continuously being improved with novel coagulants.',
    references: ['Chinese water treatment industry', 'Major coagulant manufacturers in China', 'Research from Tsinghua, Tongji universities'],
    images: ['/Photos/Coagulation/Picture38.png', '/Photos/Coagulation/Picture39.png'],
  },
  // STP Improvement
  {
    id: 17,
    name: 'MBR',
    country: 'France & USA',
    category: 'stp-improvement',
    currentGap: 'Conventional activated sludge with clarifiers requires large footprint, produces variable effluent quality, and has limited ability to treat micropollutants.',
    technology: 'Membrane Bioreactor combines activated sludge biological treatment with membrane filtration (microfiltration or ultrafiltration) for solid-liquid separation.',
    novelty: 'Eliminates need for secondary clarifiers. Produces high-quality effluent suitable for reuse. Can operate at higher MLSS concentrations (8,000-12,000 mg/L).',
    details: 'Microorganisms degrade organic matter and nutrients in bioreactor. Membrane module (submerged or external) filters treated water, completely retaining biomass and suspended solids. Produces effluent with near-zero TSS and turbidity, very low BOD (<5 mg/L) and COD, reduced pathogens. Average removal: BOD 88%, COD 84%, TN 65%, TP 60%. Enables longer SRT for nitrification and growth of slow-growing microorganisms. Compact footprint (1/3 to 1/2 of conventional). Effluent suitable for non-potable reuse, irrigation, industrial processes.',
    fieldApplication: 'Thousands of installations globally including large municipal plants (>100,000 PE). Major installations in France, USA, Asia. Used in water-scarce regions for water reuse. Industrial applications in food/beverage, pharmaceutical, semiconductor industries.',
    limitations: 'Membrane fouling requiring regular cleaning. Higher energy consumption for aeration and membrane operation. Membrane replacement costs. Requires skilled operation. Capital cost 20-40% higher than conventional treatment.',
    status: 'Mature commercial technology. Leading vendors: Suez (France), Evoqua (USA), Toray, Mitsubishi.',
    references: ['Suez Water Technologies', 'Evoqua', 'Membrane Bioreactor Industry Consortium', 'IWA MBR specialist group'],
    images: ['/Photos/Membrane Bioreactor/Picture40.png', '/Photos/Membrane Bioreactor/Picture41.jpg'],
  },
  {
    id: 18,
    name: 'MBBR',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Activated sludge requires large tank volumes, complex sludge recirculation, and sensitive operation. Limited capacity to handle organic shock loads.',
    technology: 'Moving Bed Biofilm Reactor uses free-floating plastic carriers that provide surface for biofilm growth while moving continuously in the aeration tank.',
    novelty: 'Combines benefits of suspended growth (activated sludge) and attached growth (biofilm) systems. No sludge recirculation needed. Compact design with high volumetric loading.',
    details: 'Developed in late 1980s by Prof. Hallvard Ødegaard (Norway). Carriers (filling 40-70% of reactor volume) have density close to water and move freely via aeration or mechanical mixing. Large protected surface area (>5,500 m²/m³ for advanced media) supports high biomass concentration (4,000-8,000 mg/L MLSS equivalent). Biofilm protected from toxic shocks. Processes: BOD/COD removal, nitrification, denitrification (in anoxic zones). Average removal: BOD 87%, COD 80%, TN 56%, TP 54%. Can retrofit existing tanks to increase capacity. Applications include municipal WWTPs, industrial wastewater (pulp & paper, food processing, petrochemical), and aquaculture.',
    fieldApplication: 'Over 1000 installations worldwide. Widely used in Scandinavia, North America, Asia. Successful retrofits increasing plant capacity 2-3x. Works in extreme climates from Arctic to tropical.',
    limitations: 'Higher energy consumption than activated sludge to keep carriers suspended. Requires secondary clarifier for suspended solids separation (unless combined with membrane). Media replacement every 10-15 years. Not as effective as MBR for complete solid removal.',
    status: 'Mature proven technology. Major vendors: Veolia/AnoxKaldnes (Denmark), SSI Aeration, Ecologix.',
    references: ['AnoxKaldnes (Veolia)', 'SSI Aeration', 'Norwegian University of Science and Technology', 'Wikipedia MBBR article'],
    images: ['/Photos/Membrane Bioreactor/Picture40.png', '/Photos/Membrane Bioreactor/Picture41.jpg'],
  },
  {
    id: 19,
    name: 'IFAS Technology',
    country: 'Canada',
    category: 'stp-improvement',
    currentGap: 'Existing activated sludge plants reaching capacity limits. Need to upgrade without expanding tank volume.',
    technology: 'Integrated Fixed-Film Activated Sludge combines suspended growth activated sludge with attached growth biofilm media in the same tank.',
    novelty: 'Hybrid system providing benefits of both technologies. Media can be added to existing tanks for capacity increase without construction.',
    details: 'Fixed media (plastic carriers or rope/fabric media) are added to activated sludge aeration tanks. Both suspended and attached biomass treat wastewater simultaneously. Biofilm on media provides additional treatment capacity and protects nitrifying bacteria. Suspended biomass handles bulk organic removal and provides denitrification. System maintains conventional sludge recirculation. Particularly effective for enhanced nitrogen removal through simultaneous nitrification-denitrification. Can increase treatment capacity 50-100% in existing tankage. Lower footprint than conventional activated sludge upgrades.',
    fieldApplication: 'Numerous installations across North America for municipal WWTP upgrades. Successfully implemented in Canada, USA for plants requiring nutrient removal compliance. Typical size range 5,000 to 500,000 PE.',
    limitations: 'More complex than pure MBBR or activated sludge. Requires careful balance between suspended and attached biomass. Mixing and aeration requirements higher than conventional AS. Media fouling possible with certain wastewaters.',
    status: 'Proven commercial technology for capacity upgrades.',
    references: ['InfraCor (Canada)', 'Evoqua Technologies', 'Various Canadian municipalities', 'WEF publications'],
    images: ['/Photos/Integrated Fixed-film Activated Sludge/Picture46.png', '/Photos/Integrated Fixed-film Activated Sludge/Picture47.emf'],
  },
  {
    id: 20,
    name: 'Membranes',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Need for advanced solid-liquid separation, pathogen removal, and water reuse quality. Conventional clarification insufficient for stringent standards.',
    technology: 'Pressure-driven membrane filtration technologies including Microfiltration (MF), Ultrafiltration (UF), Nanofiltration (NF), and Reverse Osmosis (RO) for water treatment.',
    novelty: 'Absolute barriers for particles, microorganisms, and dissolved contaminants depending on membrane type. Modular and scalable design.',
    details: 'MF/UF (0.01-0.1 μm pore size): Remove suspended solids, bacteria, protozoa, viruses. Used in MBR and tertiary filtration. NF (0.001 μm): Remove hardness, divalent ions, organic molecules, partial desalination. RO (<0.001 μm): Remove dissolved salts, metals, organics; produces ultrapure water. Applications: drinking water production, wastewater reuse, desalination, industrial water purification. Can achieve >99.9% removal of pathogens. Danish companies lead in ceramic membrane development (higher fouling resistance than polymeric).',
    fieldApplication: 'Global market with millions of installations. Municipal drinking water, wastewater reuse plants, seawater desalination, industrial processes, pharmaceutical production. Increasing adoption in water-scarce regions.',
    limitations: 'Membrane fouling and scaling requiring cleaning. Energy intensive especially for RO. Concentrate/brine disposal. Membrane replacement costs. Pre-treatment required for many applications.',
    status: 'Mature commercial technology with continuous innovation in materials and configurations.',
    references: ['Danish water technology sector', 'Major membrane manufacturers: Toray, Dow, Hydranautics, Pentair'],
    images: ['/Photos/Membranes; Aquaporin/Picture48.png', '/Photos/Membranes; Aquaporin/Picture49.png', '/Photos/Membranes; Aquaporin/Picture50.png'],
  },
  {
    id: 21,
    name: 'Ceramic Membrane Filtration',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Polymeric membranes degrade with harsh chemicals, high temperatures, and aggressive cleaning. Limited lifespan in difficult applications.',
    technology: 'Membranes made from inorganic materials (alumina, titania, zirconia) offering superior chemical and thermal resistance compared to polymer membranes.',
    novelty: 'Withstands pH 0-14, temperatures up to 150°C, aggressive oxidizing cleaners. Longer lifespan (>10 years vs 3-7 for polymers). Higher fouling resistance.',
    details: 'Ceramic membranes have rigid porous structure with precise pore size control. Available in MF and UF range. Can be cleaned with strong acids, bases, oxidizers without degradation, enabling recovery from severe fouling. Applications: dairy processing, oil-water separation, municipal drinking water, harsh industrial wastewaters. Denmark is global leader in ceramic membrane technology. Higher flux rates and cleaning efficiency reduce overall operating costs despite higher capital cost.',
    fieldApplication: 'Growing adoption in drinking water plants in Denmark, Netherlands, France. Industrial applications in food/beverage, petrochemical, pharmaceutical industries. Several large municipal installations.',
    limitations: 'Higher capital cost (2-3x polymeric membranes). Brittleness requires careful handling. Limited suppliers compared to polymeric. Not available in all configurations (no spiral wound).',
    status: 'Established technology with expanding market. Expected to grow as costs decrease.',
    references: ['LiqTech (Denmark)', 'TAMI Industries', 'Metawater', 'Danish Technological Institute'],
    images: ['/Photos/Ceramic Membrane Filtration/Picture51.png'],
  },
  {
    id: 22,
    name: 'Revolving Algal Biofilm System',
    country: 'USA',
    category: 'stp-improvement',
    currentGap: 'Algae-based treatment requires large ponds, long HRT, and difficult biomass harvesting. Conventional algae systems have low productivity.',
    technology: 'Rotating biofilm reactor where algae grow on slowly revolving vertical surfaces alternately exposed to wastewater and air/sunlight.',
    novelty: 'Higher algae productivity than ponds through optimized light exposure. Easy harvesting by scraping biofilm. Simultaneous nutrient removal and biomass production.',
    details: 'System consists of rotating cylinders or belts with textured surface submerged in wastewater. Algal biofilm grows on surface. As cylinders rotate, biofilm is alternately exposed to nutrient-rich water and to air/light for photosynthesis. Mature biofilm is scraped off for harvest. Algae uptake nitrogen and phosphorus while producing oxygen that supports aerobic bacteria. Integrated algae-bacteria system treats wastewater. Harvested algae biomass can be used for biofuel, animal feed, or fertilizer. Treats municipal and agricultural wastewater with high nutrient content. Removal: >90% ammonia, >80% phosphorus.',
    fieldApplication: 'Pilot and demonstration projects in USA. Installations at universities and research facilities. Several commercial installations for agricultural runoff treatment.',
    limitations: 'Requires sunlight - limited in cloudy regions or winter. Seasonal performance variation. Mechanical complexity of rotating system. Capital and maintenance costs. Algae biomass utilization pathways still developing.',
    status: 'Emerging commercial technology transitioning from research.',
    references: ['US DOE funded projects', 'Utah State University research', 'Gross-Wen Technologies'],
    images: ['/Photos/Revolving Algal Biofilm System/Picture52.png', '/Photos/Revolving Algal Biofilm System/Picture53.png', '/Photos/Revolving Algal Biofilm System/Picture54.png'],
  },
  {
    id: 23,
    name: 'Nicotinamide Adenine Dinucleotide (NADH) Probes',
    country: 'U.S.A',
    category: 'stp-improvement',
    currentGap: 'Traditional wastewater monitoring relies on grab samples and lab analysis with delayed results. Real-time process control is limited.',
    technology: 'Optical sensors that measure NADH fluorescence as indicator of microbial activity and process performance in biological wastewater treatment.',
    novelty: 'Real-time measurement of biological activity. NADH is key coenzyme in microbial metabolism - its concentration reflects treatment effectiveness.',
    details: 'NADH molecules fluoresce when excited by UV light. Fluorescence intensity correlates with active biomass concentration and metabolic activity. Probes inserted into bioreactors provide continuous monitoring. Helps optimize: aeration rates, substrate loading, nutrient dosing, early warning of process upsets. Enables automated process control for stable treatment performance and energy savings. Can reduce aeration energy 10-30% through optimized control.',
    fieldApplication: 'Implemented in advanced WWTPs in USA and Europe. Used in industrial biological treatment for breweries, food processing, pharmaceutical plants. Hundreds of installations globally.',
    limitations: 'Probe fouling requiring cleaning. Interference from other fluorescent compounds. Requires calibration and correlation with conventional parameters. Cost of sensors and control systems.',
    status: 'Commercial technology with proven applications.',
    references: ['Real Tech Inc.', 'Hach Company', 'Endress+Hauser', 'Scientific literature on biological process monitoring'],
    images: ['/Photos/Nicotinamide Adenine Dinucleotide/Picture55.png', '/Photos/Nicotinamide Adenine Dinucleotide/Picture56.png'],
  },
  {
    id: 24,
    name: 'Supercritical Water Oxidation',
    country: 'USA',
    category: 'stp-improvement',
    currentGap: 'Hazardous and recalcitrant organic wastes cannot be treated by biological methods. Incineration creates air emissions.',
    technology: 'Advanced oxidation using water above critical point (374°C, 221 bar) where organic compounds rapidly oxidize to CO2 and water.',
    novelty: 'Complete destruction of organics (>99.99%) in minutes. No air emissions. Salts precipitate and can be recovered.',
    details: 'Waste is pressurized and heated above supercritical point. Oxygen is injected. In supercritical water, organic compounds are completely miscible and oxidize rapidly to CO2, H2O, and minerals. Reaction time: seconds to minutes. Destroys: hazardous wastes, pharmaceuticals, sewage sludge, chemical weapons, PCBs, dioxins. Energy intensive but can be partially recovered. Produces clean water and recoverable salts. No toxic byproducts.',
    fieldApplication: 'Commercial plants in USA for destruction of chemical warfare agents and hazardous wastes. Pilot plants for sewage sludge treatment. Used by US military and specialty waste treatment companies.',
    limitations: 'Very high capital and operating costs. Extreme operating conditions require special materials. High energy requirement. Corrosion issues with salts. Economic mainly for high-value hazardous waste destruction, not bulk wastewater.',
    status: 'Mature but niche technology for specific applications.',
    references: ['General Atomics', 'US Department of Defense programs', 'Scientific literature on SCWO'],
    images: ['/Photos/Supercritical Water Oxidation/Picture57.png', '/Photos/Supercritical Water Oxidation/Picture58.jpg', '/Photos/Supercritical Water Oxidation/Picture59.png', '/Photos/Supercritical Water Oxidation/Picture60.png'],
  },
  {
    id: 25,
    name: 'Energy-Positive Wastewater Treatment',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Wastewater treatment is energy-intensive, consuming 1-3% of total electricity in developed countries. Need for energy-neutral or positive operations.',
    technology: 'Integrated treatment approach maximizing energy recovery from wastewater organics through anaerobic digestion, combined with energy efficiency measures.',
    novelty: 'Produces more energy than consumed. Transforms WWTP from energy consumer to energy producer and resource recovery facility.',
    details: 'Key elements: maximize carbon capture to anaerobic digestion (chemically enhanced primary treatment, sidestream treatment, A-stage in AB process), optimize anaerobic digestion (thermal hydrolysis pretreatment, co-digestion with other organics), maximize biogas yield and utilize efficiently (CHP, biogas upgrading to vehicle fuel), minimize aeration energy (efficient diffusers, process control, use of MBR or IFAS), energy recovery from effluent (heat exchangers). Danish WWTPs like Avedøre, Marselisborg, and Ejby Mølle achieve >100% energy self-sufficiency, producing surplus renewable energy. Combines with nutrient recovery for circular economy.',
    fieldApplication: 'Multiple full-scale energy-positive WWTPs operating in Denmark. Examples: Marselisborg WWTP (Aarhus) produces 150% of energy consumed. Ejby Mølle WWTP energy neutral. Technology exported worldwide.',
    limitations: 'Requires holistic redesign of WWTP. High initial investment. Some technologies (thermal hydrolysis) add complexity. Not all sites suitable - depends on wastewater characteristics and plant size.',
    status: 'Proven concept with operating examples. Becoming best practice in progressive jurisdictions.',
    references: ['Danish water utilities (BIOFOS, Aarhus Vand)', 'Water Environment Research Foundation', 'IWA energy-positive WWTP case studies'],
    images: ['/Photos/Energy-Positive Wastewater Treatment/Picture61.jpg'],
  },
  {
    id: 26,
    name: 'UV Systems',
    country: 'Denmark',
    category: 'stp-improvement',
    currentGap: 'Chlorine disinfection creates harmful disinfection byproducts (DBPs). Need for chemical-free disinfection especially for water reuse.',
    technology: 'Ultraviolet light disinfection using UV lamps (typically 254 nm wavelength) to inactivate microorganisms by damaging their DNA/RNA.',
    novelty: 'No chemical addition or residual. No DBPs formation. Effective against chlorine-resistant pathogens like Cryptosporidium. Compact footprint.',
    details: 'UV-C radiation penetrates microbial cells and damages genetic material, preventing reproduction. Achieves 3-4 log inactivation of bacteria, 2-4 log viruses, 2-3 log protozoa. UV dose typically 30-100 mJ/cm² depending on target organism and water quality. Modern systems use efficient LED or amalgam lamps with automated cleaning, intensity monitoring, and dose control. No contact time required - treatment is instantaneous. Can be combined with H2O2 for UV/AOP destroying micropollutants.',
    fieldApplication: 'Standard disinfection technology at thousands of WWTPs globally. Mandatory for water reuse applications in many jurisdictions. Used in drinking water, wastewater, aquaculture, food processing. Denmark has extensive UV installations.',
    limitations: 'Requires clear water - suspended solids and turbidity reduce effectiveness. No residual disinfection in distribution system. Fouling of quartz sleeves requires cleaning. Energy consumption. Does not remove dissolved contaminants (only disinfects).',
    status: 'Mature proven technology. Industry standard for tertiary disinfection.',
    references: ['Xylem/Wedeco', 'Trojan Technologies', 'Danish UV equipment manufacturers', 'US EPA UV Disinfection Guidance'],
    images: ['/Photos/UV System/Picture62.png', '/Photos/UV System/Picture63.jpg'],
  },
  {
    id: 27,
    name: 'Rotary Drum Filter',
    country: 'France',
    category: 'stp-improvement',
    currentGap: 'Primary treatment screens miss fine solids. Need for better solid-liquid separation before biological treatment or membrane systems.',
    technology: 'Rotating cylindrical screen with fine mesh (10-100 microns) for continuous removal of fine suspended solids from wastewater.',
    novelty: 'Continuous self-cleaning operation. Compact design with high hydraulic capacity. Low pressure drop.',
    details: 'Drum rotates partially submerged in wastewater flow. Water flows from inside to outside through screen cloth. Solids accumulate on inside surface. As drum rotates, captured solids are lifted above water level, dewatered by gravity, and backwashed off by spray nozzles into collection trough. Removes TSS, fibers, particles before biological treatment or membranes. Reduces organic load to secondary treatment, improves clarifier performance, protects membranes from fouling. Applications: primary treatment enhancement, membrane pre-filtration, industrial process water.',
    fieldApplication: 'Widely used in European WWTPs. Standard equipment in aquaculture industry. Applied in paper mills, food processing, textile industries. Thousands of installations globally.',
    limitations: 'Screen blinding with oily or sticky solids. Regular maintenance of spray nozzles and bearings. Pre-screening of large objects required. Not effective for dissolved contaminants.',
    status: 'Mature commercial technology.',
    references: ['BOKELA (Germany)', 'Hydrotech (Veolia)', 'ANDRITZ', 'French water treatment equipment manufacturers'],
    images: ['/Photos/Rotary drum/Picture65.jpg', '/Photos/Rotary drum/Picture64.png'],
  },
  // Smart Monitoring
  {
    id: 28,
    name: 'Remote Sensing & Earth Observation',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Limited spatial coverage of ground-based water quality monitoring. Difficult to monitor large or inaccessible water bodies.',
    technology: 'Satellite and aerial imagery analysis using multispectral and hyperspectral sensors to monitor water quality parameters over large areas.',
    novelty: 'Synoptic view of entire water bodies. Historical data analysis for trend detection. Can monitor parameters like turbidity, chlorophyll, algae blooms, temperature.',
    details: 'Satellites (Sentinel-2, Landsat, Planet) capture images in visible and infrared bands. Water-leaving radiance correlates with water quality parameters. Algorithms derive: suspended sediment concentration, chlorophyll-a (algae indicator), turbidity, colored dissolved organic matter (CDOM), water temperature, surface features (oil spills, algae blooms). Temporal resolution: daily to weekly depending on satellite. Spatial resolution: 10-30m for medium satellites, <5m for commercial high-res. Can integrate with hydrological models for predictive analysis. Particularly useful for: lake monitoring, coastal water quality, river basin management, compliance monitoring.',
    fieldApplication: 'Operational in Denmark and EU for water framework directive monitoring. Used globally for lake/reservoir management, HAB early warning, coastal monitoring. Applications in India for Ganga monitoring and reservoir surveillance.',
    limitations: 'Cloud cover limits optical observation. Algorithms need calibration with in-situ data. Limited penetration depth in turbid water. Cannot measure all parameters (no nutrients, pathogens). Temporal resolution lower than in-situ sensors.',
    status: 'Operational technology with growing adoption as satellite data becomes freely available.',
    references: ['DHI GRAS (Denmark)', 'European Space Agency', 'Copernicus program', 'NASA', 'Planet Labs'],
    images: ['/Photos/Rotary drum/Picture64.png', '/Photos/Rotary drum/Picture65.jpg'],
  },
  {
    id: 29,
    name: 'Multi Parameter Water Quality Monitoring',
    country: 'England',
    category: 'smart-monitoring',
    currentGap: 'Traditional monitoring requires multiple sensors and complex installation. Lab analysis has delayed results. Need for real-time comprehensive data.',
    technology: 'Integrated multi-sensor probes measuring multiple water quality parameters simultaneously with single instrument.',
    novelty: 'One sonde measures 10+ parameters. Real-time data with telemetry. Reduced deployment and maintenance compared to multiple sensors.',
    details: 'Multi-parameter sondes include sensors for: physical parameters (temperature, pressure, depth, conductivity, turbidity, TSS), chemical parameters (pH, ORP, DO, specific ions with ISE), biological indicators (chlorophyll-a, phycocyanin, CDOM, FDOM), nutrient proxies. Data logging and telemetry transmit to cloud platforms. Used for continuous monitoring at fixed stations or profiling. Applications: drinking water reservoirs, wastewater effluent monitoring, river/stream monitoring, stormwater outfalls, industrial discharge compliance.',
    fieldApplication: 'Deployed globally at water utilities, environmental agencies, research stations. Thousands of units in operation. Leading UK manufacturers supply worldwide.',
    limitations: 'Sensor drift requires regular calibration. Biofouling in natural waters. Cost increases with number of parameters. Some parameters (like BOD, COD) cannot be measured directly - only proxies. Maintenance requirements in harsh environments.',
    status: 'Mature commercial technology. Industry standard for water quality monitoring networks.',
    references: ['YSI/Xylem (USA/UK)', 'Hach (UK)', 'Aquatic Informatics', 'In-Situ Inc.'],
    images: ['/Photos/Multi parameter Water Quality/Picture68.jpg', '/Photos/Multi parameter Water Quality/Picture69.jpg'],
  },
  {
    id: 30,
    name: 'AI-Driven Cloud Optimization for WWTPs',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Indian wastewater treatment plants face challenges in optimizing energy consumption, reducing greenhouse gas emissions, and adapting to fluctuating influent loads due to reliance on manual control and static operating strategies.',
    technology: 'Cloud-based artificial intelligence and machine learning platform that connects with SCADA systems to monitor, predict, and optimize wastewater treatment plant operations in real time.',
    novelty: 'Leverages advanced AI algorithms and predictive analytics to dynamically adjust aeration, nutrient removal, and process control, reducing energy and GHG emissions by 15–30%. Integrates with existing systems for adaptive, data-driven optimization.',
    details: 'The platform collects operational and sensor data from SCADA and uploads it to a secure cloud environment. Machine learning models are trained on historical data to understand relationships between influent load, process conditions, and effluent quality. The system predicts incoming loads and optimizes process parameters such as aeration intensity, chemical dosing, and flow distribution. It supports predictive maintenance and integrates weather and rainfall data for feed-forward control. Applicable to large-scale municipal WWTPs, the system helps improve compliance, stability, and energy efficiency while reducing manual intervention.',
    fieldApplication: 'Successfully implemented at advanced WWTPs in Denmark, Italy, the Netherlands, the UK, and the USA. Demonstrated 15–25% energy and 10–20% GHG reduction with improved effluent stability. Applicable for Indian utilities seeking digital transformation in WWTP operations.',
    limitations: 'Requires reliable and comprehensive SCADA data integration. Data quality directly affects model accuracy. Initial setup, calibration, and operator training are required. Ongoing subscription costs and cybersecurity considerations apply.',
    status: 'Initial response received. Presentation requested; awaiting further communication.',
    //references: ['DHI (Denmark)', 'BIOFOS (Denmark)', 'Envirosuite', 'SUEZ AQUADVANCED', 'Xylem Applied Water Systems'],
    images: ['/Photos/AI-Driven Cloud/Picture70.jpg', '/Photos/AI-Driven Cloud/Picture71.jpg']
  },


  {
    id: 31,
    name: 'Energy-Efficient Smart Control Systems',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'High energy consumption constitutes a major operational cost for wastewater treatment and water supply systems in India. Conventional fixed-speed pumps, blowers, and manual operation cause inefficiency.',
    technology: 'Energy-efficient Variable Frequency Drives (VFDs) integrated with smart control algorithms and real-time sensor feedback to optimize pump, blower, and mixer operations across water and wastewater infrastructure, including ZLD/MLD systems.',
    novelty: 'Dynamic control based on actual process requirements instead of fixed-speed operation. Enables 25–50% energy savings through real-time optimization of aeration, pumping, and flow control. Supports predictive and adaptive process regulation for ZLD/MLD and WWTP applications.',
    details: 'The system combines online sensors (DO, NH4, NOx, ORP), PLCs with advanced algorithms (PID, fuzzy logic, model predictive control), and VFDs for variable-speed operation. SCADA systems enable centralized monitoring. Control logic optimizes dissolved oxygen setpoints, pump/blower speeds, and process staging for energy efficiency. Ammonia-based aeration control (ABAC) adjusts DO in response to nitrification demand, while ORP-based control supports denitrification. Suitable for municipal WWTPs, water pumping stations, and industrial water systems. Demonstrated 15–40% energy savings, improved effluent stability, and extended equipment life.',
    fieldApplication: 'Extensively implemented in Denmark and other advanced water utilities worldwide. Applicable across municipal and industrial sectors in India, including ZLD/MLD facilities. Proven energy-saving performance in thousands of installations.',
    limitations: 'Requires proper sensor maintenance, system tuning, and compatibility with existing motor or pump setups. Initial investment in VFDs and control infrastructure.',
    status: 'Proven and mature technology. Communication with solution providers underway for deployment.',
    //references: ['Danfoss (Denmark)', 'Grundfos', 'Rockwell Automation', 'Siemens', 'WEF Energy Management Guidelines'],
    images: ['/Photos/Energy-Efficient Smart/Picture72.png']
  },

  {
    id: 32,
    name: 'IoT Monitoring for Real-Time Water Network',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Remote or inaccessible areas in water distribution networks often lack real-time monitoring of critical parameters such as flow, pressure, and quality, especially in regions with limited power or connectivity. Manual inspection and delayed detection lead to water loss and inefficiency.',
    technology: 'Internet of Things (IoT) network of smart, self-powered sensors and connected devices across water infrastructure that monitor and transmit real-time data on flow, pressure, and water quality.',
    novelty: 'Integrates energy-harvesting micro-hydro systems to power IoT sensors, enabling continuous, battery-free operation. Provides predictive insights and early leak or contamination detection for proactive water network management.',
    details: 'IoT sensors are installed at water sources, treatment plants, pump stations, and distribution mains. They monitor parameters such as flow, pressure, turbidity, conductivity, temperature, and residual chlorine. Data is transmitted via LoRaWAN, NB-IoT, or cellular networks to a cloud-based platform. Analytics enable leak detection, quality anomaly detection, and asset condition monitoring. The energy-harvesting design allows deployment in remote areas by converting water flow into electricity to power sensors. Supports digital twins and integration with SCADA for predictive maintenance and smart water management.',
    fieldApplication: 'Piloted with utilities in Denmark and Europe for continuous water network monitoring. Achieved world-class leakage reduction rates (5–10%) and improved operational efficiency. Suitable for decentralized and rural networks.',
    limitations: 'Requires steady water flow for energy generation. Coverage depends on communication network availability. Initial setup and calibration can be resource-intensive.',
    status: 'Contact initiated with developers; technology under active piloting and demonstration.',
    //references: ['Aqua Robur Technologies (Denmark)', 'Grundfos (Denmark)', 'Kamstrup (Denmark)', 'Siemens', 'Sensus/Xylem', 'www.aquarobur.com'],
    images: ['/Photos/IoT Monitoring for Real-Time Water Network-/Picture73.jpg']
  },
  {
    id: 33,
    name: 'N₂O Sensors',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Nitrous oxide (N₂O), a potent greenhouse gas nearly 300 times stronger than CO₂, is emitted from wastewater treatment plants but typically goes unmeasured. Conventional nitrate analysis in laboratories is time-consuming and lacks real-time process feedback.',
    technology: 'Real-time sensor system measuring dissolved and gaseous N₂O concentrations in biological treatment processes, providing insights into nitrogen removal efficiency and greenhouse gas emissions.',
    novelty: 'Provides continuous, real-time measurement of nitrous oxide emissions, enabling both nitrogen process optimization and climate impact reduction. Links nitrogen transformation dynamics directly with operational parameters.',
    details: 'N₂O sensors measure emissions from nitrification and denitrification stages, offering insight into process inefficiencies and nitrate removal rates. Technologies include tunable diode laser absorption spectroscopy (TDLAS), electrochemical sensors, and gas-phase analyzers. The emission of 1 kg of N₂O equals approximately 300 kg of CO₂ in climate impact. Real-time data enables process optimization — adjusting dissolved oxygen (DO), nitrite accumulation, and carbon dosing to minimize emissions. Applicable for municipal and industrial wastewater treatment plants, research facilities, and greenhouse gas inventory monitoring.',
    fieldApplication: 'Successfully applied in Danish wastewater treatment plants and research projects by Unisense Environment and DTU Environment. Growing adoption across progressive utilities in Europe and North America.',
    limitations: 'Limited to nitrogen-based emission monitoring. High sensor cost and maintenance requirements. Data interpretation requires process expertise. Not yet a regulatory requirement in most regions.',
    status: 'Emerging operational technology transitioning from research to field-scale deployment.',
  // references: ['Unisense Environment (Denmark)', 'DTU Environment (Denmark)', 'GWRC Research', 'https://youtu.be/zE3z5IGUP88?si=avdWB4JD6qUy8fg9'],
    images: ['/Photos/N2O Sensors- Unisense; Denmark/Picture74.png']
  },


  {
    id: 34,
    name: 'SulfiLogger H₂S Sensor',
    country: 'Denmark',
    category: 'smart-monitoring',
    currentGap: 'Hydrogen sulfide (H₂S) in wastewater systems causes severe odor pollution, infrastructure corrosion, and health hazards for workers. Conventional grab sampling and gas detectors do not provide continuous or real-time data.',
    technology: 'Robust, continuous electrochemical sensor system for real-time H₂S monitoring directly in wastewater, air, or process gases. Data is transmitted to SCADA or cloud-based IoT platforms for proactive control.',
    novelty: 'Provides online, real-time dissolved or gaseous H₂S data even in harsh sewer and treatment environments. Enables predictive odor and corrosion management and optimizes chemical dosing through IoT connectivity.',
    details: 'Electrochemical H₂S sensor measures dissolved or gaseous hydrogen sulfide in concentrations typically from 0.01–10 mg/L (in liquid) or ppm levels (in gas). Designed for installation in sewers, pumping stations, wet wells, and treatment process lines. Data is logged and transmitted via telemetry to SCADA or cloud dashboards for continuous monitoring. Applications include odor and corrosion control, optimization of dosing (oxygen, nitrate, iron salts), safety management in confined spaces, and corrosion risk mapping. Used in wastewater, biogas, and oil & gas sectors. Helps utilities prevent odor complaints, extend asset lifespan, and reduce chemical costs.',
    fieldApplication: 'Widely deployed in Denmark and internationally in wastewater utilities, biogas plants, and industrial sites. Proven under harsh field conditions for long-term monitoring.',
    limitations: 'Sensor requires periodic cleaning and calibration due to fouling in sewers. Needs stable power and telemetry connections. Direct contact with sludge or debris may affect accuracy.',
    status: 'Commercial and widely adopted with proven global installations.',
    //references: ['SulfiLogger (Denmark)', 'Unisense (Denmark)', 'OdaLog', 'Scientific literature on sewer sulfide control'],
    images: ['/Photos/H2S Sensor- SulfiLogger; Denmark/Picture76.jpg', '/Photos/H2S Sensor- SulfiLogger; Denmark/Picture75.png']
  },


  {
    id: 35,
    name: 'Ultrasonic Sludge Level Sensor',
    country: 'China',
    category: 'smart-monitoring',
    currentGap: 'Determining the sludge depth or amount of water to be filtered from sedimentation tanks is difficult using manual inspection or conventional methods.',
    technology: 'Ultrasonic echo detection system that determines sludge depth and thickness based on reflection of ultrasonic waves from different density layers.',
    novelty: 'Capable of distinguishing multiple sludge layers and measuring their thickness with high accuracy. Enables real-time monitoring of sludge blanket and discharge levels.',
    details: 'The instrument emits ultrasonic waves toward the bottom of the tank and receives reflected signals of varying intensities from sludge layers of different densities. Using these reflections, it calculates sludge depth, layer thickness, and blanket interface position. It supports self-cleaning, automatic energy adjustment for various media, and wide measurement ranges up to 10 meters. Applications include sewage treatment plants (STP), water treatment plants (WTP), mining washing plants, and power plants. Data can support sludge discharge optimization and chemical dosing control. Designed for low maintenance and stable long-term operation.',
    fieldApplication: 'No specific field applications reported yet. Currently in early-stage evaluation and demonstration.',
    limitations: 'Measurement range limited to approximately 10 meters. Foam and turbulence can interfere with signal accuracy.',
    status: 'Initial response received; presentation scheduling in progress.',
    //references: ['Tenjine, China', 'Endress+Hauser', 'Siemens', 'ABB'],
    images: ['/Photos/Ultrasonic Sludge Level/Picture78.jpg', '/Photos/Ultrasonic Sludge Level/Picture77.png']
  },


  {
    id: 36,
    name: 'Sludge Concentration Sensor',
    country: 'China',
    category: 'smart-monitoring',
    currentGap: 'Difficult to continuously determine sludge solids concentration and densification requirements using conventional lab-based tests with delayed results.',
    technology: 'Online digital sensor for real-time measurement of sludge and suspended solids concentration using multi-beam infrared light transmission and optical filtering technology.',
    novelty: 'Simplifies sludge concentration measurement compared to conventional lab methods. Provides continuous and accurate monitoring with automatic air cleaning for stable performance.',
    details: 'The sensor operates on the principle of multi-beam infrared light transmission combined with optical bandpass filtering and modulated excitation to eliminate ambient light interference. It includes an automatic air-cleaning system for reducing fouling and ensuring reliable long-term operation. Offers strong anti-interference capability and stability. Measurement range typically up to 25 g/L. Applications include wastewater treatment plants (WWTPs), paper mills, coal washing plants, and power industries. Enables real-time monitoring for improved process control and reduced manual sampling.',
    fieldApplication: 'No specific field application reports available yet. Currently under evaluation and demonstration.',
    limitations: 'Not suitable for higher concentrations of activated sludge (>25 g/L). Requires calibration for accuracy and periodic maintenance of optical components.',
    status: 'Initial response received; presentation scheduling in progress.',
    //references: ['Tenjine, China', 'Hach (Solitax)', 'Endress+Hauser (Turbimax)', 'Yokogawa'],
    images: ['/Photos/Sludge Concentration Sensor- Tengine; China/Picture79.jpg', '/Photos/Sludge Concentration Sensor- Tengine; China/Picture80.png']
  },

  // Sludge/Solid Waste Treatment
 {
    id: 37,
    name: 'Reed Beds',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Sludge treatment through natural processes requires large land area and may cause gas emission problems.',
    technology: 'Engineered wetlands planted with reeds (Phragmites australis) that dewater, stabilize, and mineralize sludge through natural drainage and microbial activity in the root zone.',
    novelty: 'Natural, low-energy method for sludge treatment using reed roots to enhance drainage and microbial degradation.',
    details: 'Sludge from primary or secondary treatment is applied in layers to reed beds built over sand or gravel substrate. Water percolates down and drains through a collection system, while organic matter decomposes over time via aerobic and anaerobic microbial processes in the root zone. After several years, the mineralized sludge is removed and used as a soil conditioner or disposed of safely. Typically achieves 20–40% solids content. Requires 0.5–2 m²/PE of land depending on climate. Low operational cost and minimal maintenance. Suitable for small wastewater treatment plants (<5,000 PE).',
    fieldApplication: 'Widely implemented across Denmark and Northern Europe in small municipalities and rural areas. Proven operation in Danish plants such as Aarhus Vand with more than 30 years of successful experience.',
    limitations: 'Longer treatment time compared to thermal or pyrolysis methods. Requires large land area and favorable climate. Potential groundwater contamination risk due to leaching. Periodic harvesting required. Not suitable for large plants.',
    status: 'Communication under progress.',
    //references: ['Danish EPA', 'Aarhus University', 'Sludge Treatment Reed Beds Association', 'Reed Beds'],
    images: ['/Photos/Reed Beds- Aarhusvand; Denmark/Picture82.jpg', '/Photos/Reed Beds- Aarhusvand; Denmark/Picture81.png']
  },


  {
    id: 38,
    name: 'High Temperature and Pressure with Catalyst Technology',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Conventional sludge dryers densify the sludge only to a limited extent, causing disposal challenges.',
    technology: 'Sludge is dried under high temperature and pressure in the presence of a catalyst.',
    novelty: 'Dehydris™ Ultra (patented technology) is capable of drying sludge more effectively compared to conventional processes.',
    details: 'Utilizes HydroThermal Carbonization in a closed reactor. Produces ultra-dewatered sludge with up to 70% dry solids. Increases biogas production by 30–40% compared to standard thermal drying. The process operates with no odor, consumes 2–3 times less energy than conventional drying, and allows further use of the dried material as biosolids (fertilizer).',
    fieldApplication: 'Applied successfully in a municipal wastewater treatment plant in Handan, China.',
    limitations: 'Produces only partial removal of micropollutants.',
    status: 'No initial response received.',
    // references: [
    //   'SUEZ',
    //   'https://www.suez.com/-/media/suezglobal/files/dk/brochures/brochure_dehydris_ultra.pdf?open=true'
    // ],
    images: ['/Photos/High Temperature & Pressure with catalyst technology-Suez; Denmark/Picture83.jpg', '/Photos/High Temperature & Pressure with catalyst technology-Suez; Denmark/Picture84.png'],
  },

  {
    id: 39,
    name: 'Steam-Drying and Pyrolysis Technology',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Conventional sludge dryers densify the sludge only to a limited extent, causing disposal challenges.',
    technology: 'Biomass is dewatered, then dried under steam followed by pyrolysis (heating in the absence of air).',
    novelty: 'HECLA® 1,000 transforms waste biomass into a useful resource with minimal manpower for operation and can be monitored remotely.',
    details: 'Transforms sewage sludge into renewable thermal energy, soil-improving biochar, and activated carbon. The steam dryer dries dewatered biomass in an oxygen-free atmosphere with superheated steam at 200°C. In the pyrolysis oven, dried biomass is heated to 650°C in an oxygen-free environment. The resulting biochar can be used for soil improvement, fertilization, or upgraded into activated carbon.',
    fieldApplication: 'Full-scale implementation at several Danish wastewater treatment plants has demonstrated up to 90% reduction in sludge volume and significant carbon capture.',
    limitations: 'Requires consistent sludge input and involves high initial capital investment. Potential release of harmful gases such as dioxins and furans if toxic solids are used.',
    status: 'Not positive response obtained.',
    // references: [
    //   'Aquagreen company (Denmark)',
    //   'https://www.youtube.com/watch?v=RxOmnZtBwnc&t=2s',
    //   'https://www.sn.dk/art716024/odsherred-kommune/nyhed/epokegoerende-forsoeg-pyrolyse-fjerner-pfas-islam/'
    // ],
    images: ['/Photos/Steam-drying and pyrolysis technology/Picture85.png'],
  },

  {
    id: 40,
    name: 'Cyclones Sludge Settler',
    country: 'France; Denmark',
    category: 'sludge-treatment',
    currentGap: 'The sludge generated from conventional ASP is highly dilute (~1-5% concentration) and requires heavy treatment for discharge and return feed.',
    technology: 'Cyclonic feed of sludge through the instrument causes densification of sludge by centrifugation of solids.',
    novelty: 'The patented InDense™ technology improves sludge concentration and overall efficiency of the activated sludge process.',
    details: 'Employs high centrifugal forces within hydrocyclones to concentrate sludge. Cyclone devices separate the sludge into two fractions: the concentrated “good” sludge is returned to the plant, while the “bad” fraction is removed as excess sludge. This process increases STP efficiency, especially in winter months, by recycling sludge with higher solid concentrations. It reduces secondary clarifier area requirements, enhances treatment capacity, and allows sludge to settle 4–5 times faster than in conventional settling tanks.',
    fieldApplication: 'Increased the hydraulic capacity of Søholt wastewater treatment plant in Europe by 30%.',
    limitations: 'Only applicable for retrofitting in conventional activated sludge processes.',
    status: 'Initial response not received.',
   // references: ['SUEZ (Denmark)', 'Suez Densified Sludge'],
    images: ['/Photos/Cyclones Sludge Settler- Suez; Denmark/Picture86.png', '/Photos/Cyclones Sludge Settler- Suez; Denmark/Picture87.png'],
  },
  {
    id: 41,
    name: 'Smart Waste Management Solution',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'Indian cities suffer from overflowing bins, inefficient waste collection routes, high operational costs, and poor urban hygiene.',
    technology: 'IoT sensors (3D optical laser) in waste containers provide real-time fill level data to a cloud platform, enabling intelligent routing and optimized collection.',
    novelty: 'Automated real-time monitoring and AI-driven route optimization significantly reduce collection costs, environmental impact, and improve city cleanliness.',
    details: 'Applicable for municipal and commercial waste collection; optimizes routes, reduces trips, and improves resource allocation.',
    fieldApplication: 'Deployed for customers worldwide, showcasing improved efficiency and cost savings in urban waste collection.',
    limitations: 'Requires sensor installation in bins and an initial investment in the platform.',
    status: 'Communication is under progress.',
    //references: ['Nordsense (www.nordsense.com)'],
    images: ['/Photos/Smart Waste Management Solution- Nordsense; Denmark/Picture89.jpg', '/Photos/Smart Waste Management Solution- Nordsense; Denmark/Picture88.png'],
  },

  {
    id: 42,
    name: 'Ecogi System',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'India faces challenges in efficiently segregating and pre-treating organic waste for biogas production, limiting its energy and fertilizer potential.',
    technology: 'Mechanical pre-treatment system for source-separated organic waste, creating a pure biopulp suitable for anaerobic digestion.',
    novelty: 'Handles diverse packaging and efficiently removes impurities, maximizing biogas yield and producing a clean, ready-to-use fertilizer (biopulp).',
    details: 'Processes municipal organic waste to feed biogas plants, improving efficiency and output. Enhances circular economy for food waste.',
    fieldApplication: 'Utilized by public authorities and private companies in waste management, with pulp use as fertilizer.',
    limitations: 'Requires organized collection of organic waste for optimal performance.',
    status: 'Communication is under progress.',
    //references: ['Ecogi'],
    images: ['/Photos/Ecogi System- Ecogi; Denmark/Picture90.png', '/Photos/Ecogi System- Ecogi; Denmark/Picture91.png'],
  },
  {
    id: 43,
    name: 'Solid Waste Recycling',
    country: 'Denmark',
    category: 'sludge-treatment',
    currentGap: 'India needs efficient, specialized machinery to process diverse and challenging waste streams (e.g., tires, e-waste, plastics) for higher recycling rates.',
    technology: 'Develops and manufactures machinery for recycling various waste types, including tires, cables, aluminum, e-waste, and MSW.',
    novelty: 'Provides robust, specialized equipment and complete recycling solutions for specific, hard-to-process waste streams to maximize material recovery.',
    details: 'Offers shredders, granulators, and sorting systems for large-scale recycling facilities, converting waste into valuable secondary raw materials.',
    fieldApplication: 'Global presence with installations in numerous countries for tire recycling, e-waste processing, and other specialized waste streams.',
    limitations: 'High capital investment for full-scale recycling plants.',
    status: 'Communication is under progress.',
   // references: ['ELDAN Recycling (www.eldan-recycling.com)'],
    images: ['/Photos/Solid waste Recycling/Picture92.jpg', '/Photos/Solid waste Recycling/Picture93.jpg'],
  },
  {
    id: 44,
    name: 'Azortum Solid Waste Sorting',
    country: 'Estonia; Finland',
    category: 'sludge-treatment',
    currentGap: "India's mixed waste streams often have low recycling rates due to inefficient and labor-intensive sorting processes.",
    technology: 'Advanced sorting and recovery technology for plastics, papers, tyres, and construction waste using sensor-based identification.',
    novelty: 'Offers modular and scalable solutions to improve recycling performance, allowing higher purity and recovery from complex waste streams.',
    details: 'Designed for large-scale Material Recovery Facilities and suitable for modernizing existing plants or building new efficient sorting lines. Construction and demolition waste is reused as filling material for roads and underlayers. Tyres are converted into oils through pyrolysis. Wood chips and paper are reused as external fuel. Plastic packaging materials are sent to companies to be used for making new products.',
    fieldApplication: 'The company has installed successful plants in several countries like Latvia and Estonia.',
    limitations: 'Requires investment in specialized sorting equipment.',
    status: 'Communication is under progress.',
   // references: ['Azortum (www.azortum.com)'],
    images: ['/Photos/Azortum solid waste sorting/Picture1.png', '/Photos/Azortum solid waste sorting/Picture2.png'],
  },
  {
    id: 45,
    name: 'WAGABOX® Technology – Upgrading Landfill Gas into Renewable Natural Gas (RNG)',
    country: 'France, USA, Canada, Spain',
    category: 'sludge-treatment',
    currentGap: 'India needs sustainable methods to manage organic waste and landfill gas, converting them into renewable energy sources.',
    technology: 'Collects, stores & converts landfill gas into biomethane using advanced membrane filtration.',
    novelty: 'Transforms a major source of greenhouse gas emissions (landfill gas) into a high-value, vehicle-fuel biomethane.',
    details: 'Waste is stored in airtight geotextile membrane. The methane gas released from organic breakdown is collected & stored filtered to make it pure (~98% purity). Methane produced is used in homes & other purposes throughout the city. Reduction in emissions and generating revenue.',
    fieldApplication: 'Multiple operational sites in France, US, Canada, and Spain converting landfill gas into biomethane. 30 landfill gas have been upgraded units in operation worldwide.',
    limitations: 'Requires sufficient methane production from landfill gas and is capital intensive.',
    status: 'Communication is under progress.',
   // references: ['WAGA Energy www.waga-energy.com'],
    images: [
      '/Photos/WAGABOX® technology/Picture3.jpg',
      '/Photos/WAGABOX® technology/Picture4.png'
    ]
  },
];